### ISSUE TITLE
Reimplement code snippets in UI

### ISSUE THREAD

**Issue by Saladoc** [dzikoysk/reposilite#1003]
### What happened?

When the repository URL is long enough that it's forced to wrap in the repository details module the result is incoherent with regards to the box size and the line numbers.

Also, if it comes close to having to wrap, the text clashes with the bounds.

![image](https://user-images.githubusercontent.com/36816545/147461963-ff601513-e3c2-437c-b9a2-a5f0bb0ef048.png)
![image](https://user-images.githubusercontent.com/36816545/147462237-f477b1ed-3492-4945-ae64-12de61abf9f0.png)

### Reposilite version

3.x

**Comment by WithoutAName25** [comment]
That's an issue of koca/vue-prism-editor: koca/vue-prism-editor#117

**Comment by dzikoysk** [comment]
This library has several issues and it's not frequently updated lately, so in the end we may just need to switch to another one :<

**Comment by dzikoysk** [comment]
Also, chaning tabs in card throws exception:

```
Uncaught (in promise) TypeError: Window.getComputedStyle: Argument 1 is not an object.
    setLineNumbersHeight Editor.ts:144
    handler2 Editor.ts:111
    promise callback*nextTick runtime-core.esm-bundler.js:246
    handler2 Editor.ts:110
```

Related to:

* https://github.com/koca/vue-prism-editor/issues/131

**Comment by dzikoysk** [comment]
https://github.com/koca/vue-prism-editor looks kinda abandoned, I think we should migrate to a new library that provides code highlighting / try to color those snippets without any library

**Comment by TheTechRobo** [comment]
No experience with Vue but how about https://github.com/justcaliturner/simple-code-editor ?

**Comment by dzikoysk** [comment]
Looks pretty nice, we could give it a try! Would you like to try to submit a PR? Here's the component we need to update:

* https://github.com/dzikoysk/reposilite/blob/main/reposilite-frontend/src/components/card/CodeSnippet.vue

**Comment by WithoutAName25** [comment]
I have implemented code snippets with simple-code-editor. I had to overwrite some default css ([here](https://github.com/WithoutAName25/reposilite/blob/65e233bfd17621459cfc32d2ea928fae9ef47a68/reposilite-frontend/src/components/card/CodeSnippet.vue#L43-L61)) and i had to use [this workaround](https://github.com/justcaliturner/simple-code-editor/issues/20#issuecomment-1249311876). Maybe this library is better than the old one but it is not perfect. I don't know if we should search for another one or use this one.

**Comment by dzikoysk** [comment]
Nice! I think it's fine 🤔
