### ISSUE TITLE
GH-431: OpenID Connect (OIDC) support.

### ISSUE THREAD

**Issue by EthanDevelops** [dzikoysk/reposilite#1009]
### Request details

This would allow users to authenticate using OIDC which would allow for more permissions and user types. 

This is similar to #924 
A spring library would probably work as well:
https://spring.io/projects/spring-security/
https://github.com/mitreid-connect/OpenID-Connect-Java-Spring-Server

**Comment by dzikoysk** [comment]
Looks like there is a couple of auth services, but I'm not sure how it works and what we need to do to support this. Do you know what kind of action we need to take to somehow provide a communication between Reposilite existing access tokens <--> auth providers, or do we need to reimplement whole auth system, etc.

**Comment by EthanDevelops** [comment]
> do we need to reimplement whole auth system, etc. to make it right?

Most likely, however, implementing an Oauth2-friendly auth system would greatly increase security.

**Comment by EthanDevelops** [comment]
Then you would be able to integrate standards like LDAP, ODIC, SAML, etc. easier.
But I’m sure theres a library that works with the current auth system.
