### ISSUE TITLE
Support PAC4J security engine

### ISSUE THREAD

**Issue by dzikoysk** [dzikoysk/reposilite#1011]
### Request details

https://www.pac4j.org:

* https://github.com/dzikoysk/reposilite/issues/924
* https://github.com/dzikoysk/reposilite/issues/1009

**Comment by EthanDevelops** [comment]
https://github.com/pac4j/javalin-pac4j

**Comment by dzikoysk** [comment]
Ok, so I've made some research about it and I see some issues related to this topic. 

The first one is just the type of authentication form. Currently, Reposilite (and pretty much all microservice-like apps) uses stateless API to communicate between client (e.g. frontend, maven, external apps) and server (one or more instances).

![stateless](https://user-images.githubusercontent.com/4235722/150143228-fdbe763f-27eb-448e-a29d-effb3509a88e.png)

In pac4j it's pretty much represented by direct clients and there are authenticators that works this way:

![authenticators](https://user-images.githubusercontent.com/4235722/150143624-ff0bd898-436a-471f-8930-9c0c1413694a.png)

Speaking of OAuth based services, OIDC and in general all indirect clients:

![session](https://user-images.githubusercontent.com/4235722/150143882-ed52af6e-f9b6-4030-a592-ed87af94439e.png)

The indirect mechanism requires session to store authentication related stuff secured:

![session clients](https://user-images.githubusercontent.com/4235722/150144111-cad9e900-af1e-47db-92a5-634b53d55a84.png)

Because we can't really use session, that's just not an option for us. Of course, the OAuth implementation can expose JWT token and it could be up to the client to properly handle it, but to be honest, what's the benefit of this feature anyway then?

What's the real scenario of using alternative auth method, despite of easier logging to web ui, I guess there is no real benefit of it as it doesn't really work with Maven itself. 🤔

**Comment by pauliesnug** [comment]
@dzikoysk You could try looking into https://docs.gradle.org/current/userguide/declaring_repositories.html#sub:http-header-auth, since this would allow for PAC4J tokens and credentials to be passed as HTTP headers. This could allow for a custom Gradle plugin that allows for OAuth2-handled Maven publishing!

**Comment by dzikoysk** [comment]
When we were talking about this feature, Reposilite only had access tokens. In 4.x I'm going to add a regular user system, so it makes sense to provide OAuth - it'll be easier to manage people in the organization. In such case, each user would generate their access tokens in the UI, so I guess it's no longer an issue 😅

**Comment by pauliesnug** [comment]
> When we were talking about this feature, Reposilite only had access tokens. In 4.x I'm going to add a regular user system, so it makes sense to provide OAuth - it'll be easier to manage people in the organization. In such case, each user would generate their access tokens in the UI, so I guess it's no longer an issue 😅

Oh awesome! I still do wonder if with these new user access tokens in 4.x, it would be possible to have a flow where you generate tokens, and then it automatically logs you into any Maven repository provided. Maybe by modifying `~/.gradle/gradle.properties` to include the token? Or something more advanced-- not sure
