### ISSUE TITLE
Provide an API endpoint for a latest snapshot file

### ISSUE THREAD

**Issue by ANutley** [dzikoysk/reposilite#1012]
### Request details

As an example I would like to grab the latest snapshot from <https://repo.anutley.me/#/snapshots/me/anutley/GitCord/1.0-SNAPSHOT>. An endpoint to achieve this would be extremely helpful. Perhaps both an endpoint to return the jar file itself, and another to return the version, in this case `GitCord-1.0-20211230.200052-3`. Thanks in advance :)

**Comment by EthanDevelops** [comment]
Sort of like how Jenkins has lastSuccessfulBuild and you can get the artifact?

**Comment by ANutley** [comment]
Yes, I think it would be extremely beneficial to have a way to retrieve the latest snapshot, especially for end users. It would for example make it easy to create a (for example) snapshot.anutley.me webserver which would always serve users the latest snapshot available.

**Comment by dzikoysk** [comment]
We already have this feature in API for standard artifacts, but we don't support snapshots yet, so it's a good enhancement to this :)
