### ISSUE TITLE
(bug): Github thinks that the /docs/support.html file is contributing docs.

### ISSUE THREAD

**Issue by EthanDevelops** [dzikoysk/reposilite#1013]
### What happened?

https://github.com website
iOS 15.2 
When submitting a contribution to the repo, Github thinks that the /docs/support.html file is a “Support guidelines” file.
![image](https://user-images.githubusercontent.com/66741050/147789123-9a36e330-fbb4-4cc2-9089-cfb9daf611d4.jpeg)
  

### Reposilite version

3.x

**Comment by dzikoysk** [comment]
It points to proper contribution file:

![image](https://user-images.githubusercontent.com/4235722/147789435-3986693a-e82b-45d7-86fb-4634bde90f1e.png)

So it's just a visual bug 🤔 Kinda strange tbh, might be a good idea to report them

**Comment by EthanDevelops** [comment]
Oh ok thanks
