### ISSUE TITLE
Docker 'token-generate root m' : command not found

### ISSUE THREAD

**Issue by theirman** [dzikoysk/reposilite#1025]
### What happened?

Hello to all
My name is Thierry and I started today the implementation of reposilite to manage a team maven repository. So I'm new with reposilite. I installed the 3.0.0-alpha.16 version with docker and I started it as a daemon without any problem. Now, I'm trying to generate the authorization tokens : I connect in my container with the usual way (`docker exec -it -u root reposilite /bin/bash`) and then I run the command `token-generate root m` as indicated in the documentation but the command `token-generate` is not found.

Has anyone encountered this bug before? Is it related to the fact that this is an alpha version?

Thanks for your help
Thierry 

### Reposilite version

3.x

### Relevant log output

```shell
[theirman@sicpa 1.0]$ docker images
REPOSITORY                      TAG                 IMAGE ID            CREATED             SIZE
docker.io/dzikoysk/reposilite   3.0.0-alpha.16      f8b81bb8e4e3        3 days ago          452 MB


[theirman@sicpa 1.0]$ docker ps
CONTAINER ID        IMAGE                                          COMMAND                  CREATED             STATUS              PORTS                  NAMES
c948e58408d7        docker.io/dzikoysk/reposilite:3.0.0-alpha.16   "/bin/sh -c 'exec ..."   2 hours ago         Up 5 months         0.0.0.0:8080->80/tcp   reposilite


[theirman@sicpa 1.0]$ docker exec -it -u root reposilite /bin/bash

root@c948e58408d7:/app# token-generate root m
bash: token-generate: command not found

root@c948e58408d7:/app# updatedb
root@c948e58408d7:/app# locate token-generate
root@c948e58408d7:/app#
```

**Comment by dzikoysk** [comment]
Resolved on Discord with:

![image](https://user-images.githubusercontent.com/4235722/148065660-7aa65977-0985-4205-98fc-fd8cc97f7e7a.png)

**Comment by theirman** [comment]
To be complete for those who would encounter this kind of problem: 
- start the docker container in interactive mode (example: `docker run -it --name reposilite -v reposilite-data:/app/data -p 8080:80 docker.io/dzikoysk/reposilite:3.0.0-alpha.16)
- launch the creation of the token for the root user `token-generate root m` and copy the token
- stop the container with CTRL+C
- start the container as a daemon: `docker start reposilite`.
- access the web console and login with the token as root
- you're done! :) 

And if you have other tokens to create, you don't need to redo the whole process above, you can create them in the CONSOLE tab of the web interface

Thanks again @dzikoysk

**Comment by dzikoysk** [comment]
Thanks for summary, I'll link issue related to docs rewrite for 3.x, so we can improve this section :)

* #557

**Comment by hereisderek** [comment]
do we have a way to create a permanent user/password during docker creation? 

kinda like 
```
REPOSILITE_OPTS: "--token {{ user.name }}:{{ user.pass }}"
```
but permanent / one off
