### ISSUE TITLE
Similar issue with authorization with maven as with gradle

### ISSUE THREAD

**Issue by cdorn** [dzikoysk/reposilite#1052]
### What happened?

Maven tries to upload jar without authorization header which is then declined.
Previously experienced elsewhere:
https://stackoverflow.com/questions/48631422/maven-not-adding-authorization-header

Extending the config in settings.xml beyond username and password helps:
``<server>
  <id>some.repo</id>
    <configuration>
        <httpHeaders>
            <property>
                <name>Authorization</name>
                <value>Basic (hash)</value>
            </property>
        </httpHeaders>
    </configuration>
<username>... </username>
<password>... </password>
</server>
``
perhaps something to update the documentation with (and not really a bug)
Many thanks for your efforts.

### Reposilite version

2.x

**Comment by dzikoysk** [comment]
Well, it shouldn't be a part of default config, Maven should properly handle auth phase without this extra header configuration. Are you absolutely sure that you're using latest version of Maven and deploy plugin?

**Comment by cdorn** [comment]
interestingly Maven (3.6.3 , maven-deploy-plugin:2.7:deploy (default-deploy) ) authenticated for the pom and sha1 files which where all uploaded successfully, but just not the jar. 
In any case I|m not getting some base64 exception on reposilite's side that I will investigate why and let you know. Also, yes, this should not have to be a default config aspect, but perhaps just extra just as done for gradle.

**Comment by cdorn** [comment]
ok, the Base64 problem was that I set the authentication header wrong, with that fixed it worked perfectly.

**Comment by dzikoysk** [comment]
To avoid strange behaviours, I also recommend to bump plugins to latest versions, e.g. [`maven-deply-plugin:2.7`](https://mvnrepository.com/artifact/org.apache.maven.plugins/maven-deploy-plugin) is already 11 years old. There were a lot of changes since then and in most cases it's fully compatibile with previous setups.

**Comment by dzikoysk** [comment]
I think we can close this :)
