### ISSUE TITLE
Javadoc route for latest release.

### ISSUE THREAD

**Issue by mufinlive** [dzikoysk/reposilite#1080]
### Request details

It pretty much just gets the latest release from the `maven-metadata.xml` and redirects to that Javadoc route. Will improve reposilite as I feel like this is a pretty normal use case, maybe sharing a link somewhere and not wanting to update it every single time.

**Comment by dzikoysk** [comment]
This feature will be available in Javadoc plugin for Reposilite 3.0.0-alpha.20
