### ISSUE TITLE
Google cloud storage support

### ISSUE THREAD

**Issue by duncte123** [dzikoysk/reposilite#1083]
### Request details

It would be nice if reposilite supported [google cloud](https://cloud.google.com/storage/docs/json_api/) next to s3.
I would prefer to use google cloud storage instead of s3 since it's a lot cheaper.

Files stored on google cloud can be accessed on the internet when the proper policy is set, an example of one of these URLs could be `https://storage.googleapis.com/my-gcloud-bucket-name/com/example/project/1.0.0/project.jar`
API documentation can be found on this page https://cloud.google.com/storage/docs/json_api/ and a free tier is available if you upload less than 5GB a month.

**Comment by dzikoysk** [comment]
Right, probably https://github.com/googleapis/google-cloud-java might be a good candidate for client with https://www.testcontainers.org/modules/gcloud/ for integration tests.

**Comment by NyCodeGHG** [comment]
Google Cloud Storage buckets should work just fine as they also use the s3 protocol.

**Comment by dzikoysk** [comment]
Oh, good to know. If so, then it should work like you said. We're compatible with a few similar services - tests are running against [Localstack](https://github.com/localstack/localstack) and I'm also using [MinIO](https://min.io/) as self-hosted solution.

**Comment by duncte123** [comment]
Just set it up myself and can confirm that it works like a charm

**Comment by dzikoysk** [comment]
Awesome :)
