### ISSUE TITLE
Add cache for proxy result

### ISSUE THREAD

**Issue by Cavalcantifer** [dzikoysk/reposilite#109]
It might be interesting to cache the results obtained by the proxy on the remote directories to avoid downloading it every time.
There may already be an option to do this, but I haven't found it...
Thanks for your help!

**Comment by dzikoysk** [comment]
I'm pretty sure that #85 feature request addresses this topic :)

**Comment by Cavalcantifer** [comment]
Yes sorry I hadn't seen it, but that's exactly it! :)
