### ISSUE TITLE
Fast double-click on browser entry may request incorrect path

### ISSUE THREAD

**Issue by Osnixer** [dzikoysk/reposilite#1119]
### What happened?

Duplicate path

https://user-images.githubusercontent.com/77621271/153897214-61043152-148b-49b0-af83-578bc7887a92.mp4

### Reposilite version

3.x

**Comment by Phinner** [comment]
I have this issue too!

**Comment by dzikoysk** [comment]
It's pretty much related to Vue and router handler that changes URI faster than renders a new list of entries :/
