### ISSUE TITLE
Blank Page on Safari

### ISSUE THREAD

**Issue by ffried** [dzikoysk/reposilite#1133]
### What happened?

After running the application and opening the frontend in Safari, I get a blank page.

Looking at the JS-Console, the following appears:
<img width="474" alt="image" src="https://user-images.githubusercontent.com/1689782/155727565-12ca63bd-f1ea-4331-9b38-444bbb9028ee.png">

After a quick search, it seems like this is the underlying issue: https://stackoverflow.com/questions/51568821/works-in-chrome-but-breaks-in-safari-invalid-regular-expression-invalid-group

### Reposilite version

3.x

**Comment by dzikoysk** [comment]
That's quite strange tbh, could you share full error? :)

**Comment by dzikoysk** [comment]
Ok, I've checked it with BrowserStack Safari and indeed there is no stacktrace 😳 Kinda strange, but in general it's a bug in semver-regex library:

* https://github.com/sindresorhus/semver-regex/issues/20

The library looks kinda dead anyway, so we may need to move to some alternative solution :/

**Comment by ffried** [comment]
Wow, that was quick. Thank you!
