### ISSUE TITLE
Docker (-Compose) deployment with environment not possible

### ISSUE THREAD

**Issue by ffried** [dzikoysk/reposilite#1134]
### What happened?

I'm trying to deploy Reposilite using Docker-Compose together with a postgresql database.

I'm using the `-Dreposilite.property=value` syntax to configure the properties. However, it fails as soon as there are spaces in a value. I've tried quoting the value, escaping the spaces and quoting the complete `-D...` parameter. Nothing worked.
After playing around a while, I found that the values were passed unquoted in the `ENTRYPOINT` command, which seems to fail with a "Main class not found" error.
After overriding the entry point in the docker-compose.yml and quoting it there, it seems to work - at least it launches.
However, it seems like the values seem to be ignored. At least Reposilite still used an SQLite and the HTML meta tags still contained the default title etc. instead of the customized values.

### Reposilite version

3.x

**Comment by ffried** [comment]
For reference, here's the docker-compose service definition (`db` is a postgres service):

```
  reposilite:
    image: dzikoysk/reposilite:3.0.0-alpha.21
    depends_on:
      - db
    environment:
      JAVA_OPTS: >-
        -Dreposilite.database='postgresql db:5432 ${DB_NAME} ${DB_USER} ${DB_PASSWORD}'
        -Dreposilite.forwardedIp=X-Forwarded-For
        -Dreposilite.id=my-mvn-repository
        -Dreposilite.title='My Maven Repository'
        -Dreposilite.description='My Maven repository description'
        -Dreposilite.organizationWebsite=https://example.tld
        -Dreposilite.organizationLogo=https://example.tld/logo.svg
    networks:
      maven:
    ports:
      - "127.0.0.1:XXXX:80"
    volumes:
      - type: bind
        source: /some/persistent/path
        target: /app/data
    restart: unless-stopped```

**Comment by ffried** [comment]
I've now solved part of this by editing the local config file for the database, and then editing the shared config in the UI for the customization.

**Comment by dzikoysk** [comment]
Hi, this option has been removed from 3.x and is only available in 2.x. In 3.x you can just link modified configuration file with parameter:

* https://github.com/dzikoysk/reposilite/blob/57cd9c2cbf945f07f1062e92c830b7ba6e50c5e7/reposilite-backend/src/main/kotlin/com/reposilite/ReposiliteParameters.kt#L46

**Comment by ffried** [comment]
Ah, thanks! Does this also work for only "partial" overrides? e.g. leave most of the settings to their defaults but customize a few of them? Can I simply put the ones I'd like to modify in the file and they will override the defaults?

**Comment by dzikoysk** [comment]
Yes, should be fine :)
