### ISSUE TITLE
Close icon is broken in file browser adjustments

### ISSUE THREAD

**Issue by ffried** [dzikoysk/reposilite#1136]
### What happened?

The close icon looks a bit weird :)

<img width="432" alt="image" src="https://user-images.githubusercontent.com/1689782/155763999-ccb14765-11e3-4a71-8f0a-af1dcf0b1e4a.png">

### Reposilite version

3.x

**Comment by dzikoysk** [comment]
Yeah, looks like an issue with encoding. Can you see this unicode character in your browser?

`🗙`

**Comment by ffried** [comment]
@dzikoysk No, I can't see that icon on any of my devices (iOS and macOS) - neither in the GitHub mobile app nor Mail nor Safari (mobile and desktop) nor Firefox (desktop).

Thanks for fixing this!
