### ISSUE TITLE
Improve docker image

### ISSUE THREAD

**Issue by eshepelyuk** [dzikoysk/reposilite#117]
Hi @dzikoysk 

Tried to run via docker and experienced following issues I'd like to share with 

* Although README shows an example of overriding params via `JAVA_OPTS`, in reality passing `JAVA_OPTS` via `-e` option doesn't do anything, since this variable is not passed to `java` in `ENTRYPOINT` instruction ( i just tried to override Xms , port ) and actual docker always ignored the value.

* Dockerfile builds app from source, while it could just use a jar that is published to `Releases` and located in repo

In fact, I'm interested to try this software in docker and could countribute improved Dockerfile if you're interested.

**Comment by dzikoysk** [comment]
Fair point, at this moment the entrypoint is just hardcoded:

https://github.com/dzikoysk/reposilite/blob/0b0c7d6f42054f6d6fb0c3f38112603cccc39e25/Dockerfile#L24

`JAVA_OPTS` should be passed to the entrypoint `ENTRYPOINT exec java $JAVA_OPTS`. I'm not familiar with Docker and I'm open for your contributions to improve this area.

**Comment by eshepelyuk** [comment]
@dzikoysk why did you close the issue ?

**Comment by dzikoysk** [comment]
I develop a lot of public and private projects simultaneously and it helps me to keep it clean. The issue received a potential fix and in most cases that's enough - a lot of people just won't even respond

**Comment by eshepelyuk** [comment]
@dzikoysk i formally declare that i gonna provide a fix aka PR for this issue

**Comment by eshepelyuk** [comment]
@dzikoysk why closed again ? Dockerfile had not changed ?

**Comment by dzikoysk** [comment]
I've received feedback about some issues related to the current Dockerfile and it's why I had to take action, because current thread was opened for almost a month without any specific details. Details about changes in Dockerfile and build lifecycle:

* GH-140
* GH-142
* GH-143

These changes will be available in 2.7.0. In case of any new suggestions, report them in a new issue.

**Comment by eshepelyuk** [comment]
Unfortunately, I had no time to provide improvements with the speed that fits the release cycle of this project. So let it be closed, as soon as you consider no improvements needed.

**Comment by dzikoysk** [comment]
It is normal that people has other things to do :) In case of any new thoughts, just report a new issue.
