### ISSUE TITLE
Configure Kotlin linter for backend sources

### ISSUE THREAD

**Issue by dzikoysk** [dzikoysk/reposilite#1177]
### Request details

* https://github.com/pinterest/ktlint

**Comment by codesplode** [comment]
I am very familiar with ktlint, including writing custom rules, etc. so could help with this task if you have any other specifics in mind. Would you want to strictly use the default ruleset and codestyle?

The way I've used it in the past requires no additional gradle plugins if I remember correctly.

**Comment by dzikoysk** [comment]
This issue is blocked by #1081 now as it's really huge and breaking PR, so merge with proper conflict resolution on the main branch would be painful process :)

**Comment by codesplode** [comment]
Let me know how i can help. Feel free to assign this to me after merge is complete or if I can help with merge somehow.

**Comment by codesplode** [comment]
I went ahead and looked at #1081 and there are pretty small changes to the build.gradle.kts file for the backend, so I'm going to go ahead and branch my fork to add ktlint when I get a chance. I believe I can get that done with a few modifications to the gradle file only and have it ready for whenever it is needed.
