### ISSUE TITLE
Failure to load initial configuration from file upon startup with Docker

### ISSUE THREAD

**Issue by larsw** [dzikoysk/reposilite#1198]
### What happened?

Hi,

I've tried all permutations of `--local-config / --shared-config` and their respective `-mode` commands trying to setup Reposilite with initial repositories, but it just ignores the configuration I provide in a configuration file that I've volume mounted into the container.

Is this supposed to work?

### Reposilite version

3.x

**Comment by dzikoysk** [comment]
Yes, could you share your configuration file?

**Comment by larsw** [comment]
https://github.com/larsw/maven-sync-setup/blob/main/repo/reposilite.cdn

Also, see the `docker-compose.yml` file in the same directory.

**Comment by dzikoysk** [comment]
You can also take a look at new docs:

* https://reposilite.vercel.app/guide/setup
* https://reposilite.vercel.app/guide/docker

It works slightly different than in 2.x, let me know if you'll find it confusing.

**Comment by larsw** [comment]
Cheers - I'll take a look.

**Comment by larsw** [comment]
> --shared-configuration=/reposilite.cdn --shared-configuration-mode=copy

and

> REPOSILITE_OPTS: "--token admin:secret --shared-config=/reposilite.cdn --shared-config-mode=copy --port=8080"

is it `config` or `configuration` I should use in the arguments?

**Comment by dzikoysk** [comment]
Both should work:

* https://github.com/dzikoysk/reposilite/blob/def033d9e9d23ead064a7d1588c10b3a774074b4/reposilite-backend/src/main/kotlin/com/reposilite/ReposiliteParameters.kt#L55
