### ISSUE TITLE
Docker container should be stateless -> log only to stdout

### ISSUE THREAD

**Issue by larsw** [dzikoysk/reposilite#1199]
### What happened?

I found out that when I tried to override the port with `--port=8080` and by running the container as non-root, the
container tries to write to a log file in `/apps/logs`. Container images should really not be doing logging to files, and if they do, it should be to a well-defined volume mount point.

### Reposilite version

3.x

**Comment by dzikoysk** [comment]
Log should be located in $workDir/logs directory that is exposed as volume from container 🤔 I'll take a look at it later
