### ISSUE TITLE
Reposilite with Kubernetes/K8s

### ISSUE THREAD

**Issue by xieu90** [dzikoysk/reposilite#1201]
### What happened?

Hi, 
I'm trying to setup reposilite inside kubernetes/k8s/microk8s

following this post https://github.com/dzikoysk/reposilite/issues/360
I installed Komposer on my local linux machine and run 
kompose convert -f reposilite-dockerModified.yml
kompose can only work on version 3 --> i changed 3.9 to 3 and deleted environment, env etc and changed port to 80 80

version: "3.0"
services:
  reposilite:
    image: dzikoysk/reposilite:3.0.0-alpha.15
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 80:80
    volumes:
      - reposilite-data:/app/data
    restart: unless-stopped
volumes:
  reposilite-data: {}

after that i got 3 yml files for kubernetes (deployment, service, persistence)

using those 3 files (kubectl apply -f deployment, service, persistence)  i saw that reposilite works on my server, i could access web ui

hier is the log of pod/container in kubernetes is posted in relevant log output

The problem now is i cannot generate token to use in settings.xml
on local machine using java -jar reposilite.jar I can run these commands
token-generate admin
route-add admin */ rw
route-add admin releases rw
route-add admin /releases rw

but in kubernetes log I can only see the above console log.
if I login to console via 
portainer 
or 
kubectl exec -ti <pod-name> -n <pod-namespace> bash i cannot run those commands, if i run another java -jar reposilite.jar then i get the error that address is already used and bye bye

inside the pod a lot of linux command couldnt run either (ps, killall, pgrep etc...)  using apt-get install I can install only htop

any idea how i can stop the running repositile and rerun it in same console so that i can generate token?
Best regards

### Reposilite version

3.x

### Relevant log output

```shell
16:14:22.834 INFO | 

16:14:22.838 INFO | [0;32mReposilite [0m3.0.0-alpha.15

16:14:22.838 INFO | 

16:14:22.839 INFO | --- Environment

16:14:22.839 INFO | Platform: 16.0.2 (Linux)

16:14:22.839 INFO | Working directory: /app/data

16:14:22.839 INFO | Threads: 32 WEB / 16 IO

16:14:22.944 INFO | 

16:14:22.944 INFO | --- Loading plugins (10):

16:14:22.945 INFO | failure, settings, access-token, authentication, console, statistics, frontend, maven, badge, status

16:14:23.402 INFO | 

16:14:23.403 INFO | --- Settings

16:14:23.403 INFO | Loading shared configuration from database

16:14:23.548 INFO | Shared configuration has been loaded from database

16:14:24.065 INFO | 

16:14:24.065 INFO | --- Repositories

16:14:24.065 INFO | + releases (public)

16:14:24.065 INFO | + snapshots (public)

16:14:24.066 INFO | + private (private)

16:14:24.066 INFO | 3 repositories have been found

16:14:24.075 INFO | 

16:14:24.076 INFO | --- Access Tokens

16:14:24.076 INFO | Your instance does not have any access tokens yet.

16:14:24.076 INFO | To generate token, you can use --token flag to create temporary token:

16:14:24.076 INFO | $ java -jar reposilite.jar --token name:secret

16:14:24.076 INFO | Or using command in this terminal/through web dashboard:

16:14:24.076 INFO | $ help token-generate

16:14:24.144 INFO | 

16:14:24.145 INFO | Binding server at 0.0.0.0::80

16:14:24.150 WARN | Interactive CLI is not available in current environment.

16:14:24.151 WARN | Solution for Docker users: https://docs.docker.com/engine/reference/run/#foreground

16:14:24.785 INFO | Done (0.71s)!

16:14:24.786 INFO | 

16:14:24.793 INFO | Reposilite 3.0.0-alpha.15 Commands:

16:14:24.794 INFO |   failures - Display all recorded exceptions

16:14:24.794 INFO |   help [<command>] - List of available commands

16:14:24.794 INFO |   level <level> - Change current level of visible logging

16:14:24.794 INFO |   route-add <access_token> <path> <permissions> - Add new route to access token

16:14:24.794 INFO |   route-remove <to> <path> - Remove route from access token

16:14:24.794 INFO |   stats [<repository>] [<filter>] - Display collected metrics

16:14:24.795 INFO |   status - Display summary status of app health

16:14:24.795 INFO |   stop - Shutdown server

16:14:24.795 INFO |   token-generate [--secret=<value>] <name> [<permissions>] - Generate a new access token

16:14:24.795 INFO |   token-modify <name> <permissions> - Change token permissions

16:14:24.795 INFO |   token-rename <name> <new name> - Change token name

16:14:24.795 INFO |   token-revoke <name> - Revoke token

16:14:24.795 INFO |   tokens - List all generated tokens

16:14:24.796 INFO | 

16:14:24.796 INFO | Collecting status metrics...

16:14:24.796 INFO | 

16:14:25.799 INFO | Reposilite 3.0.0-alpha.15 Status

16:14:25.804 INFO |   Active: [1;32mtrue[0m

16:14:25.805 INFO |   Uptime: 0.01min

16:14:25.805 INFO |   Memory usage of process: 24.06M

16:14:25.805 INFO |   Active threads in group: 8

16:14:25.806 INFO |   Recorded failures: 0

16:14:25.806 INFO |   Latest version of Reposilite: [4;31m3.0.0-alpha.23[0m

16:14:25.806 INFO |
```

**Comment by dzikoysk** [comment]
Take a look at:

* https://reposilite.com/guide/docker#using-docker-compose

And let me know if it's helpful in your case :)

**Comment by xieu90** [comment]
hi, 
thank you for your help, 
I ran kompose twice with/without        - REPOSILITE_OPTS=--token admin:secret
and then ran 
persistence.yaml
with token deployment.yaml
service.yaml

then could access via admin/secret, generate token, adding role etc.
changed in settings.xml and could deploy to reposilite

after that i run 
without token deployment.yaml
service.yaml

and now everything works as expected.
thank you again for your help

I will leave the modified dockerfile here, it might be useful for anyone in future
`version: "3"
services:
  reposilite:
    image: dzikoysk/reposilite:3.0.0-alpha.15
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 80:80
    environment:
      - REPOSILITE_OPTS=--token admin:secret
    volumes:
      - reposilite-data:/app/data
    restart: unless-stopped
    stdin_open: true
    tty: true
volumes:
  reposilite-data: {}`
