### ISSUE TITLE
When using S3 storage provider, the dashboard's repository browser does not work as intended and fetches all files in one request

### ISSUE THREAD

**Issue by Idane** [dzikoysk/reposilite#1214]
### What happened?

Reproducible when S3 is the storage provider, when calling the `/api/maven/details/<repository>` endpoint, the entire bucket is retrieved as if all of the files are in the root directory - 
![image](https://user-images.githubusercontent.com/3495615/162673797-4035442a-4565-4690-a81b-2c31df94bb9f.png)

### Reposilite version

3.x

### Relevant log output

```shell
N/A
```

**Comment by dzikoysk** [comment]
Does this happen on the latest alpha.23?

**Comment by Idane** [comment]
@dzikoysk 
Whoops! Seems like I was on alpha.15.

Seems to work fine on .23. Thanks!
