### ISSUE TITLE
LdapAuthenticator fails with "Could not identify one specific result after filter" 

### ISSUE THREAD

**Issue by shuawest** [dzikoysk/reposilite#1246]
### What happened?

When configuring reposilite against an LDAP server the connector fails to filter users when there is more than one user in the directory. 

Adding a second user in LdapAuthenicatorTest.kt demonstrates this error, resulting in a failed test with output:
```
LdapAuthenticatorTest > should authenticate existing ldap user() FAILED
    org.opentest4j.AssertionFailedError: Expected success, but result errored with: <ErrorResponse(status=400, message=Could not identify one specific result)> // <-- from second filter statement in LdapAuthenticator.kt
        at app//org.junit.jupiter.api.AssertionUtils.fail(AssertionUtils.java:39)
        at app//org.junit.jupiter.api.Assertions.fail(Assertions.java:134)
        at app//panda.std.ResultAssertions.assertOk(ResultAssertions.java:14)
        at app//com.reposilite.auth.LdapAuthenticatorTest.should authenticate existing ldap user(LdapAuthenticatorTest.kt:117)
```

The root cause is in the LdapAuthenticator.kt authenticate function.  The first directory search filters users based on the auth request name matched to the userAttribute. There is a second directory search after the user is authenticated where only the userFilter is applied, however the authentication request name is not used nor available to that filter. 
```
.flatMap { createContext(user = it.first, password = authenticationRequest.secret) } // try to authenticate user with matched domain namespace
.flatMap { it.search(userFilter, userAttribute) } // <-- this search results in all users being returned from ldap that match the 'Maven Users' filter, not the only the target user                 
.filter({ it.size == 1 }, { ErrorResponse(BAD_REQUEST, "Could not identify one specific result after filter") })
``` 

Adding the userFilter with userAttribute matched with the authentication request name, as done in the first search resolves the error and makes the ldap connector functional against a realistic directory. 
```
.flatMap { createContext(user = it.first, password = authenticationRequest.secret) } // try to authenticate user with matched domain namespace               
.flatMap { 
    it.search(
        "(&(objectClass=person)(${userAttribute}=${authenticationRequest.name})${userFilter})", // filter result with user-filter from configuration                
        userAttribute
    ) 
} 
.filter({ it.size == 1 }, { ErrorResponse(BAD_REQUEST, "Could not identify one specific result after filter") }) // only one search result allowed                
``` 

I will send a PR with the fix and updated test reproducer update.

### Reposilite version

3.x

**Comment by dzikoysk** [comment]
Thanks for reporting this! I'm not LDAP user and I've pretty much learned about it while implementing this functionality, based on top of that test with stub embedded server. I'm open to any extra feedback related to this integration and how it should work - it's still alpha phase, so we can make some breaking changes.

**Comment by shuawest** [comment]
Thanks for merging the update. My goal with this PR was just to fix the issue to make it functional for a side project. I like this lightweight repository - great work.  The ldap connector is good for authentication - for keeping users/passwords external. It could get complex and bloated if you start to try to add authorization through ldap.  

I'd recommend using OpenID Connect if you want to expand this past authentication to authorization. A good OSS community that provides OpenID is KeyCloak (https://www.keycloak.org/).  I may come back and implement the client if/when I have the bandwidth. 

As a side note, my build isn't quite right. It would be great to have brief build.md document that describes the recommended distros and versions of the OS, JDK, nodejs, npm, etc that you build with for releases.

**Comment by dzikoysk** [comment]
I know, those advanced LDAP impls look like hell and I wanted to keep it as simple as possible. If [current setup](https://reposilite.com/guide/ldap) is enough for basic usage, I'm fine with it.

OpenID is a stateful identifity layer, such as the whole family of OAuth-like protocols. It means that the proper implementation more or less requires some kind of a shared context like e.g. session to properly exchange and maintain unique session identifier. On the other hand, Maven specification is based on top of the stateless authentication, so you're pretty much authenticating each request using credentials provided by Maven client in each request. Related issue:

* https://github.com/dzikoysk/reposilite/issues/1011

Speaking of building, we have a contributing guide with description in each module:

* https://github.com/dzikoysk/reposilite/blob/main/.github/CONTRIBUTING.md

JDK11+ & Node 14 should be enough to build Reposilite with `gradlew shadowJar` command. For tests, you also need an environment with Docker. We're still modifying this process, I'll try to make it clear for the final release of 3.0.
