### ISSUE TITLE
Web Interface returns 404

### ISSUE THREAD

**Issue by gmax9803** [dzikoysk/reposilite#127]
The web interface returns a 404 on all http requests. This was tested with a local installation and the one at https://repo.panda-lang.org. This causes some web browsers to sometimes act strangely.

![image](https://user-images.githubusercontent.com/27639180/86049455-0c2c7900-ba07-11ea-8104-b056e20abcbf.png)

**Comment by dzikoysk** [comment]
It's known issue. The 404 status is served, because Maven uses the same address to search for an artifact and it is required to declare that the requested file does not exist. In the future I'll discover the possibility to trick it.
