### ISSUE TITLE
3.x - REST API - /{repo}/* - Artifact path isn't interpreted

### ISSUE THREAD

**Issue by ThraaxSession** [dzikoysk/reposilite#1273]
### What happened?

REST API / Get repository - Artifact path isn't interpreted:
![image](https://user-images.githubusercontent.com/3085830/166152533-ed6d7dc3-a53a-4c7c-baff-2bcd2fe7da4a.png)

### Reposilite version

3.x

**Comment by dzikoysk** [comment]
Yeah, we should probably replace all `*` in OpenApi routes description with named parameters 🤔

**Comment by ThraaxSession** [comment]
Oh and btw. I've got another issue. If you like I can create another ticket.
But when I enabled swagger in properties. I am not able to access swagger-ui. https://<mydomain>/swagger. :/

**Comment by dzikoysk** [comment]
You have to restart your Reposilite instance, because we're currently not able to support hot-reloading of Swagger UI :<
