### ISSUE TITLE
Add trash button functionality to the UI

### ISSUE THREAD

**Issue by vLuckyyy** [dzikoysk/reposilite#1303]
### Request details

Add trash button for delete file/directory

Like this:

![image](https://user-images.githubusercontent.com/65517973/168492898-1460954c-6ff5-4785-a432-f73256df697b.png)

**Comment by dzikoysk** [comment]
![x](https://c.tenor.com/XMVz4JeILUMAAAAM/ladies-and-gentleman-we-got-him.gif)
