### ISSUE TITLE
Unable to retrieve latest JAR by endpoint

### ISSUE THREAD

**Issue by ThraaxSession** [dzikoysk/reposilite#1328]
### What happened?

I am not able to download my latest JAR by this call:
```
curl -X 'GET' 'https://mydomain/api/maven/latest/file/releases/technology/iatlas/spaceup/SpaceUp' -H 'accept: */*'
{"status":404,"message":"File not found"}
```
It works to gather the JAR version. But it's a snaptshot version uploaded to release:
```
curl -X 'GET' 'https://mydomain/api/maven/latest/version/releases/technology/iatlas/spaceup/SpaceUp' -H 'accept: */*'
{"isSnapshot":false,"version":"0.25.0-SNAPSHOT"}⏎     
```

### Reposilite version

3.x

**Comment by dzikoysk** [comment]
Issue was caused by misconfiguration:

* https://discord.com/channels/204728244434501632/875148821842231296/977533889956425828

Suppressed by:

* https://github.com/dzikoysk/reposilite/issues/1331
