### ISSUE TITLE
Adding current Reposilite version to web ui

### ISSUE THREAD

**Issue by ThraaxSession** [dzikoysk/reposilite#1332]
### Request details

It would be awesome to see the current version of the app in the web ui. As many of us will just download the app (hopefully automatically someday) and will firstly look on the ui that everything is fine and new.

**Comment by Tree4Free** [comment]
How about having it as a footer?

![image](https://user-images.githubusercontent.com/9843834/186020336-b55aa6ca-4f2f-4f97-ad62-6d36eadb5449.png)

**Comment by ThraaxSession** [comment]
@Tree4Free if it will be solved as footer. We could add additional information like the commit hash. Which might be also interesting to have a look on the current version.

**Comment by wvffle** [comment]
I can do this in some free time.

**Comment by dzikoysk** [comment]
Resolved in #1655
