### ISSUE TITLE
Download authentication only for specific repositories

### ISSUE THREAD

**Issue by jaqobb** [dzikoysk/reposilite#137]
Hey, I know there is a possibility to enable `fullAuthMode` however I believe this will make all repositories (and not specific ones) require authentication. Is there (if not then will there be) a way to make specific repositories require authentication in order to see, upload and download them?

Like, let's say that I currently have `public-releases` and `public-snapshots` repositories and they are publicly available (everyone can see and download artifacts from them) to everyone and authentication is only necessary when you want to upload a new artifact. Can I make for example `private-releases` and `private-snapshots` repositories where authentication is required for everything (seeing, downloading and uploading)? If not, is there a chance for it to be implemented?

**Comment by dzikoysk** [comment]
Nope, at this moment we cannot use mixed authentication policy for different repositories, but I was thinking about it lately. If you really need this now, I may recommend to just run two separate instances of Reposilite.

**Comment by jaqobb** [comment]
I'm currently just setting up repository for future artifacts so I can pretty much wait. I haven't really looked at the source code but if you want I can try and make a PR for that issue.

**Comment by dzikoysk** [comment]
It might be achieved in various ways, what's your proposal to implement this feature?

**Comment by jaqobb** [comment]
At first I thought of adding a section to the configuration where you can specify what repositories should be treated as "private" (that is as repositories that require special permissions to either download artifacts from them or upload new ones). We already have tokens that are used for authentication and they also store path at which they are effective so I thought of implementing some sort of primitive permissions system that you can use to indicate possibilities of each token in regard of private repositories. With this you will be able to generate a token for a private repository that can only download artifacts from them and not upload. This also allows then to generate a token that will allow only to upload new artifacts or a token that can both download artifacts and upload new ones (i.e. admins).

I think that frontend shouldn't list private repositories (for obvious reasons) and they should only be visible for you once you log in to the dashboard.

This also won't really affect public repositories as they don't require authentication to download artifacts from them so in case of public repositories, tokens should just indicate that you can indeed upload new artifacts there (like they pretty much do now).

I mentioned permissions system but we can just use 2 booleans for download and upload permissions. However I believe a special system for that will be much better and more scalable and might even get used in the features added in the future.

**Comment by dzikoysk** [comment]
Playing with private and public artifacts in repositories and modifying access tokens is not the best idea. In fact, this issue raises edge case problem 🤔 What do you think about marking private repositories with e.g. `.` character? Let's say:

```yaml
repositories:
  - 'releases'
  - '.private'
```

The dot will be removed from repository name ofc and we will just exclude these repositories from public indexing.

**Comment by jaqobb** [comment]
That's a solution. I think that it's actually even a better one because this doesn't require setting up a new section in the configuration etc. and relies purely on checking if the repository starts with `.` or just having a boolean that indicates repository status (and in that case boolean can be set up when repositories are detected/loaded). Not sure if configuration is being automatically migrated to the new version if it's detected but if it's not then this also makes it more sort of backward compatible.

I'm also not really sure what do you mean by saying that modifying access tokens is not the best idea? Do you mean like editing tokens data structure or just editing existing tokens' data?

**Comment by dzikoysk** [comment]
I may try to find some time tomorrow to implement this, I've just made some publications about this project and I'm done with it  today.

> I'm also not really sure what do you mean by saying that modifying access tokens is not the best idea? Do you mean like editing tokens' data structure or just editing existing tokens' data in general?

Both honestly, I don't want to modify existing structures as long as it is not really necessary, I'm pretty sure that in most cases we are able to work out better solutions.
