### ISSUE TITLE
Adding delete  artifact functionality to the UI

### ISSUE THREAD

**Issue by qlanduril** [dzikoysk/reposilite#1373]
### Request details

As Dzikoysk mentioned in discord server there is no such possibility. One needs to mount and delete the artifact manually.

[Mentioned discord dialogue](https://discord.com/channels/204728244434501632/875148821842231296/972182996310437888)

**Comment by dzikoysk** [comment]
It's a duplicate of #1303, but I'll rename the origin issue to make it more explicit about the requested feature
