### ISSUE TITLE
Support for Prometheus/Grafana

### ISSUE THREAD

**Issue by Deftu** [dzikoysk/reposilite#1414]
### Request details

To my knowledge, both Prometheus and Grafana are very commonly used analytics/statics platforms.

As shown to me by Dzikoysk in the Discord server, [Javalin has functionality](https://javalin.io/tutorials/prometheus-example) to track web requests built-in. This just needs to be implemented somehow. (I'm hoping through the statistics plugin?)

**Comment by Saladoc** [comment]
If the plugin interface provides enough hooks (or access to internal statistics) this could be realized via a plugin. I recommend that actually for prometheus, as it requires another endpoint to be added.

**Comment by dzikoysk** [comment]
Prometheus plugin will be available in the next release. Currently it mostly exposes Jetty related stats, but I guess we could extend in the future. Preview:

* https://reposilite.com/plugin/prometheus
