### ISSUE TITLE
Some shortcuts do not work on the terminal

### ISSUE THREAD

**Issue by RoinujNosde** [dzikoysk/reposilite#1442]
### What happened?

Pressing UP or DOWN doesn't show the previous/next command in the history:

![image](https://user-images.githubusercontent.com/6441328/177045592-5f447ca4-28be-4ba9-9619-2f7a2f6cd46a.png)

Pressing CTRL left or right:

![image](https://user-images.githubusercontent.com/6441328/177045727-2a5a3cc3-27ad-47f4-a88d-63ea459b9dcd.png)

### Reposilite version

3.x

**Comment by dzikoysk** [comment]
Unfortunately it's not something we can address in Reposilite, full support for CLI-like experience would require a CLI-library or sth like that and it's slightly hard to integrate with logging libraries. For general better experience we're slowly trying to provide all that stuff in UI, so I think it's just a better direction for project :)

Similar issue:
* #638

Anyway, thanks for your feedback!
