### ISSUE TITLE
Frontend isn't able to display packages located in S3 (Contabo - Ceph) storage.

### ISSUE THREAD

**Issue by shitzuu** [dzikoysk/reposilite#1464]
### What happened?
Frontend isn't able to display packages located in S3 storage.

## Screenshot presenting the issue.
![image](https://user-images.githubusercontent.com/63915083/177822327-561b7d54-8768-4be5-a470-c5c4583d1a8f.png)

## Screenshot presenting the content of S3 storage.
![image](https://user-images.githubusercontent.com/63915083/177822462-f4380d00-278b-41a6-adde-e24beb111b16.png)

### Reposilite version

3.x

**Comment by dzikoysk** [comment]
Resolved on Discord:
Ceph.io used by Contabo does not support `listObject`, every request to API returns empty list. Because it's not compatible with S3 specification, we're not able to support it.
