### ISSUE TITLE
Docker - Manifest for dzikoysk/reposilite:latest not found

### ISSUE THREAD

**Issue by Szczurowsky** [dzikoysk/reposilite#1466]
### What happened?

When trying to pull image from docker hub an error occurs.
Pulling using docker pull dzikoysk/reposilite:3.0.0-rc.2 works withot any problem

### Reposilite version

3.x

### Relevant log output

```shell
*****@vmi616770:~$ sudo docker pull dzikoysk/reposilite
[sudo] password for *****: 
Using default tag: latest
Error response from daemon: manifest for dzikoysk/reposilite:latest not found: manifest unknown: manifest unknown
```

**Comment by dzikoysk** [comment]
Currently I'm not distributing images as `latest`, because `3.0.0-rc.2` is not a stable version. I'm going to restore this tag for 3.0.0+.

Full list of tags:
* https://hub.docker.com/r/dzikoysk/reposilite/tags

**Comment by zugazagoitia** [comment]
Wouldn't people on 2.X.X have a broken installation once ```latest``` becomes available.

**Comment by dzikoysk** [comment]
Previously `latest` was built on top of the latest commit and in the end I've renamed it to `nightly` quite a long time ago. In 3.x we have better build & distribution phase, so `latest` will properly point to the latest **released** version.
