### ISSUE TITLE
Cross-user session sharing

### ISSUE THREAD

**Issue by bazyliszku** [dzikoysk/reposilite#1472]
Console shows my commands, as not mine, but executed by user that last logged in.
I tested, and logged on my account, then on "Demo" account on other browser/device/whatever. Console on my account shows:
CLI | demo@10.10.10.1> help

instead of my login.

**Comment by dzikoysk** [comment]
Thanks for the report and sorry for late response - I'm slightly busy lately.

Looks like a visual bug in logs, in general anyone who has access to the console uses management token, so it's not that problematic, but I'll be definitely fix it in the next release.

**Comment by dzikoysk** [comment]
Fixed! Just to be clear, because this issue does not lead to any security vulnerability despite of misleading log entry, I won't label it as security issue :)

**Comment by bazyliszku** [comment]
Ok, thanks for the quick response (in opposition to my response to your
e-mail ;) )
Karolina


sob., 23 lip 2022 o 01:07 dzikoysk ***@***.***> napisał(a):

**Comment by dzikoysk** [comment]
Sure :) Repository is linked with our Discord server, so we see notifications immediately. I have quite a lot of correspondence & spam on my mail, so if I missed something and didn't respond, could you send it once again?
