### ISSUE TITLE
Add permission validation before click delete button/before render delete button (front-end)

### ISSUE THREAD

**Issue by Rollczi** [dzikoysk/reposilite#1473]
### Request details

![image](https://user-images.githubusercontent.com/49173834/180281705-ffbdaa29-7187-4529-af43-fd94bd191116.png)

**Comment by dzikoysk** [comment]
It's only a visual bug on frontend in public repositories, but yeah, would be great to hide it if user doesn't have access to the given path. Thanks for reporting this :)
