### ISSUE TITLE
Bugged tabs navigation on Safari 15.4

### ISSUE THREAD

**Issue by itxsvv** [dzikoysk/reposilite#1477]
### What happened?

macOS Monterey
Safari 15.4

Steps
1. Open default view
2. Click on "Console" -> Nothing happens!
3. Click on "Settings" -> Console appear
4. Click on "Console" - > Settings appear

Problem affect only Safari 

### Reposilite version

3.x

**Comment by dzikoysk** [comment]
Do you have some errors in console? Unfortunately I don't have macOS, so it's kinda hard for me to diagnose this issue.

**Comment by itxsvv** [comment]
Logs is empty ;(

**Comment by dzikoysk** [comment]
Looks like it works properly on macOS Monterey - Safari 15.3:

![obraz](https://user-images.githubusercontent.com/4235722/181753993-e6950184-ef72-4edf-9920-0194b7ee4ba2.png)

Do you have some browser plugins or maybe you use some kind of proxy like Nginx?

* https://reposilite.com/guide/nginx
* https://reposilite.com/guide/nginx#additional-notes
* https://reposilite.com/guide/cloudflare

**Comment by itxsvv** [comment]
I disable safari all plugins, bug still present
Strange - "Repository details" frame works good, problem only with main menu
![Screen Shot 2022-07-29 at 16 55 46](https://user-images.githubusercontent.com/27562849/181775697-83a2af1e-70c8-4509-9d02-0375438d8086.png)

**Comment by dzikoysk** [comment]
Could you try to launch Reposilite on your localhost and check if this issue still occurs?

**Comment by dzikoysk** [comment]
Feel free to reopen this issue when you'll find time to test it on localhost and we could confirm if it's a bug or not  :)
