### ISSUE TITLE
Swagger plugin doesn't work

### ISSUE THREAD

**Issue by P3ridot** [dzikoysk/reposilite#1505]
### What happened?

https://pastebin.com/5N3B7B3N

after trying to use plugin this error appears

### Reposilite version

3.x

**Comment by dzikoysk** [comment]
`Javalin 5.0.0-SNAPSHOT` had another breaking change, we'll adapt in 3.0.1. Plugins from workspace directory should work tho:

* https://github.com/dzikoysk/reposilite/tree/main/reposilite-backend/src/test/workspace/plugins

**Comment by dzikoysk** [comment]
#1508
