### ISSUE TITLE
Allow import of tokens via command line option

### ISSUE THREAD

**Issue by hanikesn** [dzikoysk/reposilite#1506]
### Request details

During the migration to 3.0.0 (great release btw.) I noticed that it doesn't seem possible anymore to specify the access tokens list statically. The only way to import a `tokens.json` file seems to be via the interactive console. As we're deploying Reposilite as standalone, mostly stateless proxy in our Kubernetes clusters, we like the configuration to be as static as possible and ideally we'd be able to specify the the tokens.json file to be used as command line argument.

Thank you very much!

Workaround:
```
 echo "token-import /app/config/tokens.json" | java -jar /app/reposilite.jar
```

**Comment by dzikoysk** [comment]
Hi and thanks :)

In general I recommend to use standard database like MySQL/PostgreSQL, but if you really don't want to have any SQL database at all, I think you can use `--token user:secret` flags:

* https://reposilite.com/guide/setup#parameters

You can specify multiple temporary tokens like that, unfortunately without routes, but it should be enough just for the proxy I think. Token on 3.x has slightly more complicated structure:

* https://reposilite.com/guide/tokens

So it'd be slightly inconvenient to do it manually. Let me know if it helps or it's still not enough and why, so we can consider another approach.

**Comment by dzikoysk** [comment]
What's the status of this issue? @hanikesn :)

**Comment by hanikesn** [comment]
@dzikoysk can be closed from my side as things work with the workaround I added in the issue above.
