### ISSUE TITLE
JDK 8 support

### ISSUE THREAD

**Issue by Medioman92** [dzikoysk/reposilite#1507]
### What happened?

the docs say that Reposilite is compatible with JDK 8-18 but running with 1.8.0.201 produces the following error
`Exception in thread "main" java.lang.UnsupportedClassVersionError: com/reposilite/ReposiliteLauncherKt has been compiled by a more recent version of the Java Runtime (class file version 55.0), this version of the Java Runtime only recognizes class file versions up to 52.0`
![image](https://user-images.githubusercontent.com/7137172/183445671-cbc41696-7d2f-4930-97be-c857caa7b559.png)

### Reposilite version

3.x

### Relevant log output

```shell
Exception in thread "main" java.lang.UnsupportedClassVersionError: com/reposilite/ReposiliteLauncherKt has been compiled by a more recent version of the Java Runtime (class file version 55.0), this version of the Java Runtime only recognizes class file versions up to 52.0
```

**Comment by dzikoysk** [comment]
Oh, in 3.0.0 release it's updated to JDK11+, I need to update that information in guide too, nice catch :)

**Comment by Medioman92** [comment]
@dzikoysk thanks for the quick feedback...maybe since the docs points toward the use of 3.0, the JVM requirements should be better documented ?

**Comment by dzikoysk** [comment]
Hmm... Do you have something specific in mind? Currently it's listed where it's needed, so per each release on github + in setup guide on main site.
