### ISSUE TITLE
Make javadocs more accessible for users

### ISSUE THREAD

**Issue by Tigerpanzer02** [dzikoysk/reposilite#1510]
### Request details

What about having an eye on -javadoc files which redirects to the javadoc url / opens the javadoc
![image](https://user-images.githubusercontent.com/37453987/184434715-063a4f03-784c-4fab-9de6-69342730df50.png)
like it is on pom files for example?
![image](https://user-images.githubusercontent.com/37453987/184434837-cab2bbed-2e7b-4253-9169-3b959be380b2.png)

Or any other visual things to get the javadocs faster instead of typing it manually in browser url?

**Comment by dzikoysk** [comment]
This feature was requested like two times in the past on our Discord, so I think it might be a good idea to support this at some point. Unfortunately, I'm not sure how to do it yet through plugin, because plugins can't really modify frontend as it's pretty much standalone web app. We'd have to provide some kind of a strange API/bridge for plugins to make it possible or merge javadocs plugin to the main codebase.

**Comment by Tigerpanzer02** [comment]
> This feature was requested like two times in the past on our Discord, so I think it might be a good idea to support this at some point. Unfortunately, I'm not sure how to do it yet through plugin, because plugins can't really modify frontend as it's pretty much standalone web app. We'd have to provide some kind of a strange API/bridge for plugins to make it possible or merge javadocs plugin to the main codebase.

Or allowing interactions with frontend 🙃

**Comment by dzikoysk** [comment]
Well... in theory it could be nice, but I'd like to avoid tricky impl, because it's just a pain to maintain it 😓

**Comment by Tigerpanzer02** [comment]
Yeah I get that point anyway there should be something made if there are more requests for the same feature 😇

**Comment by dzikoysk** [comment]
I'm currently taking a break due to my vacation, but I'll try to do sth about that if I'll find sane solution

**Comment by PlayerSchark** [comment]
> This feature was requested like two times in the past on our Discord, so I think it might be a good idea to support this at some point. Unfortunately, I'm not sure how to do it yet through plugin, because plugins can't really modify frontend as it's pretty much standalone web app. We'd have to provide some kind of a strange API/bridge for plugins to make it possible or merge javadocs plugin to the main codebase.

I think an implementation into the code would be a good idea. I personally don't see a reason to leave it as a plugin.
