### ISSUE TITLE
Separate permission for publishing/fetching artifacts in private repositories

### ISSUE THREAD

**Issue by realkarmakun** [dzikoysk/reposilite#1511]
### Request details

Right now to publish/fetch artifacts from private repo we need Management permission. I can see a usecase where we need to give access to the repo either to getting or publishing public repo but it's still undesirable to give access to console and instance settings using keys. Ideally it would be nice to have fetching and publishing permissions separately that can be granted to a token without giving access to reposilite management

**Comment by dzikoysk** [comment]
I think you're looking for routes: 

* https://reposilite.com/guide/routes

**Comment by realkarmakun** [comment]
Oh yeah sorry I missed these while reading docs, nevermind then
