### ISSUE TITLE
404 with maven-metadata.xml

### ISSUE THREAD

**Issue by fullwall** [dzikoysk/reposilite#1545]
### What happened?

Deployed a modularised maven project to a fresh reposilite instance
maven-metadata.xml file present locally but not accessible online unless an additional slash is appended
Compare:
https://maven.citizensnpcs.co/repo/net/citizensnpcs/citizens-parent/2.0.30-SNAPSHOT/maven-metadata.xml
https://maven.citizensnpcs.co/repo/net/citizensnpcs/citizens-parent/2.0.30-SNAPSHOT//maven-metadata.xml

### Reposilite version

3.x

**Comment by dzikoysk** [comment]
Both URLs works for me, are you sure it's not an issue with cache on your side?

**Comment by fullwall** [comment]
Yes, it was a cache issue. Thanks.
