### ISSUE TITLE
Absolute paths deny usage behind a reverse proxy with path redirection

### ISSUE THREAD

**Issue by lixfel** [dzikoysk/reposilite#158]
I want to use reposilite behind a reverse proxy that e.g. http://localhost/maven directs to http://localhost:81 which would be reposilite behind a firewall.
This redirection works, but reposilite uses only absolute paths. The site doesn't load, since reposilite wants /js/api.js, which would be only availible under /maven/js/api.js. This goes on with /api etc....

I see 2 solutions to this issue:

- Usage of relative paths
- Defining a prefix (e.g. "/maven" or usually "/") in reposilite.yml which is prepended to all absolute urls

**Comment by dzikoysk** [comment]
This feature is already implemented in GH-154 through GH-148 with fixes in GH-155 and GH-157. It will be available in release 2.7.0
