### ISSUE TITLE
Dashboard shows empty directory list after login for private/hidden maven repo

### ISSUE THREAD

**Issue by mkocus** [dzikoysk/reposilite#1590]
### What happened?

After updating the reposilite from 2.x to latest 3.x I've got the following problem - private or hidden maven repositories are visible only for users with admin permission. But if you navigate (using URL) to 1 level into the repository structure it can be seen. Details below.

1. Have 3 maven repositories configured as: public (/public), hidden (/hidden), private (/private).
2. Create other user token with read path permission for "/"
3. Login into the new user (created above).

What is see:
Only public repository is seen. But the other ones - hidden and private are not visible on dashboard. But if you navigate using the address bar (via maven.example.com/#/private or  maven.example.com/#/hidden) it can be normally accessed and is visible on the dashboard.

I'm using version 3.0.3

### Reposilite version

3.x

**Comment by dzikoysk** [comment]
Sorry for late response, I was quite busy lately. Looks like a visual bug for `/`, thanks for reporting this.

**Comment by dzikoysk** [comment]
Fix is available in 3.0.4 :)
