### ISSUE TITLE
Kubernetes guide

### ISSUE THREAD

**Issue by dzikoysk** [dzikoysk/reposilite#1592]
### Request details

* https://github.com/dzikoysk/reposilite/blob/main/reposilite-site/data/guides/installation/k8s.md

**Comment by dzikoysk** [comment]
* https://github.com/dzikoysk/reposilite/issues/360?

**Comment by joshuasing** [comment]
As I run Reposilite on Kubernetes I could try to make a draft of this guide if you wish.
I could also potentially make a helm chart, however it would require another GitHub repository and and optionally a CNAME record (to use the domain `helm.reposilite.com` or something else for it)

**Comment by dzikoysk** [comment]
Sure, I'm still not that familiar with Kubernetes so I'd need to learn about to prepare useful guide & helm chart, but if you'd like to help me with that I'd be glad, I hope I'll learn about it too :P 

Speaking of the helm chart repository, do we need standalone repo or we could somehow keep it in module called like `reposilite-helm` 🤔

**Comment by joshuasing** [comment]
I think it's possible to do it under a module, I would have to do some experimenting though.
I believe it also requires a branch named `gh-pages` or similar to indicate to GitHub Pages to deploy it.

**Comment by dzikoysk** [comment]
Hmm do we need to update helm chart per each release? 🤔

**Comment by joshuasing** [comment]
I believe that would be best as then people can downgrade if there's a problem, etc.
