### ISSUE TITLE
Mute subscriber that tries to write to closed output

### ISSUE THREAD

**Issue by dzikoysk** [dzikoysk/reposilite#1604]
### Request details

![obraz](https://user-images.githubusercontent.com/4235722/195849061-491c5202-0208-4586-be52-b8155d6b7b05.png)

Probably caused by: https://github.com/dzikoysk/reposilite/blob/main/reposilite-backend/src/main/kotlin/com/reposilite/console/infrastructure/ConsoleWebSocketHandler.kt#L69

**Comment by Anuran12** [comment]
@dzikoysk I would like to do this.. but don't know how to solve this... please guide

**Comment by dzikoysk** [comment]
I think that simple try-catch around ctx.send() for ClosedChannelException could be enough, this error is pretty random and it's hard to reproduce it, we will just observe the result :)

**Comment by Anuran12** [comment]
> I think that simple try-catch around ctx.send() for ClosedChannelException could be enough, this error is pretty random and it's hard to reproduce it, so we will just observe the result :)

Maybe I could not do it.. you better to assign someone else.. sorry to bother 😢

**Comment by P-DR0ZD** [comment]
Can I be assigned I think I could solve it

**Comment by P-DR0ZD** [comment]
What should be done when the exception is caught?

**Comment by dzikoysk** [comment]
I think we can safely mute it by just logging it at `DEBUG` level? 🤔
