### ISSUE TITLE
gradle: could not publish multiple artifacts at one time 

### ISSUE THREAD

**Issue by javaone199** [dzikoysk/reposilite#1608]
### What happened?

gradle: could not publish multiple artifacts at one time. 
After publishing the first one, then error: peer not authenticated.

 ```
publishing {
    publications {
        publicationOne(MavenPublication) {

        }

        publicationTwo(MavenPublication) {

        }
    }
}
```

gradle publish

gradle version: 6.9.2.

### Reposilite version

3.x

**Comment by javaone199** [comment]
How to start reposilite in debug mode so that Intellij debugger can attach it remotely? thanks.

**Comment by dzikoysk** [comment]
Reposilite itself uses multiple publications, so I guess it's an issue with misconfiguration. Peer not authorized usually means you're using unknown certificate, so your JVM on localhost refuses to connect to the given url. Did you configure ssl in this case?

Reposilite runs on pure JVM, so all you need is to run process with enabled remote debugging. They're some guides how to configure IJ with it. Anyway, I don't think it's necessary.

**Comment by javaone199** [comment]
Use apache2 SSL reverse proxy in front of reposilite on Ubuntu. There are two publications. The first one can be deployed successfully. But the second one fails with error message "peer not authenticated". SSL certificate is OK because of no problems from web access. thanks.

**Comment by dzikoysk** [comment]
Does the second publication requests Reposilite? In latest.log file in work dir you should see that Reposilite rejected connection with given status code & message.

**Comment by javaone199** [comment]
From the latest.log,  the first artifact was deployed successfully, but there are no messages on the 2nd one. no error messages.

**Comment by dzikoysk** [comment]
If there's no log for 2nd publication, it means that Reposilite instance didn't receive those requests at all, so it most likely was rejected by something between Gradle and Reposilite, like e.g. proxy. I'd recommend to take a look at your proxy log to see if it might be the case.

**Comment by javaone199** [comment]
I will take look at proxy. From the latest.log, there are also many checksum (md5, sha256, sha512,etc) files deployed. Are they also uploaded by Gradle or generated by reposilite on server side? thanks.

**Comment by dzikoysk** [comment]
It's generated by Gradle, Reposilite 3.x does not modify your publication content (2.x modified metadata files).

**Comment by javaone199** [comment]
I am trying to understand the source code. For uploading an artifact, it is a http PUT? One http PUT for jar, and one http PUT for each checksum file, right? what are the responses expected by Gradle if deploy successful? thanks.

**Comment by dzikoysk** [comment]
Yes, each file is deployed by Gradle in standalone PUT request.

**Comment by javaone199** [comment]
Apache proxy config:

 ```
   <VirtualHost *:443>
                ServerName mydomain.com
 
                ProxyPreserveHost On

                RewriteEngine On
                RewriteCond %{HTTP:Upgrade} =websocket [NC]
                RewriteRule ^/api/(.*) ws://127.0.0.1:8081/api/$1 [P,L]

                ProxyPass / http://127.0.0.1:8081/
                ProxyPassReverse / http://127.0.0.1:8081/

                ErrorLog ${APACHE_LOG_DIR}/reposilite_error.log
                CustomLog ${APACHE_LOG_DIR}/reposilite_access.log combined

                SSLEngine on
                SSLCertificateFile      /etc/ssl/mydomain-cert.pem
                SSLCertificateKeyFile   /etc/ssl/mydomain-key.pem
        </VirtualHost>
```

No logs are found in reposilite_error.log or reposilite_access.log (both empty).

**Comment by javaone199** [comment]
Tried a dummy servlet for deployment

```
protected void doPut(HttpServletRequest req,
        HttpServletResponse resp) throws ServletException, IOException {

    resp.setStatus(HttpServletResponse.SC_OK);
}
```
gradle publish

If using https for repository URL, it will issue the same error message(peer not authenticated) after uploading the first artifact. 
If using http for repository URL, it will be successful without error.

Tried on local Tomcat9 without proxy.

**Comment by dzikoysk** [comment]
I still don't think your issue is related to Reposilite itself, especially if it's working without SSL setup. For Reposilite (and any other http app) it doesn't really matter if there's SSL setup on proxy or not.

Unfortunately I don't know much about Apache to somehow help you figure it out, but your issue is between `Gradle <--> Proxy`, so I'd try to resolve that here. You can try to update Gradle to 7.x & test your setup with Nginx instead of Apache for instance.

**Comment by javaone199** [comment]
Gradle has the same issue with https for Tomcat without proxy. So it is not proxy issue. Tried the latest gradle 7.5.1, same problem.

**Comment by dzikoysk** [comment]
I'll take a look tomorrow. In the meantime, could you share your build files (without sensitive data), so I can check your setup?

**Comment by dzikoysk** [comment]
I've set 2 publications within the same artifact to the same repo with SSL & reverse proxy configuration:

```kotlin
publishing {
    repositories {
        maven {
            name = "panda-repository"
            url = uri("https://maven.reposilite.com/snapshots")
            credentials {
                username = System.getenv("MAVEN_NAME") ?: property("mavenUser").toString()
                password = System.getenv("MAVEN_TOKEN") ?: property("mavenPassword").toString()
            }
        }
    }
    publications {
        create<MavenPublication>("library1") {
            from(components.getByName("java"))
        }
        create<MavenPublication>("library2") {
            from(components.getByName("java"))
        }
    }
}
```

And Gradle published it twice (as expected):

```
> Task :publishLibrary2PublicationToPanda-repositoryRepository
Multiple publications with coordinates 'com.reposilite.test.gh1609:workspace-deploy-app:1.0.0-SNAPSHOT' are published to repository 'panda-repository'. The publications will overwrite each other!
```

Both publications are also visible in logs:

![obraz](https://user-images.githubusercontent.com/4235722/196683819-233aa370-56b0-46a6-ab53-d91376239993.png)

Looks it has has to be related to your infrastructure setup, not Reposilite.
