### ISSUE TITLE
Increase allowed length for repository name 

### ISSUE THREAD

**Issue by jcklie** [dzikoysk/reposilite#1609]
### Request details

I am currently migrating from artifactory to reposilite. Thank you for this awesome project, it is very easy to host, light-weight but still has all the functionality I need. My issue is now that our artifactory hosted repositories that had names longer than 32 characters, , which throws an exception when adding these to reposilite. Is it possible to increase the limit (maybe 64)/make it configurable and document it somewhere? Longer names work on Artifactory by default.

**Comment by dzikoysk** [comment]
Thanks :) As long as I can add new columns etc. I wonder if [Exposed](https://github.com/JetBrains/Exposed) will be able to detect change of varchar size, so we can increase this limit 🤔

**Comment by dzikoysk** [comment]
Now you can create a new instance of Reposilite or run it **once** with `--enable-migrations` flag to update current scheme and then it should support up to 64 characters. It's available in [3.0.5-SNAPSHOT (`-all` builds)](https://maven.reposilite.com/#/snapshots/com/reposilite/reposilite/3.0.5-SNAPSHOT) / docker nightly. It'll be also available in Reposilite 3.1.0 :)
