### ISSUE TITLE
Downloading of files is not restricted, everyone who knows the link to a file, can download it.

### ISSUE THREAD

**Issue by tobiashochguertel** [dzikoysk/reposilite#1616]
### What happened?

My repositories are hidden, so they are only visible when someone is logged in. But when someone knows the Link/ http url to a file, he can download it also when he is not logged in. I think that's a bug or a mising feature.

You can check it with: https://reposilite.pkg.hochguertel.work/releases/work/hochguertel/docs/as/code/structurizer-spring-boot/1.1.1/structurizer-spring-boot-1.1.1.jar

Visiting shows that there are no repositories listed when you are not logged in: https://reposilite.pkg.hochguertel.work

### Reposilite version

3.x

**Comment by dzikoysk** [comment]
Reposilite has 3 levels of visibility:
* `PUBLIC` - Everyone can download & index (browse) repository content
* `HIDDEN` - Everyone can download content without auth, but they're not able to index content of this repository, so they have to provide valid link to existing resource
* `PRIVATE` - Only authenticated users can access repository content

Looks like you're using `HIDDEN` visibility, you can change it to `PRIVATE` in the dashboard:

![obraz](https://user-images.githubusercontent.com/4235722/197227725-c4f0c444-e4fd-435a-bce6-bb5b982ac0fa.png)

**Comment by tobiashochguertel** [comment]
Thanks!
