### ISSUE TITLE
Repository details incorrectly constructed xml tags

### ISSUE THREAD

**Issue by IM-IgniteDEV** [dzikoysk/reposilite#1619]
### What happened?

In the overview on our repository dashboard we can see small "Repository Details" section, currently generated tags look like this:
 
`<repository>
  <id><id/>
  <name><name/>
  <url><url/>
<repository/>`

that's incorrect construction, accepted syntax looks like this:

`        <repository>
            <id></id>
            <name></name>
            <url></url>
        </repository>`

as you can notice, the only difference between these two examples is "/" contained in the closing tag, reposilite generated example is placing that slash in the wrong place.

### Reposilite version

3.x

**Comment by joshuasing** [comment]
I may have misread this, or may not be understanding, but this looks like the second example you provide:
https://github.com/dzikoysk/reposilite/blob/main/reposilite-frontend/src/helpers/maven/repository.js#L40-L44

I cannot seem to find the snippet that you are referring to :thinking:

**Comment by joshuasing** [comment]
I just checked my repository and they also seem to display like this, although I cannot figure out why the `/` is moved to the end
![image](https://user-images.githubusercontent.com/25740108/197346818-122e6d1b-5da8-4bc2-9b08-4e75fd1c839b.png)

**Comment by IM-IgniteDEV** [comment]
![image](https://user-images.githubusercontent.com/31209154/197346830-d7efcac2-6607-426e-984e-1fa4765888b4.png)

**Comment by joshuasing** [comment]
I think I found the problem, it looks to be caused by this line:
https://github.com/dzikoysk/reposilite/blob/main/reposilite-frontend/src/components/card/XmlTag.vue#L29

which was introduced in #1003
