### ISSUE TITLE
Add Code of Conduct

### ISSUE THREAD

**Issue by joshuasing** [dzikoysk/reposilite#1631]
### Request details

[GitHub recommends projects adopt a code of conduct to define community standards, signal a welcoming and inclusive project, and outline procedures for handling abuse.](https://docs.github.com/en/communities/setting-up-your-project-for-healthy-contributions/adding-a-code-of-conduct-to-your-project)

The most popular Code of Conduct for Open Source projects appears to be [Contributor Covenant Code of Conduct](https://www.contributor-covenant.org/).

A Code of Conduct is not required for a project, in anyway, however Code of Conducts generally signal that the project is an inclusive environment where anyone is free to contribute, and outlines procedures for addressing problems between members of the project's community.

**Comment by dzikoysk** [comment]
I'm not sure if I see any value of such file to be honest, it's yet another resource with a lot of words to maintain that does not translate to any real value for project and community. We didn't have any incidents where such thing could be helpful, it might be related to the relatively small scale of this project. I prefer to shape community by actions and I think that the natural way of just being friendly to each other is pretty enough for us.

**Comment by joshuasing** [comment]
Fair enough and completely understandable.

Thanks.
