### ISSUE TITLE
Run docker image as a given user (uid/gid)

### ISSUE THREAD

**Issue by hereisderek** [dzikoysk/reposilite#1634]
### Request details

is there a way to run the docker as a specific user (with given uid/gid) instead of the hard coded 999:999 ?  

one of the common practices is to pass in as PUID and PGID environment variable

Thanks

**Comment by dzikoysk** [comment]
Not really, those two are hardcoded in Docker image file: 

* https://github.com/dzikoysk/reposilite/blob/864d2d013334846e6f795bdf5437f67a5bbe1ac3/Dockerfile#L38

As far as I remember quite a lot of popular projects use this 999:999 combination, why would you want to change that?

**Comment by dzikoysk** [comment]
I've used recommended by you variable names - `PUID` & `PGID`. The script will create user & group at the start of the container.
