### ISSUE TITLE
Support Gitlab/Github repos as mirrored repository

### ISSUE THREAD

**Issue by stephanpelikan** [dzikoysk/reposilite#1636]
### Request details

Gitlab uses this Maven configuration for authentication:
```
    <server>
      <id>my-gitlab</id>
      <configuration>
        <httpHeaders>
          <property>
            <name>Private-Token</name>
            <value>XXXXXXXXXXXX</value>
          </property>
        </httpHeaders>
      </configuration>
    </server>
```
In our setup we would need this kind of configuration: Providing a http-header as an alternative to username/password. This would fit to Gitlab's "Private-Token" as well as to repositories using "Authorization" header like Github:

```
      <configuration>
        <httpHeaders>
          <property>
            <name>Authorization</name>
            <value>Bearer XXXXXXXXXXXXXXXXXXXX</value>
          </property>
        </httpHeaders>
      </configuration>
```

**Comment by dzikoysk** [comment]
You should be able now to define custom authentication methods as follows:

![obraz](https://user-images.githubusercontent.com/4235722/200884004-5cef6327-e6f9-4ea9-961c-73438c461492.png)

It'll be available in the next release, but you can also test this using our snapshots builds for Docker/standalone JAR when CI will finish publication tasks.

**Comment by stephanpelikan** [comment]
Whow! You're faster than light 👍 . I will test it for sure, thanks!
