### ISSUE TITLE
Using Reposilite as a mirror for central breaks using some plugins from the CLI

### ISSUE THREAD

**Issue by siepkes** [dzikoysk/reposilite#1641]
### What happened?

First of all thanks for all the great work on Reposilite!

When using Reposilite as a mirror for Maven central running `mvn -U versions:set -DnewVersion=5.5.1` from the command line will error out with:

```
[ERROR] No plugin found for prefix 'versions' in the current project and in the plugin groups [org.apache.maven.plugins, org.codehaus.mojo] available from the repositories [local (/home/siepkes/.m2/repository), virtual (https://reposilite.foo.nl/virtual/)] -> [Help 1]
[ERROR] 

```

Relevant part of  `~/.m2/settings.xml`:

```
<?xml version="1.0"?>
<settings>
    <mirrors>
        <mirror>
            <id>virtual</id>
            <name>Reposilite Repository Manager</name>
            <url>https://reposilite.foo.nl/virtual/</url>
            <mirrorOf>*</mirrorOf>
        </mirror>
    </mirrors>
```

The `virtual` repository in Reposilite is configured as a mirror for `https://repo1.maven.org/maven2/`. Local storage is enabled for the mirror.

Opening `https://reposilite.foo.nl/virtual/org/codehaus/mojo/maven-metadata.xml` shows this:

```
<metadata modelVersion="1.1.0">
  <plugins>
    <plugin>
      <name>Exec Maven Plugin</name>
      <prefix>exec</prefix>
       <artifactId>exec-maven-plugin</artifactId>
    </plugin>
  </plugins>
</metadata>
```

As can be seen the entry for the `versions` plugin is missing. When opening the `maven-metadata.xml` on central it looks like this: https://repo1.maven.org/maven2/org/codehaus/mojo/maven-metadata.xml . I believe because Reposilite's `maven-metadata.xml`  does not have the `versions` plugin entry the command with Maven from the CLI does not work.

### Reposilite version

3.x

**Comment by dzikoysk** [comment]
I think it works fine:

* https://maven.reposilite.com/maven-central/org/codehaus/mojo/maven-metadata.xml
* https://repo1.maven.org/maven2/org/codehaus/mojo/maven-metadata.xml

Could you delete your cached `maven-metadata.xml` file and request it once again, so we can be sure it's an issue we can try to reproduce?

**Comment by siepkes** [comment]
At first I got confused because there didn't seem to be a `maven-metadata.xml` file:

```
root@reposilite-1:/var/lib/reposilite/repositories/virtual/org/codehaus/mojo
# ls -las
total 28
9 drwxr-xr-x 7 reposilite reposilite 7 Nov 29 16:23 .
9 drwxr-xr-x 9 reposilite reposilite 9 Nov 29 16:11 ..
1 drwxr-xr-x 7 reposilite reposilite 7 Nov 29 11:21 animal-sniffer-annotations
1 drwxr-xr-x 7 reposilite reposilite 7 Nov 29 13:45 animal-sniffer-parent
1 drwxr-xr-x 4 reposilite reposilite 4 Nov 29 15:17 exec-maven-plugin
9 drwxr-xr-x 6 reposilite reposilite 7 Nov 29 16:22 mojo-parent
1 drwxr-xr-x 3 reposilite reposilite 4 Nov 29 16:23 versions-maven-plugin
```

By running `grep "Exec Maven Plugin" -r /var/lib/reposilite/repositories/` ("Exec Maven Plugin" being the only thing which was shown in the Reposilite `maven-metadata.xml` ) I was able to determine it was picking up an old version from a different mirror repo. After deleting that file it worked!

Thanks for the help and putting me on the right track!

**Comment by dzikoysk** [comment]
Nice, I'm glad you've found out the issue! :)
