### ISSUE TITLE
Please support a s3 provider configuration option for the s3 client pathStyleAccessEnabled

### ISSUE THREAD

**Issue by cameronbraid** [dzikoysk/reposilite#1682]
### Request details

This is required in order to use some minio servers

**Comment by dzikoysk** [comment]
Path style access has been deprecated:

* https://stackoverflow.com/a/61602647/3426515
* https://aws.amazon.com/blogs/aws/amazon-s3-path-deprecation-plan-the-rest-of-the-story/

So I'll implement it through `reposilite.s3.pathStyleAccessEnabled` property for now:

https://github.com/dzikoysk/reposilite/blob/fee8441374d9a31ec7de2ab23ec6d18e708ea6e3/reposilite-backend/src/main/kotlin/com/reposilite/storage/s3/S3StorageProviderFactory.kt#L18-L24

Running your instance with JVM flag `-Dreposilite.s3.pathStyleAccessEnabled=true` should solve your issue.

**Comment by bh-tt** [comment]
Thank you for this fix, just ran into this issue while replacing our old nexus sonatype instance with reposilite. I'd like to note that while path style access has been deprecated in AWS, other implementations (like Ceph or Minio) still use it by default. I recommend leaving this option in even if AWS s3 removes the feature.
