### ISSUE TITLE
Mirrored repositories section does not provide time unit which used in 'Connect/Read Timeout' setting

### ISSUE THREAD

**Issue by MairwunNx** [dzikoysk/reposilite#1695]
### Mirrored repositories section does not provide time unit which used in 'Connect/Read Timeout' setting

This does little bit confuse the user much when setting up dependency mirroring, since the exact time measurement system is not specified (milliseconds or seconds).

![image](https://user-images.githubusercontent.com/39625750/213882549-c3f06224-5d88-474f-88c2-dc17daa9e6c0.png)

**Comment by dzikoysk** [comment]
Thanks for the report, indeed that's the fair point. It's in seconds :)

**Comment by dzikoysk** [comment]
It'll be mentioned in the description in the next release.
