### ISSUE TITLE
Run reposilite completely configured from file with write access to repositories only

### ISSUE THREAD

**Issue by enp** [dzikoysk/reposilite#1699]
### Request details

Is it possible to run reposilite completely configured from file with write access to repositories only?

Tokens looks like main problem because it looks impossible to store them in cdn/json - so tokens should be created/imported every time on start reposilite, right?

Another minor problems are:
- Two configuration files (cdn and json both) - why not use only one file?
- Static http folder - why not load static files as resources from jar?
- Logging - why not log to stdout/stderr only?

Btw, It will be more simple and idiomatically to run reposilite in kubernetes if problems above will be fixed

**Comment by dzikoysk** [comment]
You can define token through `--token name:secret` flag to create management token, but that's basically just it. Reposilite keeps tokens stored in database, so you can probably also mount preconfigured db.

1. There's just one configuration file, CDN with human-friendly format to configure the instance. Shared properties are by default stored in database as well and that's the main source of truth, the possibility to dump database state to json is pretty much a small workaround for people that want to use stateless Reposilite instance to e.g. proxy traffic.
2. Static files are loaded by default from JAR, the `static` directory is for users that would like to add some extra static content to serve
3. Reposilite logs to stout & file, stout is by default slightly cleaner to not spam with mostly unnecessary debug log entires, especially that you can execute commands in cli. Log files contain all logs, so they're useful in case of failures/detailed analysis of what's going on.
