### ISSUE TITLE
Tokens are logged in clear text

### ISSUE THREAD

**Issue by jcklie** [dzikoysk/reposilite#1701]
### What happened?

When creating a new access token, they are logged in clear text and even saved to latest.log when creating them via the web ui. It would be maybe good to save them via a different channel.

### Reposilite version

3.x

### Relevant log output

```shell
com.reposilite.journalist.slf4j.Slf4jLogger 2023-01-24 09:22:43.392 INFO | Generated new access token for X with 'm' permissions. Secret:
com.reposilite.journalist.slf4j.Slf4jLogger 2023-01-24 09:22:43.393 INFO | $2a$12$ee/n.7fe2MyOtroskLd1JuP3RajW6/Bbd6hdXbTRvmXwwZ.dZp2DC
```

**Comment by dzikoysk** [comment]
Because I don't have plans to remove this for now & in general we want to replace it with standalone implementation (UI), I think I can close this issue :)

**Comment by marco-brandizi** [comment]
I'd like to reopen this ticket because to me, this is a serious security issue. Secrets should never be stored in clear text, in the logs or anywhere else. The common practice for the logs is saving something like `secret=***`, rather than the original secret. Currently, I edit the log manually when I add a new token, and that's rather uncomfortable.

**Comment by dzikoysk** [comment]
Sure, but this is not regular log - you're directly using a CLI and this is somehow a side effect of it. As a workaround, we'd need to generate the token in some sort of a local file, but then it'd be a nightmare for most of the people running it in some sort of a container. So either we can add it as a separate flag to the command, or you can use REST API to generate your token with curl: 

* https://maven.reposilite.com/swagger#/Tokens/put_api_tokens__name_

**Comment by marco-brandizi** [comment]
I have uset `token-generate` on the console tab of the web UI, and I'd be fine with seeing the secret on the UI's log. What is problematic is it's in `latest.log` too.
