### ISSUE TITLE
Unable to see any private repositories while being able to publish artifacts

### ISSUE THREAD

**Issue by DelfikPro** [dzikoysk/reposilite#171]
I want my reposilite repo to require credentials when surfing and downloading artifacts, and the docs page provides a little of no info about how to achieve this: [https://reposilite.com/docs/file-viewer](https://reposilite.com/docs/file-viewer)

**Comment by DelfikPro** [comment]
Figured out the way to hide repos by adding `.` in front of its name.
Seems to work fine, except the webviewer shows nothing
![image](https://user-images.githubusercontent.com/33707322/88757252-460baf00-d16e-11ea-8853-f4620c8bfa45.png)

**Comment by dzikoysk** [comment]
Could you check the console output using dev tools? Looks like 2.7.x versions are affected by some kind of auth bug in some cases.

**Comment by dzikoysk** [comment]
#172

**Comment by dzikoysk** [comment]
Does this error occur on 2.7.3?

**Comment by DelfikPro** [comment]
Navigation and download in dashboard now works fine, but gradle doesn't:

Repo is configured with the same credentials working in dashboard
```
maven {
    url "http://N.N.N.N/releases"
    credentials {
        username = reposiliteAlias
        password = reposiliteToken
    }
```

Again, deployment works properly, downloading doesn't:
```> Could not GET 'http://N.N.N.N/releases/clepto/clepto-java/0.3.2/clepto-java-0.3.2.pom'. Received status code 401 from server: Unauthorized```

Here are the complete logs of both downloading and uploading:
[reposilite.log](https://github.com/dzikoysk/reposilite/files/4998202/reposilite.txt)

Here is the config:
[config.txt](https://github.com/dzikoysk/reposilite/files/4998204/config.txt)

**Comment by dzikoysk** [comment]
Do you use some kinf of CDN like Cloudflare?

**Comment by NoneTirex** [comment]
@DelfikPro try to do, like that:
```
maven {
    url "http://N.N.N.N/releases"
    credentials {
        username = reposiliteAlias
        password = reposiliteToken
    }
    authentication {
        basic(BasicAuthentication)
    }
}
```

**Comment by DelfikPro** [comment]
Thank you, @NoneTirex, this solved the issue.
