### ISSUE TITLE
Give a friendly error when building dockerfile and git tags aren't available

### ISSUE THREAD

**Issue by bergerkiller** [dzikoysk/reposilite#1725]
### Request details

By default when you fork reposilite on Github, it only checks out the "main" branch. Without really making it obvious however, this also omits all the git tags that the Dockerfile uses to label the final jar artifact.

The result is that after running gradle without these tags present, it outputs the following jar files:
```
#10 [build 6/6] RUN   ls /home/reposilite-build/reposilite-backend/build/libs/
#10 0.341 reposilite-0.1.0-SNAPSHOT.jar
#10 0.341 reposilite-backend-0.1.0-SNAPSHOT.jar
```

As it only copies these jars in the last build step:
`COPY --from=build /home/reposilite-build/reposilite-backend/build/libs/reposilite-3*.jar reposilite.jar`

This results in a final Docker image which lacks any jar files, and fails to start up:
```
Adding group `reposilite' (GID 999) ...
Done.
Adding system user `reposilite' (UID 999) ...
Adding new user `reposilite' (UID 999) with group `reposilite' ...
Creating home directory `/home/reposilite' ...
Error: Unable to access jarfile reposilite.jar
```

It was not immediately obvious what was wrong until I added some debugging ls lines to the dockerfile to figure all this out.

As I imagine other people forking the project might run into this same issue, it would be a good idea to add an error check in the Dockerfile with a helpful message explaining that no tags are available/should be available. Bit unfortunate that the COPY can fail silently like that.

**Comment by dzikoysk** [comment]
To be fair I didn't even know as I don't use Docker to launch Reposilite during development, the Dockerfile is for CI to build final image 🤔 If you have some kind of a solution that covers this case, feel free to submit a PR :)

**Comment by bergerkiller** [comment]
I was in more a deployment phase when I ran into that /latest bug which is why I went straight for the Dockerfile, yeah. I don't really know how that mechanism with git tags works, so can't really contribute there sadly.

It's not a huge deal, and perhaps this issue ticket being around will clue people in :)

**Comment by dzikoysk** [comment]
I think something like that might be enough 🤔 It'll just enforce everyone to fetch tags from the main reop before trying to launch/build project.
