### ISSUE TITLE
"403 - You must be the token owner or a manager to access this." When trying to browse repo with token that has access.

### ISSUE THREAD

**Issue by imorph** [dzikoysk/reposilite#1728]
### What happened?

Version: 3.3.1 (and relevant for at least to 3.2.5)

What i want:
* have single "admin/manager" user with access to console/settings
* have many read-only/read-write users with access to their repos of interest (both from gradle/maven and web-UI)

What i see: the only possible solution for user to work with private repo is to be manager. Am i doing something wrong?

Steps to reproduce:

Create private repo (`/test`):
![repo](https://user-images.githubusercontent.com/6258922/217734580-ed930b57-b4ef-4ab5-92cb-e850d831ce06.png)

Generate (non-manager) token:
`token-generate test`

Added route `/test` to token `test`:
`route-add test /test w`

Token with manager access can see repo and contents:
![contents](https://user-images.githubusercontent.com/6258922/217735399-23f145b6-40cf-4028-a682-be0a8613e2c1.png)

`test` token can see repo itself:
![repo as test](https://user-images.githubusercontent.com/6258922/217735695-d1840871-ebd1-4325-a639-a484b5d98b56.png)

but can not access it content:
![403](https://user-images.githubusercontent.com/6258922/217735838-58d53e44-38fe-4dae-8674-3920eaf1989f.png)

Also API works same way:
response from api/tokens/test: `{"identifier":{"type":"PERSISTENT","value":6},"name":"test","createdAt":[2023,2,9],"description":""}`
response from /api/maven/details: `{"name":"/","files":[{"name":"test","type":"DIRECTORY"}],"type":"DIRECTORY"}`
response from /api/maven/details/test: `{"status":403,"message":"You must be the token owner or a manager to access this."}`
resp from: /api/tokens/admin: `{"status":403,"message":"You must be the token owner or a manager to access this."}`

i dont see 403 as valid response anywhere in API: https://maven.reposilite.com/swagger nor "must be the token owner or a manager to access this" phrase (except path https://maven.reposilite.com/swagger#/Tokens/get_api_tokens__name_, which by the way doesnt have documented resp codes)

### Reposilite version

3.x

**Comment by dzikoysk** [comment]
You should also add `r` permission to allow reading content from repository. It'd be:

```
route-add test /test rw
```
