### ISSUE TITLE
Fail fast with --shared-configuration

### ISSUE THREAD

**Issue by bh-tt** [dzikoysk/reposilite#1733]
### Request details

When reposilite is given the --shared-configuration setting and something goes wrong (file does not exist, not valid json, not valid config) reposilite simply starts with the default settings. I think it would be preferable to simply crash in this case, quickly informing the administrator something is wrong instead of running with the defaults (which you do not want, if you give a shared configuration to reposilite).

**Comment by bh-tt** [comment]
Thanks for the quick fix.

**Comment by dzikoysk** [comment]
Sure, I also think it'll be healthier for users with manually mounted settings to fail immediately. I've made it a default behavior, but there's still a flag to bypass it - it might be helpful for people with db-based shared config as they wouldn't be able to start their instances in case of corrupted config.
