### ISSUE TITLE
Move from Node 14.x to 18.x with NPM 9.5.0+

### ISSUE THREAD

**Issue by PolarianDev** [dzikoysk/reposilite#1740]
### Request details

What NPM version do you use for reposilite frontend, because the AUR package needs to reflect this version, as currently it doesnt and npm shouts at you every time you build the package that the npm lock is out of date and updates it.

Would it be better to update to the latest npm version, and thus update the upstream version of the lockfile?

**Comment by dzikoysk** [comment]
The minimal required version for `reposilite-frontend` module is Node 14.x+,  there were some issues with newer versions in the past, so we're using this to build app in Docker:

* https://github.com/dzikoysk/reposilite/blob/main/Dockerfile#L6

I guess we could revisit this requirement and see if we can move to the latest LTS.

**Comment by PolarianDev** [comment]
Oh damn, we are using 8.19 to build the packages, I dont know which one you are using... but its outdated when I build reposilite

**Comment by dzikoysk** [comment]
Idk which NPM version comes with Node 14.x on CI, but locally I use Node 14.x + NPM `9.5.0` and it works properly.

**Comment by PolarianDev** [comment]
the issue is mainly because Arch Linux is rolling release, so we use latest upstream and not LTS (we could use LTS but node and NPM is split).
