### ISSUE TITLE
Support custom SSL port configuration by `enforceSsl`

### ISSUE THREAD

**Issue by Mitch64** [dzikoysk/reposilite#1751]
### What happened?

I want to access Reposilite via https only. So I configure **enforceSsl: true** in configuration.cdn, with **port: 8080**, and **sslPort: 8083**. But this leads (at least in my case) to the following problem: When I try to access **http**://my.server:**8080/**#/ in the browser, I get a redirection (301) with _Location: **https**://my.server:**8080**/#/_ in the response headers. This leads to a browser error because _**https**://my.server:**8080/**#/_ of course is not a valid URL in my case. I would have expected _Location: **https**://my.server:**8083**/#/_ in the response headers, with **sslPort** used for the redirection instead of **port**. Or am I missing something here?

### Reposilite version

3.3.2

### Relevant log output

N/A

**Comment by Mitch64** [comment]
Wow, this was a quick answer. Thank you.

**Comment by Mitch64** [comment]
I just installed release 3.4.0 and the SSL redirection works perfectly now. Thank you.

**Comment by dzikoysk** [comment]
Nice! :)
