### ISSUE TITLE
New repository link after deleting a repository

### ISSUE THREAD

**Issue by BitBlit88** [dzikoysk/reposilite#1754]
### What happened?

After deleting a repository a new repository at the overview page appears, it looks like a GUID:

releases
snapshots
private
9905ca0c-af29-423a-a6c8-189063009163

The "9905ca0c-af29-423a-a6c8-189063009163" points again to the "release, snapshot and private repository".
How can I delete/hide this GUID?

### Reposilite version

3.x

**Comment by dzikoysk** [comment]
If repository does not have a name, it's assigned to the random UUID generated at startup. To get rid of it, you should remove its setup in the dashboard - this repo is probably represented by the tab with `<New>` title, so just simply use `X` on the right side to delete it & update config.

![obraz](https://user-images.githubusercontent.com/4235722/226043327-b0b4e709-ae1a-4f41-ab75-c7e473b20d28.png)

**Comment by BitBlit88** [comment]
Thank you. I didn't noticed the "New" tab. This solved the issue.
