### ISSUE TITLE
Ability to hide repository details on main landing page when hosting multiple repositories

### ISSUE THREAD

**Issue by devopology** [dzikoysk/reposilite#1757]
### Request details

When hosting multiple repositories, the main landing page shows an invalid description. For these scenarios, the repository details isn't relevant/invalid.

```
<url>https://repository.address.cx/{repository}</url>
```

![image](https://user-images.githubusercontent.com/122582561/227579103-6b134372-d85e-43cf-884d-ff1d574a6ae4.png)

**Comment by dzikoysk** [comment]
The root directory does not point to any repository, so `{repository}` informs users that they should specify repository name here. We're using placeholder format, because developers recognize it as a placeholder that should be filled up with a value.

**Comment by dzikoysk** [comment]
I've changed `{repository}` to `<repository>`, it looks slightly better now imo (#1759). There's also a request that is kinda associated to this issue, as it makes this view fully configurable:

* #1782
