### ISSUE TITLE
Image requires to be run as root and does not support random uids

### ISSUE THREAD

**Issue by bo0ts** [dzikoysk/reposilite#1762]
### What happened?

The docker image requires to be run as root since it adds a new user and group. This makes it hard to run the image as-is on OpenShift/OKD or in constrained environments.

Supporting random UUIDs would be a great feature.

### Reposilite version

3.x

**Comment by dzikoysk** [comment]
I don't have much knowledge about OpenShift/OKD, but current setup makes sure that Reposilite is not launched as root user inside the container (the default behavior of Docker that is our current target). Do you have any recommendations about possible improvements to the existing scripts?

* https://github.com/dzikoysk/reposilite/blob/main/Dockerfile
* https://github.com/dzikoysk/reposilite/blob/main/entrypoint.sh

Maybe we should add some kind of new env variable that would launch Reposilite directly, without custom user 🤔

**Comment by bo0ts** [comment]
As far as I can see the image currently needs to be started as root to perform `adduser` and `addgroup`. It only switches into the user afterwards. Usually `adduser`/`addgroup`/`chown` and the switch to the new user are done during the image build.

To make the image run with arbitrary user ids the OpenShift doc (https://docs.openshift.com/container-platform/4.9/openshift_images/create-images.html#images-create-guide-openshift_create-images) says 

> For an image to support running as an arbitrary user, directories and files that are written to by processes in the image must be owned by the root group and be read/writable by that group. Files to be executed must also have group execute permissions.

So adding `chgrp -R 0 /app/ && chmod -R g+rwX /app/ && chgrp -R 0 /var/log/reposilite && chmod -R g+rwX /var/log/reposilite` should do the trick.

Unfortunately I haven't been able to build the image locally with podman on an M1 MacBook yet, so I cannot test this right now.

**Comment by dzikoysk** [comment]
I'd like to keep just one image that covers all we need. My suggestion was to do sth like:

```bash
#!/bin/bash

REPOSILITE_ARGS=$REPOSILITE_OPTS
case "$REPOSILITE_OPTS" in
  *"--working-directory"*) ;;
  *"-wd"*                ) ;;
  *                      ) REPOSILITE_ARGS="--working-directory=/app/data $REPOSILITE_ARGS";;
esac

# // if (REPOSILITE_WITHOUT_RUNUSER):
#   java -jar [...]
# // else:
GROUP_ID="${PGID:-999}"
addgroup --gid $GROUP_ID reposilite

USER_ID="${PUID:-999}"
adduser --system -uid $USER_ID --ingroup reposilite --shell /bin/sh reposilite

chown -R reposilite:reposilite /app
chown -R reposilite:reposilite /var/log/reposilite

# shellcheck disable=SC2093
# shellcheck disable=SC2086
exec runuser -u reposilite -- \
  java \
     -Dtinylog.writerFile.file="/var/log/reposilite/log_{date}.txt" \
     -Dtinylog.writerFile.latest=/var/log/reposilite/latest.log \
     $JAVA_OPTS \
     -jar reposilite.jar \
     $REPOSILITE_ARGS
```

So then, if you'd use define env variable `REPOSILITE_WITHOUT_RUNUSER=true`, then it'd just directly launch Reposilite as it'd be without `entrypoint.sh`. I'm not quite sure what's `easy logging configuration for JSON logging` tho.

**Comment by sschnabe** [comment]
I'would prefer a check for current uid: if 0 add non-root user, do nothing otherwise.

Regarding logging: i need not log file, i want the application to log in JSON format to console.
