### ISSUE TITLE
Filter out Snapshots in Badge API

### ISSUE THREAD

**Issue by impleri** [dzikoysk/reposilite#1781]
### Request details

Would be nice to be able to report the latest stable version for a package. Currently, the query seems to prefer snapshots over releases, so the badge isn't always accurate.

**Comment by dzikoysk** [comment]
Reposilite does not check snapshots for badges, it pulls the latest version from the current metadata file. The behavior you're describing could happen if you'd mix releases with snapshots in the same repository, but that's kinda an issue caused by non standard usage of Maven repo 🤔

**Comment by dzikoysk** [comment]
I've added a new filter, so sth like that should work for you:

```
/api/badge/latest/releases/com/reposilite?color=40c14a&name=Reposilite&prefix=v&filter=none:SNAPSHOT
```
