### ISSUE TITLE
Custom repository write permission does not imply read

### ISSUE THREAD

**Issue by robsl2314** [dzikoysk/reposilite#1818]
### What happened?

As we are using Reposilite for several projects we created multiple repositories in private mode with several users with their specific route permissions.

When adding only a write permission `route-add <user> <path> w` it is possible to upload the artifact with mvn BUT STILL an error occurs when mvn trys to check if the upload was successful as the user has no read permission.

Furthermore it is not possible to bind a 'r' and 'w' to the same route - only a janky configuration e.g. following would resolve our needs:
```
route-add user /repo/ r
route-add user /repo/com/ w
route-add user /repo/net/ w
route-add user /repo/org/ w
```

A write permission should include read permissions imo

### Reposilite version

3.x

**Comment by dzikoysk** [comment]
You can assign multiple permissions to the same route, e.g. `route-add user /repo/com/ rw`.

**Comment by robsl2314** [comment]
Ok - silly me. 
Didn't thought about combining those permissions. Maybe it would be a consideration to add this information to the official documentation? I digged several hours and only came up with my stupid workaround.

https://reposilite.com/guide/routes

Thanks!

**Comment by dzikoysk** [comment]
Sure, would you like to update the guide? :)

**Comment by robsl2314** [comment]
Sure ;)
