### ISSUE TITLE
Mirror will not work if there is a slash at the end of source URL

### ISSUE THREAD

**Issue by lawrenceching** [dzikoysk/reposilite#1820]
### What happened?

Hi 

I found that if I use "https://repo1.maven.org/maven2/" (with the "/" at the end), I can't fetch any depdency from reposilite.

It's hard to be aware of this limitation, and took me so long the debug.

I think it's good to emphasize what the URL should look like in web UI.
Or even better, reposilite can undertsand the URL with or without "/" at the end.

### Reposilite version

3.x

**Comment by dzikoysk** [comment]
Yup, we should definitely cover that case. Would you like to submit PR with a fix? :)
