### ISSUE TITLE
Deprecated method calls in Routing.kt

### ISSUE THREAD

**Issue by PolarianDev** [dzikoysk/reposilite#1824]
Hello,

While building the AUR package in a clean chroot I found the following:

```
> Task :reposilite-backend:compileKotlin
w: file:///home/build/reposilite/src/reposilite-3.4.4/reposilite-backend/src/main/kotlin/com/reposilite/web/api/Routing.kt:20:35 'RouteMethod' is deprecated. Use io.javalin.community.routing.Route instead
w: file:///home/build/reposilite/src/reposilite-3.4.4/reposilite-backend/src/main/kotlin/com/reposilite/web/api/Routing.kt:59:25 'RouteMethod' is deprecated. Use io.javalin.community.routing.Route instead
```

Just a heads up, I will let you investigate it :)

Polarian

**Comment by dzikoysk** [comment]
It's intentional, as it's deprecated on our side:

* https://github.com/dzikoysk/reposilite/blob/main/reposilite-backend/src/main/kotlin/com/reposilite/web/routing/RouteMethod.kt

It'll be removed in Reposilite 4.x due to backwards compatibility with plugin API.

**Comment by PolarianDev** [comment]
Ah ok, sorry for the noise :)

**Comment by dzikoysk** [comment]
Sure, thanks for your vigilance :)
