### ISSUE TITLE
Adding a renaming feature to mirrored repository

### ISSUE THREAD

**Issue by milkyway0308** [dzikoysk/reposilite#1847]
### Request details

Currently, Reposilite supports a "Mirrored Repository" that enables proxying and caching of libraries from the original source.

However, until Reposilite 3.4.x, it does not support custom naming of repositories, which results in a very long mirrored repository tab.

Therefore, I suggest adding some renaming features to the Mirrored Repository tab.

<br>

Here's some example screenshot of Mirrored Repository from Reposilite 3.4.
![image](https://github.com/dzikoysk/reposilite/assets/15888565/96d58909-2130-4fcb-aef4-63a70aa8d121)

**Comment by dzikoysk** [comment]
It'll be displayed as `Hub.Spigotmc.Org` & `Repo.Papermc.Io` now. Do you think it is good enough?

**Comment by milkyway0308** [comment]
Nice work! I think it can cause confusion with same url but different repository, but still looks better than before.

Looks good to me.
