### ISSUE TITLE
Support SSL connection in LDAP integration

### ISSUE THREAD

**Issue by dzikoysk** [dzikoysk/reposilite#1871]
### What happened?

Reported on Discord: `ldap://` part is hardcoded

### Reposilite version

3.x

**Comment by jsaalfeld** [comment]
I reported the issue.

https://github.com/dzikoysk/reposilite/blob/d286125abc9aac7fa7a21ca419767d84454cae80/reposilite-backend/src/main/kotlin/com/reposilite/auth/LdapAuthenticator.kt#L104 - There is the Hardcoded `ldap://`-String. It should be either not a fixed prefix at all, or a switch between `ldap` or `ldaps`.

I will provide documentation on how to inject a certificate for usage with ldaps (or other internal connections) for the documentation.
