### ISSUE TITLE
Maven Central Mirror : Default Restricted File Types List Prevents Some Artifacts from being used in Gradle

### ISSUE THREAD

**Issue by codesplode** [dzikoysk/reposilite#1875]
### What happened?

I've been working for a few days to resolve an issue that began when updating reposilite and with your knowledge here I believe it will likely be an easy resolution.

About a week ago, we began experiencing issues with certain library dependencies getting downloaded from our reposilite repository that mirrors maven central. The dependencies would get downloaded fine from the gradle log, but intellij and gradle would fail to build and show errors on any import for classes in the dependency. The most obvious dependencies were:

```kotlin
// All ktor versions 2.1.0 through 2.3.2 failed (we did not try any older, but all failures were consistent).
implementation("io.ktor:ktor-client-core:$ktorVersion")
implementation("io.ktor:ktor-client-cio:$ktorVersion")
implementation("io.ktor:ktor-client-content-negotiation:$ktorVersion")
implementation("io.ktor:ktor-serialization-kotlinx-json:$ktorVersion")
```

We first narrowed it down by removing all other repositories and finally figured out that swapping the mirror repo out for maven central directly made the difference. This made us check the Reposilite configuration for the repo.

After a lot more experimentation we found that the deciding factor was the "allowed extensions" configurations. We had never modified this from the defaults, so here is what it was before we modified it:
![image](https://github.com/dzikoysk/reposilite/assets/823828/92147df8-7274-4da9-9f35-52489c1ab5b6)

We removed all of the extensions to "Allow all" as the hint suggests and the dependencies immediately started working correctly.
![image](https://github.com/dzikoysk/reposilite/assets/823828/67705c27-bf3f-4cd9-8f56-2b66398bd72e)

Please let me know if there is anything else we can test to help resolve this issue.

### Reposilite version

3.4.5

**Comment by dzikoysk** [comment]
You should be able to see all request to your Reposilite instance in CLI in debug mode (command: `level debug`) or in the latest.log file. Each error response should also contain an error message, it might be helpful to investigate which extensions were dropped. 

I've checked out some of the files of these Ktor libs:
* https://repo1.maven.org/maven2/io/ktor/ktor-client-cio-jvm/2.3.2/
* https://repo1.maven.org/maven2/io/ktor/ktor-client-core/2.3.2/
* https://repo1.maven.org/maven2/io/ktor/ktor-client-content-negotiation/2.3.2/

It looks like our default cfg misses `.module` extension - it might be the issue. I also see they have some extra files called `kotlin-tooling-metadata.json`, but I don't think it's the cause of this problem.

**Comment by codesplode** [comment]
I'll add all the extensions back and test it today sometime. I'll also try out debug mode on reposilite to find any others if there is still an issue. Kotlin has a lot of multiplatform related capabilities which his opening the door for more types of files to be stored for multiplatform gradle builds, etc. and ktor does support many platfroms so I could absolutely see this causing some difference from a typical java project.

I'll also see if I can get a list of the file types output for multiplatform kotlin release artifacts as well.

**Comment by dzikoysk** [comment]
Sure, let me know if you'll find out more extensions that we should reconsider as defaults. To be fair, I didn't try to publish KMP projects to Reposilite yet.

**Comment by codesplode** [comment]
We are trying that out for you and happy to do so.

**Comment by dzikoysk** [comment]
It seems to be resolved ;)
