### ISSUE TITLE
Wrong statement re Maven in  reposilite/reposilite-site/data/guides/integrations/github.md

### ISSUE THREAD

**Issue by gerib** [dzikoysk/reposilite#1880]
In [reposilite](https://github.com/dzikoysk/reposilite/tree/main)/[reposilite-site](https://github.com/dzikoysk/reposilite/tree/main/reposilite-site)/[data](https://github.com/dzikoysk/reposilite/tree/main/reposilite-site/data)/[guides](https://github.com/dzikoysk/reposilite/tree/main/reposilite-site/data/guides)/[integrations](https://github.com/dzikoysk/reposilite/tree/main/reposilite-site/data/guides/integrations)/[github.md](https://github.com/dzikoysk/reposilite/blob/main/reposilite-site/data/guides/integrations/github.md) is stated:

> Because Maven does not support environment variables, [...]

I'm using the following in my repo(s) on GitLab (if that may be mentioned here on GH (:

`maven_settings_ci.xml`
```
<settings>

  ...

  <servers>
    <server>
      <id>gitlab-maven</id>
      <configuration>
        <httpHeaders>
          <property>
            <name>Deploy-Token</name>
            <value>${env.GITLAB_MAVEN_DEPLOY_TOKEN}</value>  <!-- Here it is! -->
          </property>
        </httpHeaders>
      </configuration>
    </server>
  </servers>

  ...

</settings>
```

`gitlab-ci.yml`
```
...

variables:
  MAVEN_ARGS: ... --settings ${CI_PROJECT_DIR}/maven_settings_ci.xml ...

...
```
I guess something similar can be done in a GH Action as easily.

----

References:

- [_Use GitLab_ → _Maven packages in the Package Registry_ → _Edit the client configuration_](https://docs.gitlab.com/ee/user/packages/maven_repository/#edit-the-client-configuration)

- [_Maven: The Complete Reference_ → _3.3.2. Property References_](https://books.sonatype.com/mvnref-book/reference/pom-relationships-sect-pom-syntax.html#pom-relationships-sect-property-refs)
  > **env**
  > The `env` variable exposes environment variables exposed by your operating system or shell. For example, a reference to _${env.PATH}_ in a Maven POM would be replaced by the _${PATH}_ environment variable (or `%PATH%` in Windows).

- [Configuring Apache Maven](https://maven.apache.org/configure.html#maven_args-environment-variable)
  > **MAVEN_ARGS** environment variable:
  > Starting with Maven 3.9.0, this variable contains arguments passed to Maven before CLI arguments.

- [Maven CLI Options Reference](https://maven.apache.org/ref/3.6.3/maven-embedder/cli.html)
  > | `-s`,`--settings` | Alternate path for the user settings file |

- _Use GitLab_ →
  - → [_Define a CI/CD variable in the `.gitlab-ci.yml` file_](https://docs.gitlab.com/ee/ci/variables/#define-a-cicd-variable-in-the-gitlab-ciyml-file)
  - → [_Predefined variables reference_](https://docs.gitlab.com/ee/ci/variables/predefined_variables.html)

### Reposilite version

3.x

**Comment by dzikoysk** [comment]
By `does not support environment variables` I've meant that you cannot pass these properties through standard env variables/arg parameters to `mvn` process - either way, you have to define settings.xml and link it somehow. The proposal from docs is dedicated for GitHub, so it's easier to use `maven-settings-action`, but indeed, it won't be a good solution for other CI providers. Would you like to add an alternative approach to the guide? :)

**Comment by gerib** [comment]
Thanks for the quickest reply (after 12 mins!) to an issue on any bug/issue reporting site I used...ever...since decades! For that I owe you a 🍻 – at least – if I'm in Warsaw once again or you come to Vienna once. 

I see. Then I misunderstood that.

OTH, I really wouldn't like to have to use hundreds of characters long `mvn` cmd lines containing e.g.:

`... -D server.gitlab-maven.httpHeaders.property.name=Deploy-Token -D server.gitlab-maven.httpHeaders.property.value=${env.GITLAB_MAVEN_DEPLOY_TOKEN ...`

Not to mention the dynamic token _\<server>\<id>_ therein and not to mention missing comments (and extensive ones, as in the default 256-lines global `settings.xml`.

Do you, by chance, know [_You can't parse [X]HTML with regex._](https://stackoverflow.com/a/1732454/1744774)? :)

**Comment by dzikoysk** [comment]
> OTH, I really wouldn't like to have to use hundreds of characters long mvn cmd lines containing e.g.: [...]

Yeah, but if these variables would be defined directly in pom.xml, you could just simply provide their values through env variables that are supported by all CI/CD tools etc. & are passed to the process regardless of the cmd args. 

> Do you, by chance, know [You can't parse [X]HTML with regex.](https://stackoverflow.com/a/1732454/1744774)? :)
 
I didn't know, I wouldn't even think about parsing it with regex. 😅 

> And yes, I could add pages jenkins.md and gitlab.md to the guide.

Nice!

**Comment by gerib** [comment]
Especially the settings in the `<servers><server>` section(s) are in a file other than POMs for a (good) reason: security. `settings.xml`s are not intended to be stored in SCM repos, such avoiding user name(s), password(s), access token(s) (for servers not intended to be accessible by everyone, also even inside the same organization/company) being readable for _every_ user with read access to the repo.
