### ISSUE TITLE
UI Sizing issue with a large amount of mirrors

### ISSUE THREAD

**Issue by SirEndii** [dzikoysk/reposilite#1883]
### What happened?

I have a repository in reposilite with 12 mirrors, every time I try to create a new mirror, the UI stretches, moves to the left and I only see a small portion of the UI.

https://github.com/dzikoysk/reposilite/assets/67484093/483e80f8-a8f2-4d26-9d56-c6e9bd5c77b8

I can reproduce this on firefox and opera

### Reposilite version

3.x

**Comment by dzikoysk** [comment]
Yeah, these forms have several visual glitches :/ The library we use is pretty... bad. I'll try to find a workaround once I get back from my holiday trip.

**Comment by SirEndii** [comment]
Alright, thanks!
Is there currently a workaround?

**Comment by dzikoysk** [comment]
I couldn't reproduce it with short names, but I got a similar result for a repository with a name longer than the max-width. Hopefully, the root of this issue is the same & the fix solves both cases:

![obraz](https://github.com/dzikoysk/reposilite/assets/4235722/a87a4910-860a-45e7-af18-34624062b83c)

You can download the latest build (nightly) or wait for the next stable release to get this fix. If it'll still occur, let me know :)

**Comment by SirEndii** [comment]
Alrighty, I'm gonna test that today or tomorrow

**Comment by SirEndii** [comment]
![image](https://github.com/dzikoysk/reposilite/assets/67484093/047c73ea-4f87-4365-a5b1-02f9afe60a3b)

It sadly does not seem to work. I've pulled the new image `docker pull dzikoysk/reposilite:nightly`, stopped and deleted the container `docker stop cb5a && docker rm cb5a` and started a new container `docker run -it --mount type=bind,source=/home/srendi/mvnrepo/reposilite.cdn,target=/app/reposilite.cdn -e REPOSILITE_OPTS='--local-configuration=/app/reposilite.cdn' -v reposilite-data:/app/data --restart=always --name=mvn-reposilite dzikoysk/reposilite:nightly`

The pulling seems to worked just fine
![image](https://github.com/dzikoysk/reposilite/assets/67484093/022201ef-3e87-4264-ab1e-8a2c4da8b4bb)

**Comment by dzikoysk** [comment]
Hmm do you use Cloudflare or some other caching service? I'm asking, because your mirrored urls are still uppercase, but on the latest build it should be lowercase.

**Comment by SirEndii** [comment]
Oh yeah, you're right. I've seen this in your commit
I'm using Cloudflare but without caching or other features. Only for DNS (For this zone).

But it seems after the caching purge in Cloudflare that the uppercase change is now applied. So some type of caching seems to be applying here.


![image](https://github.com/dzikoysk/reposilite/assets/67484093/33139749-f2c6-45dd-b859-7129f1e1ab26)

But sadly it still does not work

**Comment by dzikoysk** [comment]
It's slightly hard for me to diagnose what could be the issue. Could you open dev tools and check which element in the tab component exceeds the width?

**Comment by SirEndii** [comment]
https://github.com/dzikoysk/reposilite/assets/67484093/95b98520-95b9-4bd9-a473-0572bba2c07d


https://github.com/dzikoysk/reposilite/assets/67484093/e588c79f-44c8-424b-bc3c-cccac00287dc

I was not sure what exactly you want to see. So I've just opened the dev tools and enabled the hover tool thingy.
As you can see in the video, after resizing the window, the issue resolves itself.

And sure, here's the file (Needed to zip it because file regulations)

[shared.configuration.zip](https://github.com/dzikoysk/reposilite/files/12325629/shared.configuration.zip)

**Comment by dzikoysk** [comment]
I'm unable to reproduce this on Win10/11/macOS with Firefox/Opera (latest stable/beta builds) with the repository list you gave me. Do you use some extra browser extensions?

**Comment by SirEndii** [comment]
I don't have any modifications except for [languagetool](https://languagetool.org/de)

**Comment by SirEndii** [comment]
A friend tested it for me, exactly the same issue. He's using Firefox on linux

**Comment by SirEndii** [comment]
If you want, I can give you access to the site and send you the credentials via PM on discord. I would trust you and in the case something bad happens, I've backups

**Comment by dzikoysk** [comment]
I think there are 2 ways to make it work for us: 

1. You'd need to try to modify the CSS in dev tools to find out how to properly wrap the tab in UI
2. Assuming that it's not related to your setup and this bug can be reproduced, I'd need to somehow get access to your setup (full copy of the settings without files/access to the instance)

Does any of these options would fit you?

**Comment by SirEndii** [comment]
> Does any of these options would fit you?

I'm familiar with CSS, but I'm not very well.

Your second option would be easier for me. Which files do you need, and have you read my message before where I offered access to the instance? I don't have any private data which you could see, so I don't worry about these type of things. I know that's not very professional to give someone access to your stuff, but as I said, I don't have anything to hide, and I have plenty of backups.

**Comment by dzikoysk** [comment]
Sure, I'm fine with the direct access to the instance. Hit me up on Discord - here's our server https://discord.gg/qGRqmGjUFX or through my username `dzikoysk`.
