### ISSUE TITLE
Better mobile support

### ISSUE THREAD

**Issue by solonovamax** [dzikoysk/reposilite#1910]
## Request details

Currently, the mobile support for reposilite is lacking. It would be great if the site could be more responsive for mobile devices.
Specifically, the dashboard, console, and settings tabs.

## Mobile UX issues

Checklist for tracking. Check off as implemented.

- [ ] Text overflows for file names in the file list. See file list screenshots.
   Proposed solutions:
   1. Truncate overflown text, and instead insert three dots (…). (but also show file extension + last 2-3 characters of file name. so, truncate text from the middle.)
- [ ] Inadequate padding for file sizes in file list, if name is too long. See file list screenshots.
   Proposed solutions:
   1. Hide the file size completely when on a mobile device. (Optional: show in a menu when long-pressed)
   2. Add more padding :5head:
   3. Increase height of file previews
- [ ] Oddly placed icons if file is selected in file list. See screenshot 3 of the file list.
- [ ] Icons are not shown for files when on mobile, but tapping on the location they are in activates them. For example, if you tap on the far right of a file name on mobile, it will prompt to delete the file, even though it did not show the file deletion icon (because it's a hover effect). (however, if you long press on a file then tap off the popup, it will show the icon as it registers it as being "selected"/"hovered")
   Proposed solutions:
   1. When on mobile device/touchscreen, if you long-press, a list of actions are displayed. (view, delete, etc.)
   4. When on mobile device/touchscreen, always show the delete icon.
- [ ] Things take up *way* too much space (imo) on mobile.
   Proposed solutions:
   1. Decrease padding, margins, and spacing.
   2. Do nothing
- [ ] Account icons off-center on mobile. See account icons screenshot.
- [ ] Dashboard is way too tight & wastes too much space. See dashboard screenshot.
   Proposed solution:
   1. Decrease margins & padding. Place instance status in a grid. Use full width for graphs. (possibly also decrease line stroke size for the graph? It blends together a little too much.)
- [ ] Too much padding around console.
   Proposed solutions:
   1. Decrease padding around console.
- [ ] Settings menu will sometimes randomly shift to the left. Unsure of cause.
- [ ] Too much padding around settings.
   Proposed solution:
   1. Decrease padding around settings.
- [ ] Text/content overflow for settings.

#### File List
![Screenshot 1 of file list](https://github.com/dzikoysk/reposilite/assets/46940694/5045293e-9bc4-4525-995d-ea362748cec7)
![Screenshot 2 of file list](https://github.com/dzikoysk/reposilite/assets/46940694/84107bf4-476a-4057-91aa-7b02d5e70354)
![Screenshot 3 of file list](https://github.com/dzikoysk/reposilite/assets/46940694/dc9480db-29f9-4d73-8dda-87bb3a6da8dc)

#### Account Icons
![Screenshot 1 of account icons](https://github.com/dzikoysk/reposilite/assets/46940694/cc8541f4-617d-4c47-93c3-3905754d8338)

#### Dashboard
![Screenshot 1 of dashboard](https://github.com/dzikoysk/reposilite/assets/46940694/d412a243-9fee-40a7-a510-346eae6db099)

#### Console
![Screenshot 1 of console](https://github.com/dzikoysk/reposilite/assets/46940694/d35be8f4-7275-4d60-8c91-f643b7609603)

#### Settings
![Screenshot 1 of settings](https://github.com/dzikoysk/reposilite/assets/46940694/d36e4743-a403-474f-a890-4312642deb2c)
![Screenshot 2 of settings](https://github.com/dzikoysk/reposilite/assets/46940694/adf466c4-48ff-45c5-9be1-84d7c4966b20)

**Comment by dzikoysk** [comment]
I doubt we can improve settings (#1320) tab, but the others could be probably adjusted at some point.

**Comment by solonovamax** [comment]
I've updated the issye to contain details for changes that would be nice.

**Comment by dzikoysk** [comment]
I feel like the worst parts of the UI have been improved lately - of course there are still some improvements that could be made, but considering the fact that we'll completely remove this whole frontend module in 4.x, I'd rather prefer to prioritize other stuff.

**Comment by solonovamax** [comment]
I'd say it's been mostly solved other than settings/console (although console is *useable*)

but one issue I just noticed is the "File browser adjustments" dialogue:

![Screenshot_2024-11-23-16-18-23-50_50ecd26a21c2c56ce608de5e94733463.jpg](https://github.com/user-attachments/assets/f5370091-64c2-4c3f-a935-82353f012719)

this one shouldn't be a difficult fix just set a max width when the screen size is below a certain amount.

**Comment by solonovamax** [comment]
also the fact that all the filesizes are not aligned/starting in the same placr *does* kinda annoy me, but it's not by any means a *major* issue by any means.

![Screenshot_2024-11-23-16-22-26-45_50ecd26a21c2c56ce608de5e94733463.jpg](https://github.com/user-attachments/assets/321568bb-b1cc-4539-9db5-63ebc4f49faa)

![Screenshot_2024-11-23-16-22-49-44_50ecd26a21c2c56ce608de5e94733463.jpg](https://github.com/user-attachments/assets/76066328-d1ae-451d-a8a5-d03bcf1a7f14)
