### ISSUE TITLE
root check broken in Docker `entrypoint.sh`

### ISSUE THREAD

**Issue by justusbunsi** [dzikoysk/reposilite#1924]
### What happened?

9799671362533c2a47899dd59308b3b44161310b introduces a UID check within `entrypoint.sh` to determine whether the container is started as root user or not.

The entrypoint defined in [Dockerfile](https://github.com/dzikoysk/reposilite/blob/e19660b89228e177c8a6a6ee42625bf49b42873a/Dockerfile#L41) uses `/bin/sh` to start the `entrypoint.sh`. Unfortunately, the `if` condition syntax is not compatible with plain shell, but works in Bash.

This makes it currently impossible to specify something like Kubernetes `securityContext` without overriding the entrypoint command to `['bin/bash', 'entrypoint.sh']`. The script does not fail and always assumes root user context.

### Reposilite version

3.x

### Relevant log output

Running the latest Docker image as root user (`docker run --rm -it ghcr.io/dzikoysk/reposilite:3.4.8`):

```shell
entrypoint.sh: 10: [: Illegal number:                                                                                                                                                   
Adding group `reposilite' (GID 999) ...
Done.
Adding system user `reposilite' (UID 999) ...                     
Adding new user `reposilite' (UID 999) with group `reposilite' ...
Creating home directory `/home/reposilite' ...
14:31:53.094 INFO | 
14:31:53.101 INFO | Reposilite 3.4.8                          
14:31:53.101 INFO |                                           
14:31:53.101 INFO | --- Environment                           
14:31:53.104 INFO | Platform: 19 (Linux :: amd64)             
14:31:53.104 INFO | Running as: reposilite
```

Running the latest Docker image as non-root user (`docker run --rm -it --user 999 ghcr.io/dzikoysk/reposilite:3.4.8`):

```shell
entrypoint.sh: 10: [: Illegal number: 
addgroup: Only root may add a user or group to the system.
adduser: Only root may add a user or group to the system.
chown: invalid user: ‘reposilite:reposilite’
chown: invalid user: ‘reposilite:reposilite’
runuser: user reposilite does not exist or the user entry does not contain all the required fields
```

**Comment by justusbunsi** [comment]
Possible solutions for this would be:

- Switch Dockerfile entrypoint to `/bin/bash`
- Use a "default" shell comparison syntax, such as `if (( $UID > 0 )); then .....`

I would also suggest to use `set -e` at the top of the entrypoint script, to let the container fail on script errors.

I don't know which solution is preferred, please let me know and I'll provide a PR for it.

**Comment by dzikoysk** [comment]
Hi, thanks for reporting this. All suggestions sound ok, so it's up to you to choose which one suits better :)
