### ISSUE TITLE
Title customization

### ISSUE THREAD

**Issue by jolheiser** [dzikoysk/reposilite#193]
Opened from #192 
Related to #138 

> 1. The page title can be built using title - description format and I don't think we need another variable for it.
> 2. I don't really want to force people to display Reposilite on their page - they may leave a note in a description, but we should let 'em hide it. It is why any kind of footer is not a good idea.

1. Can you explain what you mean? Currently the title is hard-coded as `Reposilite`
2. That's fair, it could be turned off with a config (depending on proposal acceptance).  
Do I take this to mean you'd rather not have a footer at all?

**Comment by dzikoysk** [comment]
1. You could replace hard-coded `Reposilite` with `{{ title }} - {{ description}}` format (title and description are already available in configuration)
2. I think that it is not a good idea to add footer at all. We can consider changes in this area during GH-138 where we will improve the overall layout and design of frontend.

**Comment by jolheiser** [comment]
Since the title is part of `index.html` and outside Vue's mount, I don't think Vue can change it currently.
Do you have an idea on how to work around that?

**Comment by dzikoysk** [comment]
You can define title using `metaInfo` property from vue-meta. As an example, it is already used in `Index.vue`

**Comment by jolheiser** [comment]
Got it! Do you want me to be committing compiled production JS with PRs? Or do you do that yourself prior to release?

**Comment by dzikoysk** [comment]
Yeah, commit changes to frontend with updated production app :)
