### ISSUE TITLE
Helmrelease (v 3.4.8) can't start on 64MB of memory

### ISSUE THREAD

**Issue by JWood48** [dzikoysk/reposilite#1933]
### What happened?

Using the helm release (v 3.4.8) to start a single reposilite instance on k8s results in a OOMKilled - increasing to 128MB got reposilite in the air but using 125MB ram, and running any commands resulted in OOMKilled again - increasing to 256MB seems to run stable with 156MB memory used. 

Is this expected? The helm values com predefined with only 64MB memory limit

<img width="460" alt="image" src="https://github.com/dzikoysk/reposilite/assets/1113096/ca34a4a6-1abd-4cb9-89c6-446350884c3e">

### Reposilite version

3.x

**Comment by dzikoysk** [comment]
There are 3 memory options:
1. Size of the heap - a space available for Java app where objects are allocated (32mb+ should be enough in most cases, 64mb+ might be needed as a minimum for a repo with heavy plugins like e.g. Groovy/higher traffic)
2. Process memory - a general cost of JVM
3. Container - a memory required to properly handle an ecosystem around the JVM

The default for the 1st one seems to be valid:

* https://github.com/reposilite-playground/reposilite-helm/blob/main/charts/reposilite/values.yaml#L124

Speaking about the 2nd & 3rd... it depends on quite a lot of things. I'm not quite sure how k8s manages it, so we may need to wait for @joshuasing that set this up.

Did you use Reposilite before 3.4.8 and these limits were enough earilier?

**Comment by joshuasing** [comment]
Hi @JWood48

I am currently running Reposilite v (chart v1.2.7) on a K3s cluster.
It has the following resource configuration:
```yaml
## Resources
resources:
  limits:
    cpu: "200m" # probably overkill
    memory: 256Mi
  requests:
    cpu: "50m"
    memory: 64Mi

## Environment variables
env:
  - name: JAVA_OPTS
    value: "-Xmx128M"
```

I have never had an issue with this configuration, and I have never seen it get OOM killed.
However, as the JVM will use a bit more than the specified `-Xmx` value, I would always recommend adding a buffer to the memory limit.
Maybe is this a configuration problem? Would you mind providing a copy of your Helm values (redact if needed)?

**Comment by JWood48** [comment]
Hi

Increasing the values works fine for me, just to let you know that the default values in the helm chart may not be adequate, and user are forced to update them to get Reposilite up and running.

@dzikoysk it was my first install - so was puzzled why I needed to increase the memory manually.

**Comment by joshuasing** [comment]
Great to hear - I created the helm chart so this is likely my fault, I'll take a look and hopefully submit a pr this week to improve the chart. Sorry for the inconvenience.

**Comment by dzikoysk** [comment]
Sure, we have some upcoming changes to our Helm chart, so I guess it could be addressed as well in:

* https://github.com/reposilite-playground/reposilite-helm/issues/9

**Comment by dzikoysk** [comment]
Moving to:
* https://github.com/reposilite-playground/reposilite-helm/issues/13
