### ISSUE TITLE
Async timeout is 600 minutes, when comment in code specifies it should be 10 minutes

### ISSUE THREAD

**Issue by solonovamax** [dzikoysk/reposilite#1937]
### What happened?

`config.http.asyncTimeout` is set to `1000L * 60 * 60 * 10` for the `JavalinConfig`. The comment indicates it should be 10 minutes.

https://github.com/dzikoysk/reposilite/blob/7a5a21c1497ddfd00b31f258eb80fd17f578dfeb/reposilite-backend/src/main/kotlin/com/reposilite/web/application/JavalinConfiguration.kt#L97

However, it is definitely not 10 minutes. I checked javalin, and the units that particular variable uses is in milliseconds (not documented, but I found a reference in the source where it is passed to `jakarta.servlet.AsyncContext#setTimeout`, which is in milliseconds)

converting the value provided there into minutes gives 600 minutes. It should instead be `1000L * 60 * 10`. However, using kotlin's time api would be better: `10.minutes.inWholeMilliseconds`. This is more clear, and indicates that it is exactly 10 minutes. which is then converted to milliseconds.

### Reposilite version

3.x

### Relevant log output

```shell
n/a
```

**Comment by dzikoysk** [comment]
Thanks, I didn't notice this. I guess it was just a typo 🤔

**Comment by solonovamax** [comment]
I was just randomly looking through the source and saw it lol
