### ISSUE TITLE
White page on Apache-Proxy

### ISSUE THREAD

**Issue by ToCraft** [dzikoysk/reposilite#1939]
### What happened?

I used the following apache configuration: 

```
<IfModule mod_ssl.c>
<VirtualHost *:443>
        ServerAdmin webmaster@localhost
        DocumentRoot /var/www/DOMAIN_NAME


        ErrorLog ${APACHE_LOG_DIR}/error.log
        CustomLog ${APACHE_LOG_DIR}/access.log combined

        ServerName DOMAIN_NAME
        Include /etc/letsencrypt/options-ssl-apache.conf
        Protocols h2 http/1.1

RewriteEngine On

RewriteCond %{HTTP:Upgrade} =websocket [NC]
RewriteRule ^/api/(.*) ws://127.0.0.1:8080/api/$1 [P,L]

ProxyPass /maven/ http://127.0.0.1:8080/
ProxyPassReverse /maven/ http://127.0.0.1:8080/

SSLCertificateFile /etc/letsencrypt/live/DOMAIN_NAME/fullchain.pem
SSLCertificateKeyFile /etc/letsencrypt/live/DOMAIN_NAME/privkey.pem
</VirtualHost>
</IfModule>
```
The sites loads, but I only get a white screen (on `https://DOMAIN_NAME/maven/`):

![image](https://github.com/dzikoysk/reposilite/assets/38883321/06df73d5-e02f-48fd-858d-08ca74bfc90f)

I'm using the default reposilite configuration.

### Reposilite version

3.x

**Comment by ToCraft** [comment]
Ups, I just found this line at the bottom of the config-file: 
`basePath: /maven/`

Now it works. Nevertheless, a more detailed apache-documentation would be nice :D

**Comment by dzikoysk** [comment]
Nice, would you like to update the guide? We don't have many Apache users, so any feedback is appriciated :)

**Comment by ToCraft** [comment]
Ye, I'll try to update it :D
