### ISSUE TITLE
Move to JDK21

### ISSUE THREAD

**Issue by dzikoysk** [dzikoysk/reposilite#1960]
https://github.com/reposilite-playground/reposilite-aur/issues/21

**Comment by dzikoysk** [comment]
Blocked by:
* https://github.com/gradle/gradle/issues/25574

**Comment by PolarianDev** [comment]
`Caused by: java.lang.IllegalArgumentException: Unknown Kotlin JVM target: 21`

So java is working with gradle `8.4` but Kotlin is yet to follow.

Welp Java 20 is good enough.

**Comment by dzikoysk** [comment]
It's an issue with Gradle, not Kotlin atm. We can manually bump Kotlin version in Gradle, but later on it'll throw exceptions on Kapt + if we'll explicitly set JDK21 in the toolchain for Gradle, it'll fail on CI with JDK11.

**Comment by PolarianDev** [comment]
In other words, not mature enough yet. It was worth a try I guess.

Migrate to jdk21 when the issue is solved?

**Comment by dzikoysk** [comment]
Yup, we need to wait for sth like Gradle 8.4.1/8.5

**Comment by dzikoysk** [comment]
Gradle 8.5-rc.1 supports JDK21, but Kapt (Kotlin's annotation processor adapter) is unable to start, so we need to wait for next RC/official release.

**Comment by dzikoysk** [comment]
Related issue:

* https://youtrack.jetbrains.com/issue/KT-60507/Kapt-IllegalAccessError-superclass-access-check-failed-using-java-21-toolchain

It looks like the fix targets Kotlin 2.0, but not 1.9.20. It's a bit strange.

**Comment by dzikoysk** [comment]
In theory, it should work with 1.9.21:

* https://github.com/JetBrains/kotlin/releases/tag/v1.9.21
