### ISSUE TITLE
Use system theme

### ISSUE THREAD

**Issue by Desoroxxx** [dzikoysk/reposilite#1961]
### Request details

It would be great to have an option to follow system theme

**Comment by joshuasing** [comment]
Hi,

It looks like Reposilite uses the `prefers-color-scheme` media query to determine the theme, when not set by the user:
https://github.com/dzikoysk/reposilite/blob/main/reposilite-frontend/src/store/theme.js#L28

Once the theme toggle button is used, it does not appear to be possible to use this behaviour again, without removing the `dark-theme` item from the site's local storage manually.

Maybe the theme toggle button could be replaced with a drop-down (or similar) that has a 'System' option?
https://github.com/dzikoysk/reposilite/blob/main/reposilite-frontend/src/components/header/MenuPanel.vue#L52-L55

**Comment by dzikoysk** [comment]
Instead of a drop-down, we could use a 3rd icon - the `A` letter that would refer to the `Automatic` mode
