### ISSUE TITLE
Allow custom favicon

### ISSUE THREAD

**Issue by zeichenreihe** [dzikoysk/reposilite#1976]
### Request details

Currently the favicon is hardcoded. You should be able to use a custom favicon.

**Comment by dzikoysk** [comment]
Favicon is not hardcoded, frontend requests `/favicon.png` location:

https://github.com/dzikoysk/reposilite/blob/e185d3231c9e6dff60ab41c13151e7206d0e3ec0/reposilite-frontend/index.html#L21

And by default, this icon is hosted from `/static` directory:

* https://reposilite.com/guide/static-files

**Comment by ntt77** [comment]
@dzikoysk correct folder name /static, but the guide said /public
