### ISSUE TITLE
Option to skip s3 bucket existance check/creation

### ISSUE THREAD

**Issue by hex-agon** [dzikoysk/reposilite#1978]
### Request details

Currently whenever the s3 storage provider is initiated it performs a `HeadBucket` request to determine if the bucket exists and attempts to create it when it does not. This means that extra permissions are required besides get/list/put object for normal operation. 

This also cause an incompatibility with CloudFlare's R2 because it's permissions aren't granular enough and `Object Read & Write` is not able to perform the `HeadBucket` request (this seems to be a R2 bug as `HeadBucket` should only require the `s3:ListBucket` permission) meaning `Admin Read and Write` must be used for normal operation, this permission is dangerous as it allows full access to perform read/write/create/delete to all the R2 buckets in the account.

If possible, please include an option to skip the bucket check attempt on the storage initialization.

**Comment by dzikoysk** [comment]
I've covered it with a system property called `reposilite.s3.skip-bucket-creation`. If you launch your process with `-Dreposilite.s3.skip-bucket-creation=true` flag, S3 provider won't try to make a head request & create a bucket at all. It's a bit niche, so I didn't put it in the main cfg, although in case of more people affected by this behavior, we can for sure reconsider that.
