### ISSUE TITLE
Reposilite 3.5 unable to start

### ISSUE THREAD

**Issue by SirEndii** [dzikoysk/reposilite#1979]
### What happened?

Hey
after upgrading to 3.5, the docker container is unable to find java? That is what at least the logs tell me.
Using `dzikoysk/reposilite:latest` as the image.

### Reposilite version

3.x

### Relevant log output

```shell
Adding group `reposilite' (GID 999) ...
Done.
Adding system user `reposilite' (UID 999) ...
Adding new user `reposilite' (UID 999) with group `reposilite' ...
Creating home directory `/home/reposilite' ...
runuser: failed to execute java: No such file or directory
reposilite:x:999:999::/home/reposilite:/bin/sh
runuser: failed to execute java: No such file or directory
reposilite:x:999:999::/home/reposilite:/bin/sh
runuser: failed to execute java: No such file or directory
reposilite:x:999:999::/home/reposilite:/bin/sh
runuser: failed to execute java: No such file or directory
...
```

**Comment by dzikoysk** [comment]
Hmm... this is strange. I've only bumped JDK from 19 -> 20, CI works:

* https://github.com/dzikoysk/reposilite/actions/runs/6842989228/job/18605089885

I'll try to rebuild & run it on localhost. Thanks for reporting this.

**Comment by dzikoysk** [comment]
@SirEndii do you use some kind of a custom software to run your Docker image? It looks fine for me:

![obraz](https://github.com/dzikoysk/reposilite/assets/4235722/7ed3d9ac-73cf-4ade-99d8-34a50087462b)

**Comment by SirEndii** [comment]
Yeah, I use portainer
It seems that in the ENV vars it uses JDK 19

**Comment by dzikoysk** [comment]
Yeah, I think we had similar issue in the past with Portainer. It seems to put JDK version in env variables when container is initialized, but later on it's not detecting changes, so it keeps referring the old value. I wonder if there's something we could do to notify it about this change.

**Comment by SirEndii** [comment]
![image](https://github.com/dzikoysk/reposilite/assets/67484093/12b867bb-9b39-4aa9-b8be-2f9c54bb97cd)

Removed them, they got automatically replaced
Still, didn't fix the problem 🤔

**Comment by dzikoysk** [comment]
The `PATH` still refers 19, so it could be the issue 🤔

**Comment by SirEndii** [comment]
Woops, I just noticed

**Comment by SirEndii** [comment]
Yeah, that fixed it
Thank you for the help

**Comment by dzikoysk** [comment]
Nice :)
