### ISSUE TITLE
Title is breaking on dashboard

### ISSUE THREAD

**Issue by jolheiser** [dzikoysk/reposilite#198]
This is my fault, sorry. I never noticed because when it fails, it doesn't end up changing the title so without checking console I didn't see.

Dashboard is trying to reference configuration, however it never actually sets or queries for that data.
https://github.com/dzikoysk/reposilite/blob/a722ea253c7adb5c3587d32ca04a02b11dd7c932/reposilite-frontend/src/views/Dashboard.vue#L61-L73

To fix this I would like to get your opinion on two options:

1. Dashboard can query for config, or
2. Dashboard can just not update the title.
    * The only caveat to this is if someone goes directly to the URL, I _think_ it would just be an empty title, unless we add a fallback in `index.html`

**Comment by dzikoysk** [comment]
Well, I'm on vacation and my code review from phone/laptop might be poor 😛. I think we could use hard-coded version of title for dashboard. It might be improved in overall UI (#138) update where the segmentation of views and components will reduce boilerplate code and unnecessary copy-paste between public index and dashboard.
