### ISSUE TITLE
Customization & Formatting

### ISSUE THREAD

**Issue by cameronbowe** [dzikoysk/reposilite#1981]
### Request details

To be honest, having "net.cameronbowe" would be much preferable then "net.cameronboweSnapshot" or whatever for the repos that I am getting, why can't they be customized at all..? And why can we not change the links directly, and customize the endpoints..? Having the "link/<repository> at the home page doesn't make sense to me, why can't we change what that says because <repository> makes it a little confusing when everything on there is a repository.

**Comment by dzikoysk** [comment]
I'm not quite sure what kind of issue you have, as you've mentioned a few different things, so I'll try my best to address some of them.

> To be honest, having "net.cameronbowe" would be much preferable then "net.cameronboweSnapshot" or whatever for the repos that I am getting, why can't they be customized at all..?

Are you talking about the repository details, and to be more precise - the Gradle snippets? If so, these names follow the official standard:

* https://docs.gradle.org/current/userguide/declaring_repositories.html#sec:handling_credentials

This name is also used directly in the `publish` command, so it kinda makes sense to make it compatible with CLI by default. Regardless of the issue, there's a feature request for customizable snippets:

* https://github.com/dzikoysk/reposilite/issues/1782

It's a cosmetic & low priority issue for me, but feel free to contribute, we can definitely discuss an alternative. 

>  And why can we not change the links directly, and customize the endpoints..?

Sadly, I'm not sure what endpoints you'd like to customize. While you're in the root directory, the URL looks like `https://maven.reposilite.com/<repository>`, so the `<repository>` indicates a place, where user should provide a repository name. By going to the specific repository, the URL is automatically updated to a qualified variant: e.g. `https://maven.reposilite.com/releases`. This endpoint cannot be changed as it's an URL for Maven client that is used to query requested artifacts. 

 > Having the "link/ at the home page doesn't make sense to me, why can't we change what that says because makes it a little confusing when everything on there is a repository.
 
The link on the home page can be customized. You should login to the dashboard with a management token & go to the `Frontend` section:

![obraz](https://github.com/dzikoysk/reposilite/assets/4235722/c000ae68-7701-4228-9088-f04400368273)

4.

**Comment by cameronbowe** [comment]
The name 
https://i.imgur.com/fmCTEa7.png
https://i.imgur.com/PJECLj7.png
Why does it have "Public" right after..?

**Comment by dzikoysk** [comment]
Because `id` in Maven snippet & `name` in Gradle snippet have to be unique, so we're displaying a default one as a combination of `repository-id + repository-name`. For instance, when you go:

- To `/releases`, then it will be `xxxReleases`
- To `/public`, then it will be `xxxPublic`

To be fair, it's up to users what's the repository name in the build file, as long as it points to a valid URL, it will work properly.

**Comment by cameronbowe** [comment]
Why can't it be like .public or something? it just seems a bit weirdly formatted- but so I can still use "net.cameronbowe" as the name or?

**Comment by dzikoysk** [comment]
It can be whatever you want in Gradle, it's optional, so we're providing a format that is used by official Gradle's guide. If you don't provide the name, Gradle will automatically generate the command name from the url and it will still work.
