### ISSUE TITLE
Docker Image Not Properly Running Frontend

### ISSUE THREAD

**Issue by Thomas-Scott** [dzikoysk/reposilite#200]
Download the 2.8.0 release jar, configure to run on port 8080 and the frontend is accessible but `docker run -it -p 8080:80 dzikoysk/reposilite:2.8.0` yields a server that gives an empty response.

Version: 2.8.0, 2.7.4

Steps to reproduce:
1. `docker run -it -p 8080:80 dzikoysk/reposilite:2.8.0`
2.  Visit localhost:8080 and see an empty response.

See below image, first curl is for the jar execution, second is for the docker run. 

![Screen Shot 2020-08-05 at 11 55 34 PM](https://user-images.githubusercontent.com/1820141/89492424-29c3cf80-d777-11ea-8e5a-ecf8ca405e53.png)

**Comment by dzikoysk** [comment]
It looks like a misconfiguration of your Docker instance. For instance similar issue: https://github.com/moby/moby/issues/2522

**Comment by Thomas-Scott** [comment]
This comment makes it seem like this would stem from the reposilite configuration using "localhost" as the JS mount, no? 
https://github.com/moby/moby/issues/2522#issuecomment-51720938

**Comment by dzikoysk** [comment]
This problem is not related to the Reposilite frontend. Could you try to bind your instance to 0.0.0.0?

**Comment by Thomas-Scott** [comment]
Configuring hostname to be 0.0.0.0 allows the content to be served outside the container. Thoughts on changing the default? https://github.com/dzikoysk/reposilite/blob/master/reposilite-backend/src/main/java/org/panda_lang/reposilite/config/Configuration.java#L35

**Comment by dzikoysk** [comment]
Docker build does not contain custom configuration file, it uses the default one generated during first startup. Changing it to `0.0.0.0` sounds reasonable. I need to also improve the Docker section in guide on the website.
