### ISSUE TITLE
Group Kotlin multiplatform artifacts together

### ISSUE THREAD

**Issue by SPC-code** [dzikoysk/reposilite#2002]
### Request details

One of the problems when publishing kotlin multiplatform artifacts is that each artifact for each platform is displayed separately. 

![image](https://github.com/dzikoysk/reposilite/assets/112205870/e38cb02d-bc2b-49f1-84ec-6ca7460e678f)

It would be nice to be able to group different platform artifacts together in expandable sub list.

**Comment by dzikoysk** [comment]
KMP follows standard Maven structure for each artifact & adding this kind of feature to cover this niche doesn't really make much sense. Reposilite is supposed to work in a client-agnostic way, so I think this is not something we can address at this moment.
