### ISSUE TITLE
Public Repositories cannot be seen on dashboard without logging in (works on 3.4.3, fails on 3.5.1)

### ISSUE THREAD

**Issue by fa993** [dzikoysk/reposilite#2004]
### What happened?

https://dzikoysk.medium.com/reposilite-3-x-setup-your-own-maven-repository-manager-in-5-minutes-e72cc8b67bc3

- Followed this guide and pushed an artifact to the release repository on my instance.
- Visited the dashboard, but couldn't see the files
- Logged in and was able to see them
- Double checked if the releases repository was marked public

Downloaded the 3.4.3 jar and then ran it, I was able to see those files in the dashboard

### Reposilite version

3.x

**Comment by dzikoysk** [comment]
Indeed, it looks like a bug with a new directory emulator. You can use 3.5.0 and it should be just fine, thanks for reporting this.

**Comment by dzikoysk** [comment]
JavaScript moment

![obraz](https://github.com/dzikoysk/reposilite/assets/4235722/6daf51ed-6361-4e11-a308-24f62c191f2c)

It'll be fixed in 3.5.2, I'll try to release it later today
