### ISSUE TITLE
Ability to disable logging to file and `Journalist`

### ISSUE THREAD

**Issue by felixscheinost** [dzikoysk/reposilite#2024]
### Request details

Related to #1199 

I am trying to run Reposilite in k8s with centralized logging and I wanted to ask if it was possible to add an option to only log to stdout. Maybe the `Journalist` could even be disabled for stdout, so that stdout is really just plain old stdout of tinylog?

**Comment by dzikoysk** [comment]
You should be able to disable log file via `-Dtinylog.writerFile.level=off` system property :) Journalist implements tinylog's logger, so we can catch all logs, but that's basically just a proxy, so it shouldn't be an issue.

**Comment by felixscheinost** [comment]
Thanks! I looked for a `disable` option or something like that in the tinylog configuration but I missted that `off` is a option :) 

Am I understanding correctly that I could then use `--level debug` to get the same log as is normally written to `latest.log` to stdout?

**Comment by dzikoysk** [comment]
Yes, you can even use a `level` command in terminal/web console, because we're able to change logging level dynamically.
