### ISSUE TITLE
How to setup token secret brute force protection?

### ISSUE THREAD

**Issue by DWolf-19** [dzikoysk/reposilite#2026]
### Request details

Does reposilite have protection against the brute force of secrets? I didn't find any information in the docs.

I wanted to try setup fail2ban, but one thing worries me: there is no IP address in the authentication error line.
```
com.reposilite.journalist.slf4j.Slf4jLogger DATE TIME DEBUG | GET /api/auth/me from HOST
# Error
com.reposilite.journalist.slf4j.Slf4jLogger DATE TIME DEBUG | USER failed to authenticate with Basic realm due to ErrorResponse(status=401, message=Invalid authorization credentials)
com.reposilite.journalist.slf4j.Slf4jLogger DATE TIME DEBUG | ERR RESULT | GET /api/auth/me errored with ErrorResponse(status=401, message=Invalid authorization credentials)
```

Could this be the case if there are 2 parallel authentication attempts and line with the error will not go immediately after `GET /api/auth/me from HOST`? Because in this case, regex may not work/will not work correctly.
```
com.reposilite.journalist.slf4j.Slf4jLogger DATE TIME DEBUG | GET /api/auth/me from HOST
com.reposilite.journalist.slf4j.Slf4jLogger DATE TIME DEBUG | GET /api/auth/me from HOST
com.reposilite.journalist.slf4j.Slf4jLogger DATE TIME DEBUG | USER failed to authenticate with Basic realm due to ErrorResponse(status=401, message=Invalid authorization credentials)
com.reposilite.journalist.slf4j.Slf4jLogger DATE TIME DEBUG | ERR RESULT | GET /api/auth/me errored with ErrorResponse(status=401, message=Invalid authorization credentials)
com.reposilite.journalist.slf4j.Slf4jLogger DATE TIME DEBUG | USER failed to authenticate with Basic realm due to ErrorResponse(status=401, message=Invalid authorization credentials)
com.reposilite.journalist.slf4j.Slf4jLogger DATE TIME DEBUG | ERR RESULT | GET /api/auth/me errored with ErrorResponse(status=401, message=Invalid authorization credentials)
```

**UPD:** I found a solution: I run Reposilite behind Nginx, so I can just catch 401 in its logs. But I will still leave the issue open, as others may not have a web server.

**UPD 2:** Reposilite tries to authorize user every time they visit site, so catching 401 will be more annoying than useful.

**Comment by dzikoysk** [comment]
Now, it'll be logged as `${credentials.name}@${credentials.host} failed to authenticate with ${authenticator.realm()} realm due to $it"`. I think your setup should be easily able to catch this now :)

**Comment by DWolf-19** [comment]
Thank you very much! I will try to set up protection after release.

**Comment by DWolf-19** [comment]
Also, what about the built-in mechanism? As far as I know, for example, Grafana has some kind of protection against brute force when log-in to dashboard by default.

**Comment by dzikoysk** [comment]
Sure, we can think about it. Could you submit a new issue with some more details about the requested feature? :)
