### ISSUE TITLE
401 Invalid Authorization Credentials using LDAP auth

### ISSUE THREAD

**Issue by mstup** [dzikoysk/reposilite#2054]
### What happened?

I tried Reposilite 3.5.6 intergrate with OpenLDAP 2.4.57
On user login Reposilite reports error - "401 Invalid Authorization Credentials".

OpenLDAP log on Reposilite login:
```
ldap_1                | 65ccb304 conn=1021 fd=12 ACCEPT from IP=172.18.0.5:43118 (IP=0.0.0.0:389)
ldap_1                | 65ccb304 conn=1021 op=0 BIND dn="cn=readonly,dc=domain,dc=com" method=128
ldap_1                | 65ccb304 conn=1021 op=0 BIND dn="cn=readonly,dc=domain,dc=com" mech=SIMPLE ssf=0
ldap_1                | 65ccb304 conn=1021 op=0 RESULT tag=97 err=0 text=
ldap_1                | 65ccb304 conn=1021 op=1 SRCH base="ou=people,dc=domain,dc=com" scope=2 deref=3 filter="(&(objectClass=posixAccount)(uid=mykola))"
ldap_1                | 65ccb304 conn=1021 op=1 SRCH attr=uid
ldap_1                | 65ccb304 conn=1021 op=1 SEARCH RESULT tag=101 err=0 nentries=1 text=
ldap_1                | 65ccb304 conn=1022 fd=13 ACCEPT from IP=172.18.0.5:43120 (IP=0.0.0.0:389)
ldap_1                | 65ccb304 conn=1022 op=0 BIND dn="uid=mykola,ou=people,dc=domain,dc=com" method=128
ldap_1                | 65ccb304 conn=1022 op=0 BIND dn="uid=mykola,ou=people,dc=domain,dc=com" mech=SIMPLE ssf=0
ldap_1                | 65ccb304 conn=1022 op=0 RESULT tag=97 err=0 text=
ldap_1                | 65ccb304 conn=1022 op=1 SRCH base="ou=people,dc=domain,dc=com" scope=2 deref=3 filter="(&(objectClass=posixAccount)(uid=mykola)(memberOf=cn=users,ou=reposilite,dc=domain,dc=com))"
ldap_1                | 65ccb304 conn=1022 op=1 SRCH attr=uid
ldap_1                | 65ccb304 conn=1022 op=1 SEARCH RESULT tag=101 err=32 nentries=0 text=
```
We have two binds: 
1. conn=1021 
Works fine for connect **readonly** user
2. conn=1022 
Failed for user **mykola** because of err=32 (No such object)

This error is caused because LDAP is blocking login for any other users (even if they actually exists). Only some particular users (**readonly** in my case) this is allowed.

I think no needs on the second Bind to use actual user (**mykola**), but reuse the first one (**readonly**) again.
Otherwise it will require to change LDAP security configuration to allow this, but it's kind of undesirable practice because BindDN is used.

### Reposilite version

3.x

**Comment by mstup** [comment]
@dzikoysk As you asked, my _shared_ configuration. Only LDAP configuration added and all the rest left untouched.
[shared.configuration.json](https://github.com/dzikoysk/reposilite/files/14297760/shared.configuration.json)

**Comment by dzikoysk** [comment]
Could you take a look at this setup:

https://github.com/dzikoysk/reposilite/blob/9a20c45cd0fd9a50d679246cc441b3ca0dc5aee7/reposilite-backend/src/test/kotlin/com/reposilite/auth/LdapAuthenticatorTest.kt#L141-L206

It works for me, so I'm not quite sure what change would be required here. 

* `mykola` authenticated, `readonly` not authenticated if `baseDn` is set to `ou=people,dc=domain,dc=com`
* `mykola` authenticated, `readonly` authenticated if `baseDn` is set to `dc=domain,dc=com`

I guess you have a bit of different setup on your server, so we'd need to recreate this on my side first & investigate if it's indeed correct.

**Comment by mstup** [comment]
@dzikoysk  Here is some part of my configuration.

![image](https://github.com/dzikoysk/reposilite/assets/16793676/804115ae-5e6a-41e9-b152-67f898aa6c21)

**Comment by dzikoysk** [comment]
Thanks for your cooperation, it took us a while 😅 I'll try to release it this week as 3.5.7, but you can already use nightly/snapshot build.
