### ISSUE TITLE
SHA1 checksum is different, causing SBT build to fail

### ISSUE THREAD

**Issue by hzwaal** [dzikoysk/reposilite#2099]
### What happened?

I'm using SBT to build my Scala code and have set up Reposilite as a mirrored repository for Maven.

SBT uses Coursier for its fetching artifacts, which will download its own jar and verify it. This fails, because the SHA1 checksum returned by Reposilite is different than expected. As a consequence, my build aborts, making it impossible for me to use Reposilite in combination with SBT.

In the FAQ I read:

> Q: Checksum validation failed on the maven-metadata.xml
> A: Checksum validation always fails, because Reposilite does not trust the metadata files offered by client - they're generated by server, based on the repository content to ensure consistency. It's fine and it does not affect your builds.

However, in this case it's not the metadata file, but the jar file itself:

The URL of the jar file is: https://repo1.maven.org/maven2/io/get-coursier/interface/1.0.19/interface-1.0.19.jar
SHA1 checksum from Maven: `e21790b550d98b24632512d49ab87b1be6a1faf2` (from https://repo1.maven.org/maven2/io/get-coursier/interface/1.0.19/interface-1.0.19.jar.sha1)
SHA1 checksum from Reposilite: `f8063085e867d78d9884baa764bd332a017452b1`

Why is the SHA1 different, and is there a way to remedy my issue?

### Reposilite version

3.x

### Relevant log output

```shell
[error]  http://--address-redacted--/maven/io/get-coursier/interface/1.0.19/interface-1.0.19.jar: wrong checksum: /home/hzwaal/.cache/coursier/v1/http/--redacted--/maven/io/get-coursier/interface/1.0.19/interface-1.0.19.jar (expected SHA-1 e21790b550d98b24632512d49ab87b1be6a1faf2 in /home/hzwaal/.cache/coursier/v1/--redacted--/maven/io/get-coursier/interface/1.0.19/interface-1.0.19.jar.sha1, got f8063085e867d78d9884baa764bd332a017452b1)
[warn] Project loading failed: (r)etry, (q)uit, (l)ast, or (i)gnore? (default: r)
```

**Comment by dzikoysk** [comment]
Hey, Reposilite 3.x accepts checksums from client, so it should work properly, because we're not generating any files at this moment. The FAQ entry you've mentioned was true for [Reposilite 2.x](https://v2.reposilite.com/docs/faq). 

Because we're talking about mirrored repository, are you sure that SHA1 extension is added to the list of allowed file types?

* https://reposilite.com/guide/mirrors#allowed-extensions

**Comment by hzwaal** [comment]
Hey, good to know that the FAQ entry is about 2.x. I missed that.

The .sha1 extension is an allowed file type in my setup, which it was by default. I didn't change anything there.

So my best guess now is that the Coursier downloader maybe includes more than just the file contents in the hash. In the end I've worked around the issue by manually writing the 'wrong' SHA1 in the cached .sha1 file of the Reposilite mirror repository. The Coursier downloader then no longer complains and works as expected.

Since the issue is probably in Coursier rather than in Reposilite, I'm closing the issue.

And thanks for all the work. If I decide on keeping Reposilite, I'll become a sponsor.

**Comment by dzikoysk** [comment]
Oh okay, I don't have much experience with Scala and I see this tool for the first time, but indeed it could be the issue. 

Our Scala user base is not big, so let me know if you'd find some other issues. Even if we won't be able to fix it in 3.x, I'm currently gathering feedback for 4.x here:

* https://github.com/dzikoysk/reposilite/issues/2005
