### ISSUE TITLE
Add a "WWW-Authenticate" header 

### ISSUE THREAD

**Issue by zyuiop** [dzikoysk/reposilite#211]
The Scala Build Tool (SBT) is compatible with maven, but it won't send any credentials to the server if it doesn't provide a "WWW-Authenticate" header, requesting the credentials.

It would be cool to return such header when publishing artifacts if the credentials are absent.

I already implemented it in a repo of mine, but it's a quick and dirty impl, see here: https://github.com/Polyjapan/reposilite/commit/1521d6944aa5d219bfb9d8e34a2751fdc37341dd

Thanks!

**Comment by dzikoysk** [comment]
It should be available in the next release, probably tomorrow :)

**Comment by dzikoysk** [comment]
2.8.3 has been released, Reposilite adds `www-authenticate` header for all 401 requests
