### ISSUE TITLE
When in debug mode, log all sql statements

### ISSUE THREAD

**Issue by solonovamax** [dzikoysk/reposilite#2119]
### Request details

Currently, debug mode will log all requests, but not all sql statements.
It would be nice if they could be logged as well.

I'm currently attempting to debug an issue with some sql stuff, and I had to make a custom build to get this. It would be nice to have this enabled with debug mode.

you can add a debug logger to a transaction using:
```kotlin
addLogger(StdOutSqlLogger)
```
this will log to stdout using the format:
```
SQL: [sql statement to be executed here]
```

Alternatively, if you want to implement a custom logger that uses your logging framework (bc ik you use a custom one), you can do so by copying the implementation from [`StdOutSqlLogger`](https://github.com/JetBrains/Exposed/blob/4a6e29827bbf126135b9e1226aaff1c9af71da02/exposed-core/src/main/kotlin/org/jetbrains/exposed/sql/SQLLog.kt#L21-L26):
```kotlin
object StdOutSqlLogger : SqlLogger {
    /** Prints a log message containing the string representation of a complete SQL statement. */
    override fun log(context: StatementContext, transaction: Transaction) {
        println("SQL: ${context.expandArgs(transaction)}")
    }
}
```

---

the reason I'm having to debug some issues is bc I went and deleted a bunch of shit with
```sql
DELETE FROM statistics_identifier WHERE identifier_id IN (SELECT identifier_id FROM statistics_resolved_identifier WHERE date = 1709874000000 OR date = 1709787600000 OR date = 1709960400000 OR date = 1709701200000);
DELETE FROM statistics_resolved_identifier WHERE date = 1709874000000 OR date = 1709787600000 OR date = 1709960400000 OR date = 1709701200000;
```
in order to remove some testing things that were making my stats out of proportion, but that's a whole other thing lol

**Comment by solonovamax** [comment]
It seems that you can add a logger to all transactions by doing the following:
```kotlin
// An example with current available settings and their defaults
val dbConfig = DatabaseConfig {
    sqlLogger = Slf4jSqlDebugLogger
    useNestedTransactions = false
    defaultFetchSize = null // unlimited
    defaultIsolationLevel = -1 // DB specific
    defaultRepetitionAttempts = 3
    warnLongQueriesDuration = null // no long query tracing
    maxEntitiesToStoreInCachePerEntity = Int.MAX_VALUE // unlimited 
    keepLoadedReferencesOutOfTransaction = false
}
// databaseConfig available on each connect/connectPool functions
val database = Database.connect(datasource, databaseConfig = databaseConfig)
```
see: [0.35.1 Release Notes](https://github.com/JetBrains/Exposed/blob/4a6e29827bbf126135b9e1226aaff1c9af71da02/CHANGELOG.md#0351)

**Comment by dzikoysk** [comment]
I don' think we need this :thinking: If you only care about a development mode, you can just comment out this line:

* https://github.com/dzikoysk/reposilite/blob/main/reposilite-backend/src/main/resources/tinylog.properties#L36

And you'll get all statements from Exposed in debug mode.

**Comment by solonovamax** [comment]
@dzikoysk it was more for diagnosing an issue

but it'd be nice to not have to recompile it in order to see the debug logs
