### ISSUE TITLE
Guide - Wrong folder name for static files

### ISSUE THREAD

**Issue by ntt77** [dzikoysk/reposilite#2145]
### What happened?

In the guide, section Static files, the document said that the 

> Reposilite creates public directory in workdir.

and 

> Using public directory you can implement frontend on your own. Because assets have lower priority, you have to disable frontend in the local configuration file:

However, when I created a folder name public/ and put my custom frontend, it didn't work
Instead, I found that the folder name static/ is created, and when I put to that folder, it works!

So, I request you to update the Guide, section Static files with that information.

### Reposilite version

3.x

**Comment by dzikoysk** [comment]
Thanks, fixed :ok_hand:
