### ISSUE TITLE
Implement Last-Modified response HTTP header

### ISSUE THREAD

**Issue by kili668** [dzikoysk/reposilite#2161]
### Request details

To test Reposilite, I use the docker image of it.

Now, I have made the following observation. When I download an artifact from the server using
**wget -N http://server:port/path/artifact.jar**
I get the warning message "_Last-modified header missing -- time-stamps turned off._" and
the timestamp of the downloaded file ist the current time.

I expected to have the timestamp when the file was created on Reposilite. In my current Repository (Archiva) it's working like this.

Please implement the Last-Modified response HTTP header in your server.

**Comment by dzikoysk** [comment]
Hey, done! It'll be available in 3.5.15 or in the nightly build that should be available in about an hour.

**Comment by kili668** [comment]
Thank you so much. It works as expected.
