### ISSUE TITLE
Reposilite shutdown automatically after a certain amount of time

### ISSUE THREAD

**Issue by sergiobelli** [dzikoysk/reposilite#2172]
### What happened?

Hi,
    i would like to provide a strange use case that happen to my reposilite installation every day.

I installed resposilite in my dev server to furnish a repo to my projects in development. Every morning I startup the reposilite system with the command : 
"java \
        -Xmx64M \
        -jar \
        -Dreposilite.port=8080 \
        /home/ec2-user/data/reposilite/reposilite-3.5.13-all.jar \
        --token admin:xxx"

Reposilite startup properly and I'm able to work without any kind of problem for the whole day.

Every evening, after I stopped my development session I see that Reposilite shutdown in automatically way... Take a look at the log belove. 

What I have to do in order to let Reposilite running forever?

Thank you for the support.
Bye

### Reposilite version

3.x

### Relevant log output

```shell
com.zaxxer.hikari.pool.HikariPool$PoolEntryCreator 2024-07-12 19:10:29.264 DEBUG | HikariPool-1 - Added connection org.sqlite.jdbc4.JDBC4Connection@10816101
com.zaxxer.hikari.pool.HikariPool$PoolEntryCreator 2024-07-12 19:40:00.829 DEBUG | HikariPool-1 - Added connection org.sqlite.jdbc4.JDBC4Connection@58047c7b
com.zaxxer.hikari.pool.HikariPool$PoolEntryCreator 2024-07-12 20:09:57.294 DEBUG | HikariPool-1 - Added connection org.sqlite.jdbc4.JDBC4Connection@387a16f3
com.zaxxer.hikari.pool.HikariPool$PoolEntryCreator 2024-07-12 20:39:42.498 DEBUG | HikariPool-1 - Added connection org.sqlite.jdbc4.JDBC4Connection@6a013d71
com.zaxxer.hikari.pool.HikariPool$PoolEntryCreator 2024-07-12 21:09:30.984 DEBUG | HikariPool-1 - Added connection org.sqlite.jdbc4.JDBC4Connection@203e54ca
com.zaxxer.hikari.pool.HikariPool$PoolEntryCreator 2024-07-12 21:39:18.246 DEBUG | HikariPool-1 - Added connection org.sqlite.jdbc4.JDBC4Connection@67538fcd
com.reposilite.journalist.slf4j.Slf4jLogger 2024-07-12 21:41:41.693 DEBUG | GET /geoserver/web/ from 120.92.12.14
com.reposilite.journalist.slf4j.Slf4jLogger 2024-07-12 21:41:41.694 DEBUG | FIND | Could not find file due to ErrorResponse(status=404, message=Repository geoserver not found)
com.reposilite.journalist.slf4j.Slf4jLogger 2024-07-12 21:45:42.436 DEBUG | GET /geoserver/web/ from 117.53.144.46
com.reposilite.journalist.slf4j.Slf4jLogger 2024-07-12 21:45:42.437 DEBUG | FIND | Could not find file due to ErrorResponse(status=404, message=Repository geoserver not found)
com.reposilite.journalist.slf4j.Slf4jLogger 2024-07-12 21:48:40.770 WARN | Interactive CLI is not available in current environment.
com.reposilite.journalist.slf4j.Slf4jLogger 2024-07-12 21:48:40.771 WARN | Solution for Docker users: https://docs.docker.com/engine/reference/run/#foreground
com.reposilite.journalist.slf4j.Slf4jLogger 2024-07-12 21:48:40.783 INFO | Shutting down 0.0.0.0::8080...
io.javalin.util.JavalinLogger 2024-07-12 21:48:40.784 INFO | Stopping Javalin ...
com.reposilite.journalist.slf4j.Slf4jLogger 2024-07-12 21:48:40.785 INFO | Server stopping...
org.eclipse.jetty.server.Server 2024-07-12 21:48:40.785 INFO | Stopped Server@2839e3c8{STOPPING}[11.0.20,sto=0]
org.eclipse.jetty.server.AbstractConnector 2024-07-12 21:48:40.789 INFO | Stopped ServerConnector@63f6bed1{HTTP/1.1, (http/1.1)}{0.0.0.0:8080}
org.eclipse.jetty.server.handler.ContextHandler 2024-07-12 21:48:40.796 INFO | Stopped o.e.j.s.ServletContextHandler@59a2388e{/,null,STOPPED}
io.javalin.util.JavalinLogger 2024-07-12 21:48:40.801 INFO | Javalin has stopped
com.reposilite.journalist.slf4j.Slf4jLogger 2024-07-12 21:48:40.802 INFO | Bye! Uptime: 13h 9s
```

**Comment by kili668** [comment]
Did you already try with either

**_nohup_** java -Xmx64M -Dreposilite.port=8080 -jar /home/ec2-user/data/reposilite/reposilite-3.5.13-all.jar --token admin:xxx

or

java -Xmx64M -Dreposilite.port=8080 -jar /home/ec2-user/data/reposilite/reposilite-3.5.13-all.jar --token admin:xxx **_&_**

This will start the process in the backgroud and when you leave the session it should not stop (except you shutdown your development environment).

**Comment by dzikoysk** [comment]
Just like @kili668 said, this is a problem with Reposilite being started in the session that is simply terminated when you're logging off. It's unrelated to Reposilite, just regular Linux process management.

Additionaly, you may also e.g.:
1. Run Reposilite in [a screen](https://linuxize.com/post/how-to-use-linux-screen/#starting-linux-screen)
2. Run Reposilite as [a service](https://reposilite.com/guide/systemd)
3. [Docker](https://reposilite.com/guide/docker)
