### ISSUE TITLE
How does one cache the entire Maven central repository?

### ISSUE THREAD

**Issue by abotelho-cbn** [dzikoysk/reposilite#2173]
### What happened?

When attempting to configure `https://repo.maven.apache.org/maven2/` as a mirror, like in documentation (https://reposilite.com/guide/mirrors) the console tells me:
`15:50:04.296 DEBUG | HttpRemoteClient | https://repo.maven.apache.org/maven2/maven-metadata.xml responded with 404 (Content-Type: text/html) `

When narrowing the mirror URL, like for example `https://repo.maven.apache.org/maven2/abbot/abbot`
It succeeds:
`15:44:42.152 DEBUG | HttpRemoteClient | https://repo.maven.apache.org/maven2/abbot/abbot/maven-metadata.xml responded with 200 (Content-Type: text/xml)`

![image](https://github.com/user-attachments/assets/67584676-5dad-491e-876a-3fd3d4714852)

Which begs the question: is the documentation incorrect? Or is the configuration demonstrated in documentation meant to work?

If it's not meant to work like the documentation, how can the entire Maven central repository be cached? Do i have to list every single repository within that domain? The way the tabs in the "Mirrored repositories" implies that you should only need one repository entry for an entire domain.

### Reposilite version

3.x

**Comment by dzikoysk** [comment]
The guide seems to be correct and the behaviour looks properly too. The URL you're trying to access does not point to any file:

* https://repo.maven.apache.org/maven2/maven-metadata.xml

![image](https://github.com/user-attachments/assets/3edce06d-e99a-4d28-9551-f09ba318daed)

So Reposilite is simply ignoring it. Whenever you'll request a valid file, it should work. For instance, the file you tried to request later:

![image](https://github.com/user-attachments/assets/14b9ff08-3908-44dd-a1e5-9e40d3c8351f)

**Comment by abotelho-cbn** [comment]
I think I understand how the proxy mechanism works now.

When I was pointing it to a repository containing a maven-metadata.xml file, it *appeared* to be that the mirroring mechanism was prefetching maven-metadata.xml. I wasn't making any requests to my Reposilite instance yet.

The console entry:
`15:50:04.296 DEBUG | HttpRemoteClient | https://repo.maven.apache.org/maven2/maven-metadata.xml responded with 404 (Content-Type: text/html)`

Gave me the impression the mirroring mechanism was failing entirely, which is why my repository wasn't being populated at all.
