### ISSUE TITLE
Support Ivy wildcard version resolving / list directory via Maven Repository Endpoint

### ISSUE THREAD

**Issue by isaacgale** [dzikoysk/reposilite#2176]
### Request details

I'm currently trying to replace our Nexus 2 server with a Reposilite server and for the most part it is working fine. Except when it comes to Ivy resolving wildcard versions eg 1.0.+ or 'latest.intergration'. The problem is reposilite returns 404s when trying to request a directory.

Ivy and Gradle (when using Ivy repos) actually expect to get a text/html file with a list of hrefs it can parse to get the versions and not a maven-metadata.xml. (Apache Server style)

See it documented here: [https://docs.gradle.org/current/userguide/dependency_resolution.html#discovering_versions](https://docs.gradle.org/current/userguide/dependency_resolution.html#discovering_versions)

See the implementations here:
[https://github.com/gradle/gradle/blob/master/platforms/software/resources-http/src/main/java/org/gradle/internal/resource/transport/http/ApacheDirectoryListingParser.java](https://github.com/gradle/gradle/blob/master/platforms/software/resources-http/src/main/java/org/gradle/internal/resource/transport/http/ApacheDirectoryListingParser.java)

[https://github.com/apache/ant-ivy/blob/master/src/java/org/apache/ivy/plugins/resolver/util/ApacheHttpURLLister.java](https://github.com/apache/ant-ivy/blob/master/src/java/org/apache/ivy/plugins/resolver/util/ApacheHttpURLLister.java)

I've hacked together a temporary solution here (don't be too harsh I don't know Kotlin or any of these frameworks) where I just use the kotlinx HTML DSL to build the file on the fly. [https://github.com/isaacgale/reposilite/blob/ivy-directory-listing-proto/reposilite-backend/src/main/kotlin/com/reposilite/maven/infrastructure/MavenEndpoints.kt](https://github.com/isaacgale/reposilite/blob/ivy-directory-listing-proto/reposilite-backend/src/main/kotlin/com/reposilite/maven/infrastructure/MavenEndpoints.kt)

Could this feature be added properly to v3 and v4?

Thanks
Isaac

**Comment by dzikoysk** [comment]
Hey, Ivy is indeed not supported. It's a bit weird format tho, but if that's all we need, then I think that's okay :thinking:

**Comment by isaacgale** [comment]
I can confirm everything else with Ivy works fine in Reposilite, so it would be awesome if this could be added.

**Comment by dzikoysk** [comment]
I've added some extra styling to the index, so it's actually usable when accessed accidentaly without UI:

![image](https://github.com/user-attachments/assets/0c8361bc-2a56-4b06-a8a5-0fcb99e81b1a)

Let me know if Ivy interprets it correctly - I've noticed in some examples that it's able to extract values from lists or even tables, so I hope it'll be compatible too.

**Comment by isaacgale** [comment]
@dzikoysk Hi thanks for adding this feature sadly it's not working.

The ant-ivy regex logic expects " in the HTML and will not work with '. I have made some changes to the DirectoryIndexPage.kt file [here](https://github.com/dzikoysk/reposilite/compare/main...isaacgale:reposilite:main#diff-8877c23b60e36d9c00c6ff2806268b445e8514e7ce381439dbbb8d1f07b6bf58) that now have it working for me, if you could incorporate these changes into the next release that would be awesome. Cheers Isaac.

**Comment by dzikoysk** [comment]
Thanks for feedback. You've also added a leading `.` to the link, is it the only way to make it work? :thinking: I'm asking, because it's actually translated to incorrect URL by the browser if trailing slash is missing:

* `http://localhost:8080/releases/com/reposilite` + `./1.0.0` = `http://localhost:8080/releases/com/1.0.0`
* `http://localhost:8080/releases/com/reposilite/ + `./1.0.0` = `http://localhost:8080/releases/com/reposilite/1.0.0`

We can also set base tag, but I'm not sure if it won't be picked up by Ivy :thinking:

**Comment by dzikoysk** [comment]
Now we have something like that:

```html
<!DOCTYPE html>
<html lang='en'>
    <head>
        <title>Index of /releases/com/reposilite</title>
        <meta charset='utf-8'>
        <base href='/releases/com/reposilite/'>
        <style>
        li {
            padding: 2px 10px;
        }
        .back::marker {
            content: '🔙';
        }
        .directory::marker {
            content: '📁';
        }
        .file::marker {
            content: '📄';
        }
        </style>
    </head>
    <body>
        <h1>Index of /releases/com/reposilite</h1>
        <ul>
            <li class='back'>
                <a href='/releases/com'>Parent Directory</a>
            </li>
            <li class="directory"><a href="./plugin/">plugin/</a></li><li class="directory"><a href="./test/">test/</a></li>
        </ul>
    </body>
</html>
```

* `<base href='<base-path'>` - Base path for browsers to handle both scenarios properly + it uses `'` quotes, so it should be ignored by Ivy
* `<a href="./<directory">` - for Ivy

**Comment by isaacgale** [comment]
The main issue in Ivy is the regex here in this class in the Ivy code: [https://github.com/apache/ant-ivy/blob/master/src/java/org/apache/ivy/util/url/ApacheURLLister.java](https://github.com/apache/ant-ivy/blob/master/src/java/org/apache/ivy/util/url/ApacheURLLister.java) it expects the href to contain " not single '.

I retested the changes I made just replacing the single quotes to doubles and adding the trailing '/' (which is needed if you look at the Ivy class above) and leaving the base path as you had it see [here](https://github.com/dzikoysk/reposilite/compare/main...isaacgale:reposilite:main#diff-8877c23b60e36d9c00c6ff2806268b445e8514e7ce381439dbbb8d1f07b6bf58) 

This works with Ivy too.

**Comment by dzikoysk** [comment]
Here's the commit I pushed before my comment, not sure if you've seen this:

* https://github.com/dzikoysk/reposilite/commit/325eb751318986af3c87c93e4ba49487729b8022

It uses double quotes, so the generated HTML above is already available in our nightly build, so I'd say it might be worth testing :crossed_fingers:

**Comment by isaacgale** [comment]
I can confirm reposilite-3.5.16-20240820.185709-1-all.jar it working as I expect. Thanks for putting this in.

**Comment by dzikoysk** [comment]
Great! Thanks for your feedback, I'll probably release it as 3.5.16 tomorrow :)
