### ISSUE TITLE
Remove nanohttp

### ISSUE THREAD

**Issue by dzikoysk** [dzikoysk/reposilite#22]

**Comment by ruzkant** [comment]
What do you have in mind to replace nanohttpd with?

**Comment by dzikoysk** [comment]
I've made a research and the strong candidate for replacement is  http://sparkjava.com/ at this moment. It is the lightest solutions, e.g. https://craftsmen.nl/memory-usage-6-popular-rest-server-frameworks-compared/. 

I'm also considering micronaut/quarkus and their native images where memory footprint could be less than 10mb.

**Comment by ruzkant** [comment]
I am keenly watching micronaut with the compile time dependency injection, but I haven't played with it directly. 

Of course you can always go low down to netty. 

Is there some place I can ask you some questions regarding where you're going with this in future?

For example my number one other thing I would like to see is: "Proxy for the specified remote repositories" whereas things like an admin panel is not important to me. For me it's about a light low RAM system I can host on a cheap VM and all my management needs are met in configuration files and file system management. Most of the time I don't interact with artifactory, and these tools just get more RAM hungry with every new release.

**Comment by dzikoysk** [comment]
I use this project as my maven repository for 3 years already. I had plans to support maven in [reposilite](https://github.com/panda-lang/reposilite) and it is why this repository was marked as abandoned for a while. I've changed my goals lately and it's why I reactivated nanomaven.

The main priority is to reduce memory footprint ofc and improve overall quality of code. The problem with micronaut is that if you are not using native images, the memory usage of application on JVM is much higher, e.g.: (IDLE after startup)
* micronaut JVM *~200MB >*
* micronaut native image *40MB*
* spark *~30MB*
* nanomaven 2.2.0 *24MB*


![obraz](https://user-images.githubusercontent.com/4235722/82048905-bf3e4e80-96b5-11ea-9670-2f891ab08158.png)
*https://medium.com/graalvm/lightweight-cloud-native-java-applications-35d56bc45673*

I also think I'll focus on recording statistics in a next release and then we will see.

**Comment by ruzkant** [comment]
Ok thanks for the feedback

**Comment by dzikoysk** [comment]
[**Rejected**] Candidate: [reactor-netty](https://github.com/reactor/reactor-netty)

Issues:
* Lack of standardized API for multipart files  [GH-3](https://github.com/reactor/reactor-netty/issues/3)
* Protocol issues [HttpVersion.java#L64](https://github.com/netty/netty/blob/0cde4d9cb4d19ddc0ecafc5be7c5f7c781a1f6e9/codec-http/src/main/java/io/netty/handler/codec/http/HttpVersion.java#L64)
* Random timeouts and overall poor quality

**Comment by dzikoysk** [comment]
**[Rejected]** Candidate: [spark](https://github.com/perwendel/spark)

Issues:
* Uncertain [GH-1102](https://github.com/perwendel/spark/issues/1102)
* Higher memory footprint
* Wildcard issues [GH-945](https://github.com/perwendel/spark/issues/945)
* Lack of reactive-like API

**Comment by dzikoysk** [comment]
**Candidate: ** [ktor](https://github.com/ktorio/ktor)

Issues:
* Focused on Kotlin
* Dirty [ktor :: uploads](https://ktor.io/servers/uploads.html)
* ~needs investigation~

**Comment by dzikoysk** [comment]
[Currently tested] Candidate: [javalin](https://github.com/tipsy/javalin)

Issues:
* Higher memory footprint (~ Jetty)

**Comment by dzikoysk** [comment]
Javalin :)

* https://github.com/dzikoysk/reposilite/blob/c1089d347bd3021f24bf789a485c3071c343c567/reposilite-backend/build.gradle.kts#L94
