### ISSUE TITLE
Cannot upload file undefined

### ISSUE THREAD

**Issue by Desoroxxx** [dzikoysk/reposilite#2225]
### What happened?

![image](https://github.com/user-attachments/assets/1e63a906-f015-4b6a-be43-9acf53d988a4)

Running in a VPS, I could upload stuff before, but now everything puts the same error

### Reposilite version

3.x

### Relevant log output

```shell
20:26:55.128 DEBUG | GET /dev/maven-metadata.xml from 172.17.0.1

20:26:55.128 DEBUG | GET /api/maven/details/dev from 172.17.0.1

20:26:55.131 DEBUG | Prioritizing mirror repository for 'maven-metadata.xml'

20:26:55.133 DEBUG | FIND | Could not find file due to ErrorResponse(status=404, message=File not found)

20:26:55.174 DEBUG | GET /api/maven/details/ from 172.17.0.1

20:26:55.269 DEBUG | GET /maven-metadata.xml from 172.17.0.1

20:26:55.269 DEBUG | GET /api/maven/details/dev from 172.17.0.1

20:26:55.308 DEBUG | GET /api/maven/details/ from 172.17.0.1

20:26:56.301 DEBUG | GET /api/maven/details/dev from 172.17.0.1

20:26:56.305 DEBUG | GET /dev/maven-metadata.xml from 172.17.0.1

20:26:56.305 DEBUG | Prioritizing mirror repository for 'maven-metadata.xml'

20:26:56.306 DEBUG | FIND | Could not find file due to ErrorResponse(status=404, message=File not found)

20:26:56.433 DEBUG | GET /api/maven/details/dev from 172.17.0.1

20:26:56.440 DEBUG | GET /maven-metadata.xml from 172.17.0.1

20:26:56.569 DEBUG | GET /api/maven/details/dev from 172.17.0.1
```

**Comment by Desoroxxx** [comment]
![image](https://github.com/user-attachments/assets/4a344c43-a2b3-4458-babf-3a7fbe38ff0a)
Same things happen if I use Firefox (Previously chromium)

**Comment by dzikoysk** [comment]
You've received [413 error](https://developer.mozilla.org/en-US/docs/Web/HTTP/Status/413) - it indicates that the content of the uploaded file was too large. Are you sure this file was within the limit that is set on the reverse proxy service? (like nginx)

**Comment by Desoroxxx** [comment]
Not sure would need to investigate thanks, it did not cross my mind that this was a HTTP response code
