### ISSUE TITLE
Add support for Major and Major.Minor Docker tags

### ISSUE THREAD

**Issue by kirbylink** [dzikoysk/reposilite#2282]
### Request details

**Problem Statement**  
Currently, the Docker images published for Reposilite are tagged only with `latest` and the full version (e.g., `3.5.19`). While this works for many use cases, it can make managing updates more challenging for users who want to:
- Restrict updates to a specific major version (e.g., `3.x`) to avoid breaking changes.
- Apply updates only within a specific minor version (e.g., `3.5.x`) for added stability.

This lack of additional tags can lead to either using the full version tag (requiring frequent manual updates) or relying on `latest`, which carries the risk of breaking changes.

**Proposed Solution**  
Enhance the tagging process for Docker images by adding the following additional tags:
- `Major` (e.g., `3`)
- `Major.Minor` (e.g., `3.5`)

These tags would complement the existing `latest` and full release tags, giving users more flexibility to manage updates in their environments.

**Benefits**  
- Users can opt-in to update strategies that better suit their requirements:
  - Use the `Major` tag to stay on the latest version within a major release.
  - Use the `Major.Minor` tag for stability within a minor release series.
- Reduced risk of unexpected breaking changes when relying on the `latest` tag.

**Implementation Details**  
In the `docker` job of the GitHub Actions workflow, the additional tags can be generated by extracting the `Major` and `Minor` parts of the version (e.g., from a variable or computed from the full version). These tags would then be passed to the `docker/build-push-action` step alongside the existing tags.

**Additional Context**  
I am happy to open a PR to implement this feature, as I already have a working solution. Please let me know if this aligns with the goals of the project or if any adjustments are needed before proceeding.

**Comment by dzikoysk** [comment]
I think it'd be a great improvement, feel free to submit the PR then :shipit:
