### ISSUE TITLE
Organization Logo and Descriptions in Frontend do not update

### ISSUE THREAD

**Issue by DevJoey** [dzikoysk/reposilite#2290]
### What happened?

I tried to set my project icon and some descriptions in the Settings/Frontend tab. after saving it does not show up. Cache cleared and so on also dont solve the problem.

### Reposilite version

3.x

**Comment by DevJoey** [comment]
Edit: It updates but it takes some time.

Restarted nginx
Cleared CloudFlare cache
Using inkognito mode in browser

IDK if there is some setting in eg. nginx or else to optimize that? But seems not a bug from reposilite so i think this can be closed

**Comment by dzikoysk** [comment]
It's most likely caused by aggressive Cloudflare's caching policy - enabling development mode within an incognito tab should help in the future. Anyway, that's purely cosmetic, so you shouldn't really bother tbh 🙂‍↕️
