### ISSUE TITLE
Support authorization through the browser-side pop-up

### ISSUE THREAD

**Issue by Sir-Cryptic** [dzikoysk/reposilite#240]
I set up /snapshots as private repository and created an access token for my teamcity server with access to /snapshots.
Works as intended.

Direct access to <url>/snapshots displays an auth pop-up with username and password. 
The alias and token used by maven are not working there

A separate access token listed as manager token in the configuration doesn't work either.

Am I doing anything wrong?

Access to <url>/dashboard works just fine with the same credentials

Reposilite version 2.8.4

**Comment by dzikoysk** [comment]
You should be able to login using credentials on `domain.com/dashboard/snapshot`. Do you have any errors in CLI or in DevTools console?

**Comment by Sir-Cryptic** [comment]
Yes. As I said dashboard login works. Or is this the intended way? That I can only see private repositories if I do the login on /dashboard first? Direct access to /snapshots is therefore not possible?

It this is true, then why the auth pop-up from the browser. This could potentially confuse people. Like it did to me

**Comment by dzikoysk** [comment]
Oh, I didn't understand at first - you're talking about this browser-side pop-up 😅 No, it is not supported, it shows up, because Reposilite returns unauthorized request which is required by some tools like e.g. SBT.

By the way, what's your browser?

**Comment by Sir-Cryptic** [comment]
That's exactly what I thought. Maybe 403 Forbidden would be handled better by browsers.

I'm currently using Chrome on Windows

**Comment by dzikoysk** [comment]
I'm not able to that, some tools strictly requires this status code. I may try to support logging through this pop-up 🤔

**Comment by dzikoysk** [comment]
After the investigation I'm unfortunately not able to support this pop-up. 

* I can't hide it, it's always displayed by the browser for `401 status code + www-authenticate` which are required by the SBT #211 
* I can't support authentication through this, because frontend is not able to get current headers. It would require to hardcode auth credentials in page source and it is just bad.
