### ISSUE TITLE
CLI does not work

### ISSUE THREAD

**Issue by MaryWeeb** [dzikoysk/reposilite#241]
When trying to access the CLI, I get no responses back from the server, with the following in the browser logs:

![image](https://user-images.githubusercontent.com/16361449/92611611-404ed080-f2b9-11ea-97ae-209c72a44944.png)

**Comment by dzikoysk** [comment]
Since 2.7.4, Reposilite uses a new implementation of CLI authorization. What's your version?

**Comment by MaryWeeb** [comment]
2.6.1-1, the latest on AUR.

**Comment by dzikoysk** [comment]
I didn't publish any version of Reposilite on AUR, so you're probably using some kind of unofficial distribution (I guess this: https://aur.archlinux.org/packages/reposilite/)

Use latest version of Reposilite and it shouldwork :)

**Comment by MaryWeeb** [comment]
I'm getting an Error 400: 
![image](https://user-images.githubusercontent.com/16361449/92747652-b53b0c80-f384-11ea-8d04-75c109a7d018.png)
I'm assuming this is probably because of nginx, but I have no clue how to forward only wss and not http on the same route.

**Comment by dzikoysk** [comment]
Make sure you properly handle `Upgrade` and `Connection` headers, just like that: https://stackoverflow.com/a/42493289/3426515

**Comment by MaryWeeb** [comment]
That's what I added and I reloaded nginx, but no success...

**Comment by dzikoysk** [comment]
So it looks like you're trying to forward secured websocket connection into a non-secured one. 

If you're using HTTPS, Reposilite will try to connect to WSS: https://github.com/dzikoysk/reposilite/blob/bfb6fa0e61e77226edabb6d12466dbb439741722/reposilite-frontend/src/views/dashboard/Cli.vue#L43

~ https://stackoverflow.com/a/51973761/3426515
