### ISSUE TITLE
Upload in UI not working

### ISSUE THREAD

**Issue by heineson** [dzikoysk/reposilite#244]
Hi!

I am trying out Reposilite for my private repo as a replacement for Archiva, but I can't get it to accept artifacts uploaded through the UI. When I have clicked "upload" in the form after entering all info, the page simply reloads with an empty form. No status message, nothing (perhaps this is how it should look though). The problem is that nothing is added to the repository, and if I check the repository folder on the server it is empty too. The only thing I can see which indicates some kind of problem is this log in the browser console:
`Form contains a file input, but is missing method=POST and enctype=multipart/form-data on the form.  The file will not be sent.`

Reposilite version: 2.8.4, running in Docker using the image `dzikoysk/reposilite`
Browser: Firefox 80.0.1

**Comment by dzikoysk** [comment]
Yeah, looks like a bug on a 2.8.x

**Comment by dzikoysk** [comment]
2.8.5 has been released: https://github.com/dzikoysk/reposilite/releases/tag/2.8.5
You have to wait a couple of minutes for a docker image, its CI is kinda slow 😬

**Comment by heineson** [comment]
Works like a charm, thanks!
