### ISSUE TITLE
Can multiple reposilite instances share the same data volume ?

### ISSUE THREAD

**Issue by xfabre** [dzikoysk/reposilite#251]
Hi there, nice project.
My question is about HA situation having kubernetes deployment in mind where we would like to have many reposilite pods (thus containers) accessing concurrently to the same data volume.
Is it something somewhat supported or by design it would not work due to potential conflicting access to the same files?
Thank you.

**Comment by dzikoysk** [comment]
Thanks :) I am not familiar with kubernetes, but I think it should work. Reposilite serves files directly from disk, so it mostly depends on the available within volume IO.

**Comment by xfabre** [comment]
Thanks for your quick answer.
Perhaps I clarify my question then, would concurrent mvn deploy on the same maven coordinates taken simultaneously by two reposilite instances sharing a same data volume would cause conflicting writes? Or maybe that's just the last deploy who win?
BTW perhaps the situation is not that different from a single instance handling 2 concurrent requests, how is it handled?

**Comment by dzikoysk** [comment]
Well, concurrent deploy of the same file is not really supported at this moment. I may add a locking mechanism using `FileLock` 🤔

**Comment by dzikoysk** [comment]
Ok, I think that all of these changes in previous days should make it possible to use Reposilite 2.9 in that way. The only limitation is that you can not create user accounts that are synchronized between instances. To add a new token you have to restart other instances, because tokens.dat file is loaded only at startup.

**Comment by sammy-da** [comment]
Hello 👋 

I'd lack some clarification on this.

Does this mean i can run multiple instances of reposilite that point to the same data volume now?
(in kuberentes i'd only have to bump the replicas to like 2 or 3 or something, right?)

i'm using 3.x version, and I don't need to ever upload artifacts, i only use reposilite for mirroring / caching (`store: true`)
