### ISSUE TITLE
How can I access to the CLI the first time

### ISSUE THREAD

**Issue by quitusl** [dzikoysk/reposilite#262]
How can I access to the CLI the first time? what is the default username and password ? 

![image](https://user-images.githubusercontent.com/24661740/93828127-1b574780-fc41-11ea-8da5-31cd3781203b.png)

**Comment by dzikoysk** [comment]
Reposilite does not create default user because of the security issues. You have to generate your first access token through the CLI. You may find some useful articles about setting up the Reposilite in the publications section:

* https://github.com/dzikoysk/reposilite#publications

Good luck :)

**Comment by quitusl** [comment]
Thanks for your quick response. But it is not clear to me (reading all the documentation) how to generate the token for the first time. I understand that I should run this command **keygen / admin** (for example), but I do not have access to the application CLI.

**Comment by dzikoysk** [comment]
How do you launch the application? You should be able to type commands in your system's terminal where you've launched it.

**Comment by vrozkovec** [comment]
FYI this was not clear to me either that I can just use the terminal and only by accident I've found out. I think that simple notice in the authorization section where you talk about generating tokens would do wonders :)

**Comment by dzikoysk** [comment]
Sounds like a good idea considering the reactions, thanks for the reply ❤️

**Comment by jflamy** [comment]
I never understood that the java program was waiting for input.  Most web servers don't sit waiting for commands !

**Comment by EverNife** [comment]
Yep, two years later and here was me with the same question :D
When seeing the default startup text i had the same though.

> I never understood that the java program was waiting for input. Most web servers don't sit waiting for commands !

I would suggest adding one more log line, something like:

## ~~ Startup Done! For help, type "help" or "?"

**Comment by dzikoysk** [comment]
Would you like to submit a PR? :)

**Comment by EverNife** [comment]
Done at https://github.com/dzikoysk/reposilite/pull/1870
