### ISSUE TITLE
UI: display issue with a lot of files

### ISSUE THREAD

**Issue by utarwyn** [dzikoysk/reposilite#265]
Hello, I use your tool everyday to store a large amount of files for my project and it works pretty well!

But, there is a bug when displaying filenames in the UI, the header is not visible and I can't seen all my files (the top and bottom of the page are cut off). **Is this a known bug? Maybe a flex problem on the main container?**

Thank you in advance!

**Reposilite version:** latest (2.9.0-dev)
**Example:**
![screenshot](https://user-images.githubusercontent.com/9255967/94057825-73788000-fde0-11ea-8f0a-8f7788d2ea81.jpg)
**Flex classes that may cause the issue:**
![image](https://user-images.githubusercontent.com/9255967/94058030-cce0af00-fde0-11ea-936d-b190f0d7c579.png)

**Comment by dzikoysk** [comment]
Thanks for report! Yeah, I'm aware of this problem, I've also experienced this issue in my public repository. I'll try to deliver a fix to 2.9 release.

**Comment by utarwyn** [comment]
Thank you for the quick fix, much appreciated! :+1:

**Comment by dzikoysk** [comment]
Unfortunately, I'm not able to release it as 2.8.6 due to some breaking changes on master since 2.8.5 :<
