### ISSUE TITLE
basePath does not affect routing?

### ISSUE THREAD

**Issue by thvitt** [dzikoysk/reposilite#277]
I have configured a base path in the configuration:
```
basePath: /repo
```
However, this doesn’t really work. GETting `/repo/` returns an HTML page that contains a `<script src="/repo/js/app.js"></script>` as would be expected. 

However, 
* The HTML page for `/repo/` contains `window.REPOSILITE_MESSAGE = 'Repository repo not found'`
* `/repo/js/app.js` returns an HTML page with `window.REPOSILITE_MESSAGE = 'Unsupported request'`
* `/js/app.js` does return the javascript instead

**Comment by dzikoysk** [comment]
The base path is dedicated for multi-app sites behind proxy, e.g.:

```
nginx:
  `/` -> some app
  '/repo' -> reposilite instance
``` 

Do you use it this way or you've just launched Reposilite with custom base path assigned to `/`? 🤔

**Comment by thvitt** [comment]
Yes, a multi-app site behind a reverse proxy is why I tried to configure basePath. I’ve tried to proxy /repo to http://localhost:8765/repo with `basePath: /repo` (with reposilite on port 8765).

I also tried to proxy /repo/js -> /js separately and /repo/api -> /api separately, this loads the javascript but still tries to pick up `repo` as repository name.

**Comment by dzikoysk** [comment]
Could you try to use 2.8.5 to check if it is related only to 2.9.x?

**Comment by thvitt** [comment]
appears to be the same behaviour with 2.8.5

**Comment by dzikoysk** [comment]
Ok, first of all set the base path to `/repo/` instead of `/repo`, I didn't notic it. I have to mention it in the configuration. Everything seems to work fine with the following configuration:

![image](https://user-images.githubusercontent.com/4235722/95114496-54fd7780-0744-11eb-999a-348796c623b6.png)

**Comment by thvitt** [comment]
Ah, I see. After configuring `basePath: /repo/` and proxying :80/repo to :[reposilite]/ it works fine. Besides the missing `/` my mistake was to not rewrite the base path.

The only remaining minor glitch seems to be that the admin page for the root (i.e. http://.../repo/dashboard/) says `repository repo not found` (don’t need this anyway). The admin pages in the actual repositories work fine.

![image](https://user-images.githubusercontent.com/1906208/95180922-e1e71600-07c2-11eb-9725-4a032ce749a0.png)


Many thanks for your help!

**Comment by dzikoysk** [comment]
Well, the `basePath` is a little tricky to support, especially with Vue which is not really suitable for such an usage and it requires some dirty hacks. Most of the applications with custom base path support are rendered SSR, but the `reposilite-frontend` is just a standalone web app so yeah, it has some glitches. The preferred way of setting it up will be always dedicated domain like e.g. `repo.domain.com`.

Anyway, I'll mark it as a bug. I didn't check the custom base path support for a while, so the review might be a good idea.

**Comment by johnny-bui** [comment]
Do I need a reversPoxy to use basePath? I run reposilite with 

```
port: 8888
basePath: /repo/
```

but I got 404 for the HTTP request `http://localhost:8888/base/js/app.js`

**Comment by dzikoysk** [comment]
Yes, that's like a main idea of this feature - to work with reverse proxy so you can host multiple apps under the same domain. Anyway it's always dirty, so if possible, I'd recommend using just a dedicated subdomain

**Comment by johnny-bui** [comment]
I wish I has a dedicated subdomain. I have only a server, I cannot install a revers proxy, the basePath / is also used for other webpage. I think its time to ask admin for a new domain.

**Comment by johnny-bui** [comment]
Yep, Port `:8888` is used for git-Repo. I think I ask for a new port for Reposilite, for example `:8880/` and let it map to `:443/repo`. Will revers proxy https also work with Apache https server? I don't see it in document.

**Comment by dzikoysk** [comment]
If possible, go ask for subdomain, if it's not an option, then you need a new port at least. Not sure about Apache, I never used this, should be possible, Reposilite is just another regular http service.

**Comment by WithoutAName25** [comment]
I have a base path and I use Apache as reverse proxy. If you need help I can help you later.
