### ISSUE TITLE
Support authentication to access private project

### ISSUE THREAD

**Issue by vincent732** [dzikoysk/reposilite#294]
Hello everyone,

I hide my project using dot in front of the project name for example **.private** and I upload the files inside private folder.
Then I try to access it inside **dashboard** -> **Index** tab, then it asks me the to enter password and username.
Entering the alias/token that is generated from keygen with **keygen /private m** seems not work to access it.
Does reposilite support authentication to access private project?

**Comment by dzikoysk** [comment]
You should be able to login into the dashboard, but you should not be able to see the content of private repository in file viewer. I've just checked the source and it is a bug. Thanks for reporting this.
