### ISSUE TITLE
REST API for commands

### ISSUE THREAD

**Issue by kaosko** [dzikoysk/reposilite#320]
Would be great if you could issue the same CLI commands via a rest api.  Now it seems the only rest api is for fetching info about repos and artifacts.

**Comment by dzikoysk** [comment]
Someone mentioned it in the past as far as I remember. Probably you'd like to  use it locally to invoke commands without direct access to CLI?

**Comment by kaosko** [comment]
The CLI is great. However, we have a use case where we'd like to create customer specific access tokens (i.e. lots of them) and the REST api would make it easier to create and manage them programmatically.

**Comment by dzikoysk** [comment]
I think it could be implemented with #268. I'll try to find some time next weekend to take a look at this.

**Comment by kaosko** [comment]
Thanks, appreciated!

**Comment by dzikoysk** [comment]
Using [2.9.7](https://github.com/dzikoysk/reposilite/releases/tag/2.9.7) you should be able to execute commands through the api. Take a look at:

* https://reposilite.com/docs/cli#remote-execution
