### ISSUE TITLE
How to access CLI when deploying with docker

### ISSUE THREAD

**Issue by affanshahid** [dzikoysk/reposilite#321]
How do I go about generating a token when running with docker? Inside the container "keygen" is not a known command

**Comment by dzikoysk** [comment]
Do you launch Reposilite in interactive mode with terminal?

![image](https://user-images.githubusercontent.com/4235722/102259842-e9881100-3f0f-11eb-9e1a-d6d7264a0126.png)

**Comment by affanshahid** [comment]
Ah missed that! Thanks!

**Comment by dzikoysk** [comment]
@agelosnm take a look at https://reposilite.com/docs/docker
