### ISSUE TITLE
Wrong maven-metadata hash in snapshots

### ISSUE THREAD

**Issue by AlessioDP** [dzikoysk/reposilite#327]
I am not able to generate a correct maven-metadata.xml hash in snapshot repositories.

Its possible to see this behaviour in the demo repository (https://repo.panda-lang.org/snapshots/org/panda-lang/nanomaven/2.1.2-SNAPSHOT) by downloading `maven-metadata.xml` and generating its sha1 hash  then comparing to the wrong one in `maven-metadata.xml.sha1`.

Real sha1 hash of `maven-metadata.xml`: `B38F8EF35B8EE7235C20E056F39D54E2A794B1D4`
Calculated sha1 hash in repository: `59550559e053f640b3157024a6c302bf68fb951c`

**Comment by dzikoysk** [comment]
Reposilite uses server-side hash generation to avoid a couple of problems. You should be able to perform every Maven task, the only expected side effect of this should be a client-side warning.

Did you experience other problems?

**Comment by AlessioDP** [comment]
No, only the client side warning. Is it possible to prevent that?

**Comment by dzikoysk** [comment]
Not really, but it is intended behavior, and it looks strange only without having a context and explanation. I've mentioned it in a FAQ section:

* https://reposilite.com/docs/faq

**Comment by AlessioDP** [comment]
Sorry didn't see that in FAQ.

But why in server-side the hash doesn't match either? By downloading both files and checking the hash of the file + the one stored should be correct right?

**Comment by dzikoysk** [comment]
I don't remember the specification, but in theory - yes. I've supported this in the past, and I was planning to support it by the way in the current implementation, but I didn't have time for it due to the cosmetic aspect of this issue.
