### ISSUE TITLE
Web cli through dashboard not working

### ISSUE THREAD

**Issue by Palomox** [dzikoysk/reposilite#346]
Hi,
I just finished installing and configuring reposilite, created my first admin user, and entered the dashboard. I found the webCLI doesn't work, there is no error in the logs (I have set ``debugEnabled: true``), just this 2 errors in the dashboard itself:
![imagen](https://user-images.githubusercontent.com/48994550/105880806-1269ee80-6004-11eb-9b5d-f64ed9c59eba.png)
My token has 'm' permissions. I've also tried setting the token alias in the config in the ``managers`` block but it gets deleted every time I start the application.
Thanks in advance,
Palomox.

**Comment by dzikoysk** [comment]
Hey, do you use some kind of proxy service like nginx? Also, please attach some logs from cli and full error from browser console :)

**Comment by Palomox** [comment]
Yes I use nginx, this is its config:
```nginx
upstream reposilite{
  server serverhostname:8081; # reposilite ip and port
}
server {                                                                                                                                                   
        server_name domain;                                                                                                                                    
        listen 80;                                                                                                                                                
        listen [::]:80;                                                                                                                                           
        access_log /var/log/nginx/reverse-access.log;                                                                                                             
        error_log /var/log/nginx/reverse-error.log;                                                                                                               
        location / {
                proxy_pass http://reposilite;
              proxy_set_header   Host              $host;
              proxy_set_header   X-Real-IP         $remote_addr;
              proxy_set_header   X-Forwarded-For   $proxy_add_x_forwarded_for;
              proxy_set_header   X-Forwarded-Proto $scheme;
              proxy_set_header Upgrade $http_upgrade;
              proxy_set_header Connection "upgrade";   
        }                                                                                                                                                              
} 
```
I also use cloudflare with a proxied record.

This is the error at the browser console, which makes me think the error is probably on my side
![imagen](https://user-images.githubusercontent.com/48994550/105911033-02650580-602a-11eb-9562-5a53c56cef69.png)
And this is the error on the get request:
![imagen](https://user-images.githubusercontent.com/48994550/105912301-8b307100-602b-11eb-8c7e-0b6413cdc31f.png)


There is no error at the logs (even with debug enabled). This is the line that gets printed in log.txt when I open the cli 
``22:59:39.892 INFO | LOOKUP /dashboard/cli from 69.42.05.00, 2400:cb00:40:1024::bc72:6eb5``
If any more details are needed, just tell me and I'll be happy to send them.

**Comment by dzikoysk** [comment]
Well, it is definitely a problem with configuration of websocket connection in nginx/cloudflare, because Reposilite does not even receive a connection. I guess I might be associated with SSL, take a look at: https://stackoverflow.com/a/51973761/3426515

**Comment by Palomox** [comment]
It was a problem of my nginx configuration not liking websockets. For possible future readers, I solved it it by changing my nginx config for that domain to this: 
```nginx
map $http_upgrade $connection_upgrade {
        default upgrade;
        '' close;
}

upstream reposilite{
  server domain:8081; # reposilite ip and port
}
server {                                                                                                                                                   
        server_name domain;                                                                                                                                    
        listen 80;                                                                                                                                                
        listen [::]:80;                                                                                                                                           
        access_log /var/log/nginx/reverse-access.log;                                                                                                             
        error_log /var/log/nginx/reverse-error.log;                                                                                                               
        location / {
              proxy_pass http://reposilite;
              proxy_set_header   Host              $host;
              proxy_set_header   X-Real-IP         $remote_addr;
              proxy_set_header   X-Forwarded-For   $proxy_add_x_forwarded_for;
              proxy_set_header   X-Forwarded-Proto $scheme;
              proxy_set_header Upgrade $http_upgrade;
              proxy_set_header Connection $connection_upgrade;
              proxy_http_version 1.1;    
        }                                                                                                                                                              
} 
```

**Comment by dzikoysk** [comment]
Thanks for sharing your solution! I'll mention it in FAQ during the next update of the Reposilite website.

**Comment by BluCobalt** [comment]
Would you happen to have the websocket proxy config required for apache?

**Comment by dzikoysk** [comment]
Unfortunately I don't have, but take a look at `mod_proxy_wstunnel`. I've already found some related questions:

* https://stackoverflow.com/questions/27526281/websockets-and-apache-proxy-how-to-configure-mod-proxy-wstunnel
* https://stackoverflow.com/questions/43552164/websocket-through-ssl-with-apache-reverse-proxy

If you'll figure it out and share the solution, I could also add apache section to the FAQ.

**Comment by BluCobalt** [comment]
I've got it working!
Here is the relevant portion of my apache vhost:
```vhost
# reposilite is listening on 127.0.0.1:6385
RewriteEngine On

RewriteCond %{HTTP:Upgrade} =websocket [NC]
RewriteRule ^/api/(.*)    ws://127.0.0.1:6385/api/$1 [P,L]

ProxyPass / http://127.0.0.1:6385/
ProxyPassReverse / http://127.0.0.1:6385/
```

**Comment by dzikoysk** [comment]
Thanks, I hope it will help someone else! :)

**Comment by StaticDevMC** [comment]
for the latest version (v3-alpha) I recommand use this configuration, but there is also an issue with the console:

```
  RewriteEngine On
  RewriteCond %{HTTP:Upgrade} =websocket [NC]
  RewriteRule ^/api/(.*) ws://127.0.0.1:8081/api/console/sock/$1 [P,L]
  ProxyPass / http://127.0.0.1:8080/
  ProxyPassReverse / http://127.0.0.1:8080/
```
