### ISSUE TITLE
No mention of the dashboard url in documentation

### ISSUE THREAD

**Issue by jflamy** [dzikoysk/reposilite#352]
A step-by-step process is needed to describe the very first use

1. create a subdirectory, put the  jar there, start it (Override the port if not running as root)
2. Tell people to run the keygen command for admin
3. Tell people that the url for the dashboard is .../dashboard (or add a button on the main page)

**Comment by dzikoysk** [comment]
It might be a good idea to make an all-in-one page that combines all of these first steps in one article, some kind of official version of:

* https://dev.to/dzikoysk/publishing-your-artifacts-to-the-reposilite-a-new-self-hosted-repository-manager-3n0h

By the way, you can click feather to access the login panel (https://reposilite.com/docs/cli). It also could be better exposed in docs.

**Comment by jflamy-dev** [comment]
I had seen the article— the part I got stuck was the non-obvious fact that the keygen command is given at Java (there is no prompt!).  I’m trying to replace bintray which is shutting down and Maven central is just too complicated for my needs.  Good job!
