### ISSUE TITLE
checksum miscomputed for maven-metadata.xml

### ISSUE THREAD

**Issue by jflamy** [dzikoysk/reposilite#354]
I deployed my first artifacts today to a Ubuntu 20.04 Linux setup (standalone version reposilite-2.9.10.jar),
When I did a test deploy (from a Windows 10 dev machine) I received a `maven-metadata.xml` checksum warning after the upload to reposilite.

I downloaded the artifacts and they looked fine, so I ignored the warning and blamed them on Windows oddities (even though I never got issues uploading  to bintray.com)
Tonight I am running my CI build on Azure DevOps using Ubuntu, and I also get the same warning when deploying to reposilite.

```
[WARNING] Checksum validation failed, expected 3e6c06b1a28a035e21aa0a736ef80afadc43122c but is 429753b55e2187644c74bee1ff32e09860de36b3 from owlcms-maven-repo for http://maven.owlcms.mywire.org:8088/releases/app/owlcms/owlcms/maven-metadata.xml
```

The actual checksum on the reposilite directory is indeed the same as computed by the job, and different from the one stored inside the .sha1 file.
```
$ sha1sum maven-metadata.xml
429753b55e2187644c74bee1ff32e09860de36b3  maven-metadata.xml
```

**Comment by dzikoysk** [comment]
You should get rid of this warning by using 2.9.11 - this cosmetic bug was resolved in #327 :)
