### ISSUE TITLE
Helm chart (or other way for k8s deployment)

### ISSUE THREAD

**Issue by denis111** [dzikoysk/reposilite#360]
I see there's no instructions how to deploy it to k8s.
Just wanted to ask if there's a helm chart planned or maybe somebody already has it and wants to share ;)

**Comment by dzikoysk** [comment]
Unfortunately, I'm not quite familiar with k8s environment. In the past I've implemented some adjustments for such an usage:

* https://github.com/dzikoysk/reposilite/issues/251

So I think you should be able to use. Helm looks interesting, I'll try to explore the topic.

**Comment by dzikoysk** [comment]
Hmm... As far I see helm uses artifacthub.io service, where people can add their public repositories to the registry. I don't think I want to host and maintain such a thing. I see that you should be able to deploy docker image to k8s using `kubectl` command.

* https://kubernetes.io/docs/reference/kubectl/docker-cli-to-kubectl/
* https://codeburst.io/getting-started-with-kubernetes-deploy-a-docker-container-with-kubernetes-in-5-minutes-eb4be0e96370

I'll provide `docker-compose.yml` to simplify this process.

**Comment by dzikoysk** [comment]
Well, now you should be able to use [Kompose](https://kompose.io/) (~ [translate compose](https://kubernetes.io/docs/tasks/configure-pod-container/translate-compose-kubernetes/)) to launch Reposilite on k8s. If possible, please share the results so I can enhance documentation related to this topic to help other people in the future :)

**Comment by dzikoysk** [comment]
Resolved by https://github.com/reposilite-playground/reposilite-helm
