### ISSUE TITLE
Misprocessed URL in Cli Dashboard

### ISSUE THREAD

**Issue by zen-fge** [dzikoysk/reposilite#364]
In my environnement, where Reposilite is behind a reverse proxy with a context root path, Cli Dashboard didn't work because there is a small bug:
```js
    if (origin.endsWith('/')) {
      origin = origin.substring(1)
    }
```
In my case, `orign` ends with a '/' so the substring is invalid and lead to break the websocket url.

**Comment by dzikoysk** [comment]
By saying `context root path` you mean the base path? :) Could you provide your custom base path, it might be useful during debug.

**Comment by gegouxfr** [comment]
Yes, you are right, I mean `base path` :-)
My configuration starts with:
```txt
hostname: 0.0.0.0
port: 8081
basePath: /reposilite/
```
My basePath ends with a '/'   I've tried to remove it but when I restart the configuration is automatically modified and the ending slash come back again

**Comment by zen-fge** [comment]
Yes, you are right, I mean `base path` :-)
My configuration starts with:
```txt
hostname: 0.0.0.0
port: 8081
basePath: /reposilite/
```
My basePath ends with a '/' I've tried to remove it but when I restart the configuration is automatically modified and the ending slash come back again

**Comment by dzikoysk** [comment]
I've made some fixes related to custom base path, check out the [2.9.14](https://github.com/dzikoysk/reposilite/releases/tag/2.9.14).
