### ISSUE TITLE
Can we upload to a hidden repo?

### ISSUE THREAD

**Issue by yoxel** [dzikoysk/reposilite#367]
Hi there,

It seems we can upload artifacts only to releases or snapshots although in our config we have two more hidden repos and no snapshots actually.

Thanks

**Comment by dzikoysk** [comment]
Well, the dashboard is not perfect, I'll try to investigate this issue this weekend.

**Comment by yoxel** [comment]
Thank you.

**Comment by dzikoysk** [comment]
I've just reviewed this issue and it looks fine:

![image](https://user-images.githubusercontent.com/4235722/108609516-ae520480-73ce-11eb-8ef0-4dacbfb938f9.png)

Do you use token that has access to these private repositories?

**Comment by yoxel** [comment]
Yes, I use an 'm' token. And our list of repos is defines this way:

repositories [

  releases

  .libs-release-local

  .libs-snapshot-local

]

**Comment by dzikoysk** [comment]
I'm not able to reproduce it, could you provide more details about the token (associated path) and your setup (Reposilite version, reverse proxy, custom base path)? And to clarify the issue, you can't see these hidden repositories in the `Upload` tab in the dashboard, but you're able to push artifacts through the standard maven goal?

**Comment by yoxel** [comment]
Yes, that is correct:
>you can't see these hidden repositories in the Upload tab in the
dashboard, but you're able to push artifacts through the standard maven
goal?

Just went to check again and I see the upload repos correctly now.

Sorry, I am not sure how they did not show on the day I filed the ticket. I
guess this ticket can be closed.

**Comment by dzikoysk** [comment]
Good to know! Maybe some kind of browser caching affected the response 🤔 Let me know if this issue will occur once again.
