### ISSUE TITLE
Cli in web UI does not work?

### ISSUE THREAD

**Issue by yoxel** [dzikoysk/reposilite#368]
I type help or ? or anything in web's Cli and nothing happens, nothing shows.

**Comment by dzikoysk** [comment]
Could you share log from dev tools (F12)? :)

**Comment by yoxel** [comment]
REPOSILITE_MESSAGE: Repository dashboard not found
app.js:7 REPOSILITE_BASE_PATH: /
app.js:7 REPOSILITE_VUE_BASE_PATH: 
app.js:7 REPOSILITE_TITLE: #onlypanda
app.js:7 REPOSILITE_DESCRIPTION: Public Maven repository hosted through the Reposilite
app.js:7 REPOSILITE_ACCENT_COLOR: #2fd4aa
app.js:7 undefined
...
app.js:7 WebSocket connection to 'wss://repo.<ourdomain>/api/cli' failed: Error during WebSocket handshake: Unexpected response code: 400
created @ app.js:7
nt @ app.js:7
zn @ app.js:7
e._init @ app.js:7
o @ app.js:7
rn @ app.js:7
init @ app.js:7
n @ app.js:7
m @ app.js:7
d @ app.js:7
A @ app.js:7
C @ app.js:7
A @ app.js:7
C @ app.js:7
(anonymous) @ app.js:7
Nn.e._update @ app.js:7
i @ app.js:7
ni.get @ app.js:7
ni.run @ app.js:7
Jn @ app.js:7
(anonymous) @ app.js:7
ut @ app.js:7

**Comment by dzikoysk** [comment]
Do you use some kind of proxy service, e.g. nginx?

**Comment by yoxel** [comment]
Yes, I do. Nginx

**Comment by dzikoysk** [comment]
WebSocket connection requires extra configuration:

* https://reposilite.com/docs/reverse-proxy
