### ISSUE TITLE
Swagger for the REST API

### ISSUE THREAD

**Issue by kontza** [dzikoysk/reposilite#384]
Hi,

Could it be possible to have a Swagger UI for the API? With Spring Boot it is relatively easy to enable.

Or, could it be possible to have a document of REST APIs?

**Comment by dzikoysk** [comment]
At this moment Reposilite doesn't support such an option, but it looks Javalin provides such a possibility:

* https://javalin.io/plugins/openapi

I'll try to explore the topic.

**Comment by dzikoysk** [comment]
Swagger is now available in Reposilite 2.9.18. Here is a preview:

* https://repo.panda-lang.org/swagger

**Comment by TrentLi** [comment]
I can not open swagger UI, can you help me


> Swagger is now available in Reposilite 2.9.18. Here is a preview:
> 
> * https://repo.panda-lang.org/swagger

**Comment by dzikoysk** [comment]
Thanks for reporting this, in 3.x Swagger is a standalone plugin and I didn't use it in the official instance, here it is:

* https://maven.reposilite.com/swagger
