### ISSUE TITLE
Cleanup old artifacts

### ISSUE THREAD

**Issue by utarwyn** [dzikoysk/reposilite#385]
Hello, first I would like to thank you for the active support on the project, I am really satisfied with your service.

I use timestamp-based snapshots in my Reposilite instance to store development artifacts. But as time goes by, my global disk usage is growing. The "disk quota" feature is very nice to avoid a disk saturation. But by using your service, I don't have a quickly or automatically way for cleaning up old artifacts.

Is it a planned feature? Or maybe too complex/consuming to be implemented?
I don't have a clear idea how to integrate it *(maybe a max amount of snapshots per artifact?)*.

**Comment by dzikoysk** [comment]
Thanks :)

Yeah, it sounds reasonable. I'm not sure how to solve this issue at this moment, but I'll try to explore possible options after #384.

**Comment by utarwyn** [comment]
Thank you! It's not urgent :)

**Comment by caoli5288** [comment]
So how to keep only the latest snapshots artifacts?

**Comment by utarwyn** [comment]
@caoli5288: that's kind of the goal of this issue yes :)

**Comment by dzikoysk** [comment]
All issues are kinda suspended due to some braking changes on #387 by @Haven-King. I don't want to make it more difficult for him, so we need to wait for a while 😛

**Comment by Haven-King** [comment]
This seems like it would be a good use-case for per-repository options, as detailed in #394.

**Comment by utarwyn** [comment]
Yep, I definitly agree with that idea!

**Comment by caoli5288** [comment]
any progress?

**Comment by dzikoysk** [comment]
We're still with #387 which conflicts with this topic, so unfortunately it's not yet available. It's issue of high priority, so as soon as we will get through it, I'll take care of it. Moving to `nio` and implementing whole fs abstraction takes some time :/ It's also developed by volunteer and I don't want make his task harder because of some various merge conflicts.

**Comment by Haven-King** [comment]
nio porting and file system abstraction are nearly done, I just need to do some more thorough testing. I'll hopefully have it in a "finished" state by the end of next week.

**Comment by dzikoysk** [comment]
I'll add it after 3.x release as I don't want to introduce new features to somehow simplify this process.

**Comment by dzikoysk** [comment]
Available in `Configuration` tab in the dashboard, configurable per each repository:

![image](https://user-images.githubusercontent.com/4235722/147862442-614c92ba-c3a2-4e4d-b0e1-b9a83a26b3c3.png)

**Comment by utarwyn** [comment]
Thank you for this addition! I can't wait to try version 3 🥳

**Comment by dzikoysk** [comment]
I think it was the longest opened issue in this repository, not quite proud of this fact, but at least I like the fact, it's fully implemented as event listener on top of the new plugin api 🎉

**Comment by marco-brandizi** [comment]
@dzikoysk is this in the web interface? I've just upgraded to 3.5.5 and I can't find it in the repository configurations.

**Comment by marco-brandizi** [comment]
@dzikoysk thanks. I thought the feature allows for telling how many old repos to retain, but it's good even without this detail.

**Comment by dzikoysk** [comment]
Sure, keep in mind that if you have some specific requirements, you can always cover this via plugin api with your own implementation.
