### ISSUE TITLE
Abstract Repository and Token Storage

### ISSUE THREAD

**Issue by Haven-King** [dzikoysk/reposilite#392]
Move all file manipulation logic into a single abstract class/interface so that alternative storage solutions can be implemented more easily. Ideally, all file saving/loading outside of the config file would go through this abstraction (including tokens). Such a class may be called `StorageProvider`, with a default implementation `FileSystemStorageProvider` that would act just like the current system.

Two additional new implementations that would be good to have included by default would be `RemoteStorageProvider`, which would allow users to implement a REST API that can accept any requests for storing/getting/listing files (The REST API could be hosted locally, to make the whole system more modular) and an `S3StorageProvider`, which would allow users to specify a destination S3 bucket. The S3 provider *could* be implemented and shipped separately as a REST API to be used with `RemoteStorageProvider`, but it seems like a common enough use case to warrant shipping natively.

The storage provider that's used could be selected through either the config file or command line arguments.

**Comment by dzikoysk** [comment]
Do you think about using some kind of library, for instance Apache Commons VFS? I've never used such a solution and I don't know what is the proper way of providing support for different storage providers.

**Comment by Haven-King** [comment]
I'd like to avoid dragging in any other dependencies if possible. [Here ](https://github.com/Haven-King/reposilite/blob/storage-providers/reposilite-backend/src/main/java/org/panda_lang/reposilite/storage/StorageProvider.java)is what I've started planning out the `StorageProvider` might look like (with additional `putFile` methods for `InputStream`s and such). My draft of the `FileSystemStorageProvider` implementation is [here](https://github.com/Haven-King/reposilite/blob/storage-providers/reposilite-backend/src/main/java/org/panda_lang/reposilite/storage/FileSystemStorageProvider.java), which also eliminates the need for the `DiskQuota` class.

These are still in the early drafting stage, of course :)

**Comment by dzikoysk** [comment]
Yeah, it looks like these Apache VFS implementations are kinda dead anyway 🤔 I wonder if file locks could be moved directly to storage providers, because at this moment locking mechanism is up to an implementation of service performing some fs operations.

**Comment by Haven-King** [comment]
Yep, I've tentatively moved the file locks to the `FileSystemStorageProvider`. I think we'll want to look into a better mechanism for that that still addresses #251 and #264, but ideally people wouldn't be using a single drive for multi-instance solutions (which the S3 storage provider would be great for).

**Comment by dzikoysk** [comment]
Right, the current locking system was a compromise between the existing implementation and the related issue. As you can notice, it was not designed to support distributed platforms, so I'm glad to see such an improvement ❤️
