### ISSUE TITLE
Add Per-Repository Options

### ISSUE THREAD

**Issue by Haven-King** [dzikoysk/reposilite#394]
It would be good to look into a more robust way of defining per-repository configs. The current practice of using a `.` to denote a private repository could use the new system instead, as well as any other options.

The current `repositories` block:
```
repositories [
  releases
  snapshots
  .private
]
```

Might look like:
```
repositories [
  releases --no-redeploy
  snapshots
  private --private
]
```
I'm not entirely sure how you'd want to format it, given that there's no precedent for any kind of "object" in your config file, but I wanted to open the conversation.

**Comment by dzikoysk** [comment]
We can convert repositories into objects or maps:

```
repositories {
  releases {
    redeploy: false
    public: true
  }
  private {
    redeploy: false
    public: false
  }
}
```

CDN will perform conversion automatically, so it is not a problem, but I kinda like your proposal with flags, just because it looks cleaner.

**Comment by Haven-King** [comment]
Gotcha. I hadn't seen your CDN repository, so I wasn't entirely sure what the config format was. Either flag-style or objects should work fine. I have a hard time thinking of any options that couldn't be represented as either `--flag` or `--flag [data]`, which would both be acceptable. Objects are going to be more familiar to a lot of people though, so it's probably worth using objects for that reason alone.

**Comment by dzikoysk** [comment]
I think it might be even harder to declare repositories in the configuration through objects tbh. I think we should stay with flags at this moment and in case of any further issues, it could be migrated to standalone file (just like tokens), where some kind of a new command set would properly manage them.

**Comment by dzikoysk** [comment]
There is a proposal for per-repository configuration of proxy (#448) that brings the topic of properties like lists:

https://github.com/dzikoysk/reposilite/blob/daa7d05c133f03d6e7b32d224e62b08dae138784/reposilite-backend/src/main/java/org/panda_lang/reposilite/config/Configuration.java#L80

Summing up various related issues we'd get sth like:

```json5
repositories [
  releases --no-redeploy --quota 1GB
  snapshots --cleanups --quota 1GB
  mirror --quota 1GB --cleanups --store-proxied --proxied https://repo1.maven.org/maven2;https://repo1.maven.org/maven3;https://repo1.maven.org/maven4
  anonymous --hidden
  private --private
]
```

I wonder if we want to keep it that way or we want to a little modify it. Some possible variants:

```json5
repositories [
  # v1
  releases [
    --no-redeploy
    --quota 1GB
  ]
  # v2
  snapshots [
    cleanups
    quota 1GB
  ]
  # v3
  mirror {
    quota: 1GB
    cleanups: true
    store-proxied: true
    proxied [
      https://repo1.maven.org/maven2
      https://repo1.maven.org/maven3
      https://repo1.maven.org/maven4
   }
  # v4 (current)
  anonymous --hidden
  private --private
]
```

I kinda like _v1/v2/v4_, but that's just my preference and I'd like to know what's your opinion.

**Comment by Haven-King** [comment]
I've already gone ahead and implemented a system [very similar to v4](https://github.com/dzikoysk/reposilite/blob/72af83e13d63a8562db3bc68187d365b40c0ba31/reposilite-backend/src/main/java/org/panda_lang/reposilite/config/RepositoryOption.java#L16), but I'd be happy to change it. More parsing will be required, but that shouldn't be a large issue if you think it would be worth it.

**Comment by dzikoysk** [comment]
I'm pretty sure we shouldn't parse and load it that way 🤔 I think we should keep configuration as a static piece of information. In `v4` case, the repository domain configuration should get a parameters string for each repo from configuration and load it with picocli (it's probably the best option for clean load of v1, v2 and v4). I may try to implement omitting default values in CDN entities, so we could simplify a little v3.
