### ISSUE TITLE
Mixed repository like nexus' public

### ISSUE THREAD

**Issue by caoli5288** [dzikoysk/reposilite#397]
Request configurable mixed repository like nexus' public.

Or defaults to public = snapshots + releases

**Comment by dzikoysk** [comment]
You can add new repository in the configuration. and you should be able to deploy both build types to every repository.

**Comment by caoli5288** [comment]
> 
> 
> You can add new repository in the configuration and you should be able to deploy both build types to any repository.

So the releases repository only named "releases "?

**Comment by dzikoysk** [comment]
It's just a standard name for default repository. Repository name does not really matter, it all depends on your distribution configuration and version of artifact (`-SNAPSHOT` in version switches context)

**Comment by pangiole-tibco** [comment]
> It's just a standard name for default repository. Repository name does not really matter, it all depends on your distribution configuration and version of artifact (`-SNAPSHOT` in version switches context)

---
I'm testin with Reposilite version `3.0.0-alpha.25. Just tried to re-deploy an artifact having version ending with `-SNAPSHOT` and got the following error response:

```json
{"status":400,"message":"Redeployment is not allowed"}
```

It's not clear which _"distribution configuration"_ should I set to enable the behaviour of mixed repositories _"a la Sonatype Nexus"_

**Comment by dzikoysk** [comment]
You can enable redeployment in shared configuration - you can find it in `Configuration` tab in web interface :)

**Comment by pangiole-tibco** [comment]
Ok, found it!
I'm answering my self to my comment (see above)
The right piece of configuration seems to be:

```
# file: configuration.shared.json
repositories {

   # the repository name does not matter   
   my-beloved-one {   
   
      # How many builds of the given snapshot version should be preserved when a new build is deployed. 
      # Use -1 to disable this feature
      preserved: 8
      
   }
}      
```

With the above pice of configuration with the `-SNAPSHOT` suffix appended to the artifact version, the same artifact can be uploaded multiple times up to a maximum of 8 times.

**Comment by pangiole-tibco** [comment]
> You can enable redeployment in shared configuration - visit `Configuration` tab in web interface :)

[dzikoysk](https://github.com/dzikoysk), enabling redeployment would allow any versions, regardless their values, to be redeployed as it would not make any distinction between those ending with `-SNAPSHOT` and those not.

The so-called mixed repository behaviour, _"a la Sonatype Nexus"_, (which seems to be widely known and accepted by the Java community) is that :

* the only artifacts allowed to be redeployed multiple times are those having version ending with `-SNAPSHOT`
* contrarly, those artifacts having version which does not end with `-SNAPSHOT` shall not be redeployed again

QUESTION: _"Does Reposilite provide that behaviour? If yes, how to configure it? If no, can we add an issue ticket demanding for enhancement? Do you need contributors for it?"_

**Comment by dzikoysk** [comment]
Umm... the `Version policy` property describes something slightly different than `redeployment`. It stands for support for snapshot builds in repository, because snapshot structure is quite different than regular build. In general Reposilite by default works like the `Mixed` mode here, because it accepts: regular builds, snapshot build & pseudo snapshot builds. On the other hand, the `redeployment` property is more likely referring to the state of repository content, so you can guarantee there is no change in existing files for like e.g. security purposes. So on, I don't quite see the reason to change this behavior, because it's really explicit about what it does 🤔 So the general setup would look like this:

```
releases:
  redeployment: false
snapshots:
  redeployment: true
all:
  proxied: [releases, snapshots]
  redeployment: false
```
