### ISSUE TITLE
Generate checksums for any stored file is missing

### ISSUE THREAD

**Issue by caoli5288** [dzikoysk/reposilite#400]
Otherwise, it may cause some problems

![image](https://user-images.githubusercontent.com/3120587/110750321-4419da80-827d-11eb-934d-6df9dc1baae5.png)

**Comment by dzikoysk** [comment]
Maven metadata is dynamically generated by Reposilite. Just call `(...)/maven-metadata.xml` path.

**Comment by caoli5288** [comment]
@dzikoysk Seems Reposilite do generated `maven-metadata.xml` after anybody request it!

But it doesn't seem to generate the checksum of the jar file.

![图片](https://user-images.githubusercontent.com/3120587/110900586-ef8a6400-833d-11eb-84ae-88afda2a6d39.png)

**Comment by dzikoysk** [comment]
Checksum should be generated by `mvn deploy` command and you've probably uploaded this artifact using web cli. It's probably why there is no such a file. I'll mark it as a cosmetic issue, because it's just an information and it should not cause any other issues.
