### ISSUE TITLE
Application should exit if port is taken

### ISSUE THREAD

**Issue by stephansann** [dzikoysk/reposilite#408]
Hello!

First of all: Reposilite is a-ma-zing! I am so happy I found it for the hosting of my OSS-App artifacts. It is easy to set up and everything is straightforward. Love it! Thanks a lot for it!

By chance I found out that - if started on a busy port - it just logs an exception and keeps on running.
IMHO in this situation the application should exit.
A half-running application only makes it harder to detect problems. If the process is not running, I can easily detect it. Like this I have to implement some kind of HTTP-Client, which has to connect to the server and check if it is really running (listening).

If this is not what you think, maybe you could make the behavior configurable!?

Thanks again and best regards
Stephan

**Comment by dzikoysk** [comment]
Thanks for your kind words :)

It's not expected behaviour and it should be definitely fixed. I'll take a look at this during #407.
