### ISSUE TITLE
No respone to HTTP client request for stop

### ISSUE THREAD

**Issue by jpschewe** [dzikoysk/reposilite#410]
When I use `curl` to send a stop command I get an error "curl: (52) Empty reply from server". Technically it's an HTTP error when a web server doesn't send a response. You may need to start a timer to stop the service, then send the response so that the response gets out before the service exits.

**Comment by dzikoysk** [comment]
Yeah, it looks like I should provide some kind of delay to properly send the response, thanks for the report.
