### ISSUE TITLE
Log writing fails for final shutdown messages

### ISSUE THREAD

**Issue by magneticflux-** [dzikoysk/reposilite#411]
It's not a major issue, but every time the Docker container is shut down, the last two messages fail to be written to the file and instead write errors to STDOUT:
```
LOGGER ERROR: Failed to write log entry 'Shutting down 0.0.0.0::80 ...' (java.io.IOException: Stream Closed)
07:37:57.046 INFO | Shutting down 0.0.0.0::80 ...
LOGGER ERROR: Failed to write log entry 'Stored records: 5' (java.io.IOException: Stream Closed)
07:37:57.084 INFO | Stored records: 5
```

Perhaps the log file is being closed by the logger too soon?

**Comment by dzikoysk** [comment]
Launching and shutting down the app may cause such an issues, because implementation is not the best and I need to rewrite it. I'll take care of it as soon as #387 is finished.
