### ISSUE TITLE
Requires version crash on update

### ISSUE THREAD

**Issue by milkyway0308** [dzikoysk/reposilite#413]
Requires version crash when upload existing version on release repository, like Github Package.

**Comment by dzikoysk** [comment]
Do you mean something like #395?

**Comment by milkyway0308** [comment]
Yeah, I didn't see opened issue.
Anyway, thank's for develop reposilite! Works very smooth, and great.

**Comment by dzikoysk** [comment]
Thanks, let me know in case of any extra issues :)
