### ISSUE TITLE
The Web UI is incomplete in offline environment

### ISSUE THREAD

**Issue by OrdinaryMiracles** [dzikoysk/reposilite#421]
I installed reposilite in offline environment, but found that the Web UI display is incomplete. I read the relevant source code and found online ".css" and ".js" files are referenced in "index.html". This problem is solved temporarily by downloading these files and modifying "ReposiliteHttpServer.java", but I don't think it's a good solution.

**Comment by dzikoysk** [comment]
Hi, the frontend was never meant to be used in fully offline mode, but I can take care of it during some of the changes related to the #138
