### ISSUE TITLE
K8s > Token generation

### ISSUE THREAD

**Issue by olivierboucher** [dzikoysk/reposilite#424]
Hi,

I'm in the process of deploying reposilite on kubernetes and possibly submitting a chart for #360 

I was wondering if there was any way to generate a token or specify tokens manually when starting the server because there is no way to get an interactive CLI going on in k8s.

My goal would be to have some way to generate tokens, store them in some sort file, translate that into a kubernetes secret, mount it to the container and have it read from it. 

Let me know if I can be more specific

**Comment by dzikoysk** [comment]
Hi :)

Well, there is no default access token at this moment, so you should probably launch Reposilite for the first time locally to generate a new one. I didn't want to provide some kind of a default access token to avoid situations when people could forget to change them or something. Let me know if you have some suggestions in this area. 

Reposilite uses BCrypt to encrypt tokens:
* https://github.com/dzikoysk/reposilite/blob/3d8739119e2a433238877c93bedd2c7f97459b23/reposilite-backend/src/main/java/org/panda_lang/reposilite/auth/TokenService.java#L59

And stores them in yaml file:

* https://github.com/dzikoysk/reposilite/blob/3d8739119e2a433238877c93bedd2c7f97459b23/reposilite-backend/src/main/java/org/panda_lang/reposilite/auth/TokenStorage.java#L79

I'm not sure about the helm support, I've generated some files related to this ecosystem:

* https://github.com/dzikoysk/reposilite/tree/master/reposilite-packages/reposilite-helm

But then I've found out that there is no official repository for chars, so I gave up on this topic. I think Kompose should be able to cover k8s use-cases.

**Comment by olivierboucher** [comment]
@dzikoysk Thank you !

Not that this is related to tokens but I was wondering if there was any endpoint I could hit for health checks. Various Ingress implementation require that the app replies with 200 to their health check. Currently the / path returns 203 since the health check client doesn't support javascript.

**Comment by dzikoysk** [comment]
You can check available routes here: https://repo.panda-lang.org/swagger. API requests should return `200`.
