### ISSUE TITLE
Separate Proxied files into own 'proxy' repo.

### ISSUE THREAD

**Issue by LexManos** [dzikoysk/reposilite#448]
Ideally we'd allow this to separate out proxies files, from files intentionally uploaded to the repo.
This is for organizational purposes. 
It'd be nice to have space limits not impact the main repo.
Prevents duplicate data when multiple repos proxy the same upstream repo.
Also allows flat out deleting files inside that repo {potentially automated if not accessed in X days?} without interfering with manually added files.

**Comment by dzikoysk** [comment]
Hmm, we'd need to add per-repository quotas (through #394) and some kind of lazy tasks that scans repositories in background (could be combined with #385). Overall, it's a good idea to add such a possibility.

**Comment by LexManos** [comment]
Those were just some of the ideas for a use. The main one I'm concerned about is the separation from potentially non-replaceable data. Makes for easier backups.

**Comment by Haven-King** [comment]
Per-repository storage solutions are a WIP, but I have already done some work for [per-repository options](https://github.com/dzikoysk/reposilite/blob/72af83e13d63a8562db3bc68187d365b40c0ba31/reposilite-backend/src/main/java/org/panda_lang/reposilite/config/RepositoryOption.java#L16). I would be happy to add some proxy options to that PR which would replace the existing proxy options and allow for this kind of granularity.

**Comment by LexManos** [comment]
A related note to this, it seems to be a bug that proxied files are always stored in the primary repository.
Causing files requested on the non-primary repository to always miss and re-download the file.
`http://localhost/snapshots/net/md-5/SpecialSource/1.9.0/SpecialSource-1.9.0.jar`
`Stored proxied .\repositories\releases\net\md-5\SpecialSource\1.9.0\SpecialSource-1.9.0.jar from https://repo.panda-lang.org/net/md-5/SpecialSource/1.9.0/SpecialSource-1.9.0.jar`

**Comment by dzikoysk** [comment]
If possible, report as much suggestions as you can. I think it's a good time to consider 3.x due to various breaking suggestions. We could also get rid of some legacy stuff that could block development on 2.x.

**Comment by LexManos** [comment]
Ya, i'm currently working on learning the code, and figuring out what things would be nice to have for our repository. 
See my fork here: https://github.com/dzikoysk/reposilite/compare/master...MinecraftForge:master
It'll be an ongoing thing while I figure things out. I already have thoughts on a complete revamp of the API endpoint because honestly it doesn't tell me anything that I want.
My next task is looking into if failures from proxies are cached at all. Or if every request that we dont have is bounced to the proxied server.
Then i'm going to be adding a regex/list to blacklist things requested from proxies.
Because I know for a fact certain patterns clients send to our server will never be on remote servers. And our files will never have them, so making a known blacklist to short circuit and 404 would save a lot of CPU/network.

I also added the ability to send a custom 404 page. So that it just bypasses the entire index/app: https://maven.minecraftforge.net/asdf/a/abcd.jar

Also, quieting down the cli log. I don't like the way I did it {turned a lot of logging from info to debug} but I haven't looked into how the cli works yet, and it was completely unusable due too the activity of our repo spitting out 2 lines for every request.

So ya, If you don't mind me spamming this place with a bunch of small requests. I can make seperate issues as I find things that I would use on our server.

**Comment by dzikoysk** [comment]
I see, I think we should figure out these various issues to provide support through the official distribution, so feel free to use tracker. As far as I see you're just hot-patching project for your needs, but remember that #387 kinda breaks half of the repository.
It's really late where I live and I'm literally sleeping, so see you later.

**Comment by LexManos** [comment]
I'm keeping an eye on that. There is a reason why i'm trying to keep our changes as small as possible. There are some cases which I don't handle because it would require a larger change and i'm trying to keep it easy for me to rebase.

**Comment by dzikoysk** [comment]
Well, `ReposiliteContext` is relatively new concept and I was not sure if I want to keep it. I think it's quite a good idea to move these common features like uri normalization or auth within this wrapper, I like this.

**Comment by dzikoysk** [comment]
Addressed in #544
