### ISSUE TITLE
Proxied files include directory indexes

### ISSUE THREAD

**Issue by LexManos** [dzikoysk/reposilite#449]
If a directory contains a period {and thus has an 'extension'} will request it from upstream and cache it.
Example: https://repo.panda-lang.org/releases/activesoap/activesoap/1.0-20050615.083700
It's served as a file, but is a web page. Better option would be to filter our any html file returned from upstream. Probably worth filtering out most mime types for common web files such as images.

**Comment by dzikoysk** [comment]
Addressed in #544
