### ISSUE TITLE
API Revamp Ideas

### ISSUE THREAD

**Issue by LexManos** [dzikoysk/reposilite#451]
This is more just my thoughts on what i'd like to see from the API, not a hard suggestion or anything.

Expandability:

-   Most sites use /api#/ to define feature sets. Not sure if this would be big enough to care about that.
-   The next entry should be command name, so that extra commands can be added in the future.
-   The current ones would be something like /api/listFiles/{path} and /api/fileInfo/{path}
  
Additional api that I would find a use for:

/api/checksums/{group:artifact:version:classifier@ext}
- Used to return all known checksums for a file in one simple call. 
- Accepts a JSON/Plain Text POST for the requested hash types? "I want to know the sha1, md5, and sha512 of foo.jar"

/api/stats/downloads/{group:artifact:version:classifier@ext}
- Returns a simple count of how many times that entry has been requested. I could use this for our download index page.
- Accept a json/plain text POST with a list of files to return entries for? That way it could be one request to query the counts for every file in our index: https://files.minecraftforge.net/net/minecraftforge/forge/

/api/classifiers/{group:artifact:version}
 - Maven layout has no way to list all files for a version, this would be nice. It's similiar to listFiles, but skips hashes/poms/etc
 
 Also somewhat related to https://github.com/dzikoysk/reposilite/issues/435 A way to limit a token/user's access to specific api elements, or the entire system would be useful. Being able to get hashes/classifiers is fine but if we add a API to delete proxied files or anything like that we'd need fine grained auth.

**Comment by dzikoysk** [comment]
List of planned API routes in 3.0:

```
{gav} is /:repository/:group/:artifact/:version/:file (depends on the context how many parts are required to get valid response)
[feature request] routes are new functionalities that probably won't be implemented at once

Authentication endpoint
GET    /api/auth/info - Access token details

Repository endpoint
GET    /api/maven/file/{gav} - Get content of file
PUT    /api/maven/file/{gav} - Deploy file
POST   /api/maven/file/{gav} - Deploy file
DELETE /api/maven/file/{gav} - Delete file
GET    /api/maven/details/{gav} - File (or directory with index of files) description
GET    /api/maven/checksums/{gav} - [feature request] - list of available hash types
GET    /api/maven/versions/{gav} - returns list of available versions
GET    /api/maven/latest/{gav} - returns latest version of artifact

Badge endpoint [feature request]
GET    /api/badge/latest/{gav}
GET    /api/badge/downloads/{gav}

Statistics endpoint
GET    /api/statistics/count/{gav} - count of resolved files
```
