### ISSUE TITLE
Rewrite frontend

### ISSUE THREAD

**Issue by dzikoysk** [dzikoysk/reposilite#460]
Changes:
* Better UI (new layout)
* Support dark & light themes
* Drop possibility of serving whole application under 404 routes. Support browsing only through search uri param, for instance:
  ```
  domain.com/#/releases/org/panda-lang
  ```
* Extend configuration possibilities
* Use Vue 3.x instead of Vue 2.x
* Use Windicss instead of Tailwindcss
* Move to Vite
* Add possibility to use custom frontend implementation

UI concept proposals (explore inspirations in dedicated Pinterest board: https://pin.it/MillMAj):

**Comment by dzikoysk** [comment]
UI concept:

![img](https://cdn.discordapp.com/attachments/812280988393799740/835538049949237258/unknown.png)

**Comment by neg4n** [comment]
> UI concept v1
> 
> ![image](https://user-images.githubusercontent.com/4235722/115964572-70d03b80-a525-11eb-8721-eba229c42a27.png)

Looks good despite fact that this is almost 1:1 copy of https://vercel.com/ dashboard 😁

**Comment by dzikoysk** [comment]
Atm it's a mix of Chakra UI, Vercel dashboard and [Fluent Dark UI](https://pl.pinterest.com/pin/354658539412202314/) + some old pins from [hub](https://github.com/panda-lang/hub) project. I kinda like it, because such a design does not really require styling, especially with windicss. We're also still limited to a small number of ported libraries for Vue 3 :/ I'd be glad if you or community could come up with a fancy UI proposal, because I'm focused on preventing regression over the 2.x rather than UI design. We need to rewrite whole frontend in a decent amount of time to catch up 3.0 schedule.

**Comment by neg4n** [comment]
I might take a look at it at my free time (in 1-2 weeks?) and eventually I will contact you via email or here however I can't promise anything 🤙

**Comment by dzikoysk** [comment]
Todo:
* Extend layout with search box and ping info
* Add dashboard concept
