### ISSUE TITLE
Run reposilite as daemon

### ISSUE THREAD

**Issue by FloweyTheFlower420** [dzikoysk/reposilite#464]
How would one go about starting reposilite as a daemon from init? Do I need to disable CLI?

**Comment by dzikoysk** [comment]
Launching Reposilite as a daemon is exactly the same as any other Java application. There are several ways to achieve this, so I think you should just make a research around this topic and select the best option for you. You have to remember, that Reposilite uses CLI (which is required at least during the first launch to generate your first access token), so you may explore possibilities that support interactive mode. The simplest one-liner would be probably just a dedicated `screen`.

**Comment by dzikoysk** [comment]
Related: #468
