### ISSUE TITLE
Body greater than max size

### ISSUE THREAD

**Issue by thhart** [dzikoysk/reposilite#467]
Can not find a configuration possibility for uploading artifacts via Maven deployment greater than this boundary size? How to change this?
The max is 1000000 bytes.

Version: 2.9.21

**Comment by dzikoysk** [comment]
1000000 bytes is just 976kb, so it's quite small file. Does this issue also occur on 2.9.20?

**Comment by thhart** [comment]
This is what I get exactly in the reposilite console:
16:08:56.546 WARN | Body greater than max size (1000000 bytes)
The file in question is around 12 MB.

**Comment by thhart** [comment]
This is what I get in Maven, maybe the warning is misleading and it is rather an auth problem?

[ERROR] Failed to execute goal org.apache.maven.plugins:maven-deploy-plugin:2.7:deploy (default-deploy) on project commons-core: Failed to deploy artifacts: Could not transfer artifact com.itth.commons:commons-core:jar:4.0 from/to local-repository (http://localhost:5050/releases): Transfer failed for http://localhost:5050/releases/com/itth/commons/commons-core/4.0/commons-core-4.0.jar 401 Unauthorized -> [Help 1]

**Comment by dzikoysk** [comment]
I'm uploading 25MB Reposilite atm to the repository and it works fine. I wonder if it is related do Javalin 4.x backend.

https://github.com/tipsy/javalin/blob/3d9b86f4a111412ed1af55506043d5e694057b20/javalin/src/main/java/io/javalin/http/util/ContextUtil.kt#L98

Do you have enabled debug mode?

**Comment by thhart** [comment]
Yes Debug is on. In 2.9.20 I don't get this WARN in the console but the upload fails as well.

**Comment by dzikoysk** [comment]
Ok, so first of all turn off the debug mode. It causes strange behaviors for large artifacts. Also, please share the log when the deploy fails with disabled debug mode.

**Comment by thhart** [comment]
Same problem, below is the full log. In Maven it simply states Unauthorized.

20:04:42.405 INFO |                                                                                                                              
20:04:42.410 INFO | Reposilite 2.9.21
20:04:42.411 INFO | 
20:04:42.559 INFO | --- Environment
20:04:42.559 INFO | Platform: 14.0.2 (Linux)
20:04:42.559 INFO | Configuration: /etc/reposilite/reposilite.cdn
20:04:42.559 INFO | Working directory: /opt/reposilite/.
20:04:42.560 INFO | 
20:04:42.560 INFO | --- Loading data
20:04:42.560 INFO | Using an existing tokens data file
20:04:42.641 INFO | Tokens: 2
20:04:42.642 INFO | 
20:04:42.642 INFO | --- Loading repositories
20:04:42.642 INFO | Using an existing repository directory
20:04:42.643 INFO | + releases (primary)
20:04:42.643 INFO | + snapshots
20:04:42.643 INFO | 2 repositories have been found
20:04:42.643 INFO | 
20:04:42.643 INFO | --- Loading domain configurations
20:04:42.682 INFO | Binding server at 0.0.0.0::5050
20:04:42.959 INFO | Done (0.28s)!
20:04:42.962 INFO | 
20:04:42.967 INFO | Reposilite 2.9.21 Commands:
20:04:42.968 INFO |   chalias <alias> <new alias> - Change token alias
20:04:42.968 INFO |   chmod <alias> <permissions> - Change token permissions
20:04:42.968 INFO |   failures  - Display all recorded exceptions
20:04:42.968 INFO |   help [<command>] - List of available commands
20:04:42.968 INFO |   keygen <path> <alias> [<permissions>] - Generate a new access token for the given path
20:04:42.969 INFO |   purge  - Clear cache
20:04:42.969 INFO |   revoke <alias> - Revoke token
20:04:42.969 INFO |   stats [<filter>] - Display collected metrics
20:04:42.969 INFO |   status  - Display summary status of app health
20:04:42.969 INFO |   stop  - Shutdown server
20:04:42.969 INFO |   tokens  - List all generated tokens
20:04:42.969 INFO |   version  - Display current version of Reposilite
20:04:42.970 INFO | 
20:04:42.970 INFO | Collecting status metrics...
20:04:42.970 INFO | 
20:04:43.809 INFO | Reposilite 2.9.21 Status
20:04:43.810 INFO |   Active: true
20:04:43.810 INFO |   Uptime: 0.02min
20:04:43.811 INFO |   Memory usage of process: 15.15M
20:04:43.811 INFO |   Disk usage: 47.8 MiB
20:04:43.812 INFO |   Cached metadata: 0
20:04:43.812 INFO |   Exceptions: 0
20:04:43.813 INFO |   Latest version of reposilite: 2.9.21
20:04:43.813 INFO | 

20:05:11.089 INFO | 
20:05:11.091 INFO | 
20:05:25.855 INFO | DEPLOY /releases/com/itth/commons/commons-core/4.0/commons-core-4.0.jar from 127.0.0.1
20:05:26.153 INFO | DEPLOY /releases/com/itth/commons/commons-core/4.0/commons-core-4.0.pom from 127.0.0.1

**Comment by thhart** [comment]
In logfile I get this below, I will double check correct Maven setup, please hold on.

20:08:30.729 DEBUG | Header ---
  20:08:30.729 DEBUG | Cache-Control: no-cache
  20:08:30.729 DEBUG | Expect: 100-continue
  20:08:30.729 DEBUG | User-Agent: Apache-Maven/3.6.3 (Java 14.0.2; Linux 5.4.0-72-generic)
  20:08:30.729 DEBUG | Connection: keep-alive
  20:08:30.730 DEBUG | Host: localhost:5050
  20:08:30.730 DEBUG | Pragma: no-cache
  20:08:30.730 DEBUG | Accept-Encoding: gzip,deflate
  20:08:30.730 DEBUG | Cache-store: no-store
  20:08:30.730 DEBUG | Content-Length: 12555745
  20:08:30.730 DEBUG | Authorization credentials are not specified
  20:08:30.731 DEBUG | Cannot deploy artifact due to: Authorization credentials are not specified

**Comment by dzikoysk** [comment]
If you're using Gradle, you may need to declare auth method:

* https://reposilite.com/docs/deploy#gradle

Anyway, I wonder when `Body greater than max size` may occur. It's kinda new message and I'd prefer to understand the scenario, thanks for reporting this.

**Comment by thhart** [comment]
No, only Maven in use here.
Ok. I get a little further with a better settings.xml like this, so I am afraid the example in the docu is not correct for 3.x.
https://maven.apache.org/guides/mini/guide-configuring-maven.html

However now the authorization goes ok, but the upload stuck at 2.7 MB...

```
<settings>
        <servers>
        <server>
                <id>local-repository</id>
                <username>user</username>
                <password>qGRuRo2Q2PcJPsoTpomms+CadKsEhD60QLAX6+Sz/QH8gmS7+EbHjHXHYfWPThwQ</password>
        </server>
</servers>
</settings>

```

**Comment by thhart** [comment]
The upload stucks here:

Uploading to local-repository: http://localhost:5050/releases/com/itth/commons/commons-core/4.0/commons-core-4.0.jar
Progress (1): 2.7/13 MB

**Comment by dzikoysk** [comment]
What do you mean by `the example in the docu is not correct for 3.x.` 🤔 Does it always get stuck on 2.7 with clean deploy?

**Comment by thhart** [comment]
> If you're using Gradle, you may need to declare auth method:
> 
> * https://reposilite.com/docs/deploy#gradle
> 
> Anyway, I wonder when `Body greater than max size` may occur, because I didn't get it even in debug mode. It's kinda new message and I'd like to know the scenario, thanks for reporting this.

Maybe it only occurs like this if not authorized in front.
It does not occure in debug mode for me now, however the upload does not go though...

**Comment by thhart** [comment]
> What do you mean by `the example in the docu is not correct for 3.x.`  Does it always get stuck on 2.7 with clean deploy?

I mean Maven 3.x. In https://reposilite.com/docs/deploy you give an example of a settings.xml file which is incomplete. The full file should look like above.

**Comment by thhart** [comment]
Ok. It works now. It was probably related to failed tests from before. I did a clean setup now and it works. Thanks for quick lookup.

**Comment by dzikoysk** [comment]
> I mean Maven 3.x. In https://reposilite.com/docs/deploy you give an example of a settings.xml file which is incomplete. The full file should look like above.

Oh, I've just provided the specified fragment to not paste whole settings.xml file. It could be good idea to provide the rest of settings for a context. 

> Ok. It works now. It was probably related to failed tests from before. I did a clean setup now and it works. Thanks for quick lookup.

Yeah, maven cache handling is terrible, it is always good practice to run full clear for each task to avoid `random()` issues. In case of any further problems feel free to ask.
