### ISSUE TITLE
Service file for Linux environments

### ISSUE THREAD

**Issue by thhart** [dzikoysk/reposilite#468]
This is a code snippet for a possible service file to start reposilite automatically. The file should be saved as reposilite.service into /etc/systemd/system. The **User** must be changed as wished and must exist of course, using the root user is not recommended. Then it might be activated like this:
systemctl enable reposilite
systemctl start reposilite

Of course you must have root access to the system and systemd must be installed as it is in Debian based Linux.

```
[Unit]
Description=Reposilite Service
[Service]
User=th
# The configuration file application.properties should be here:

#change this to your workspace
WorkingDirectory=/opt/reposilite

#path to executable.
#executable is a bash script which calls jar file
ExecStart=java -jar reposilite-2.9.21.jar --config=/etc/reposilite/reposilite.cdn

SuccessExitStatus=0
TimeoutStopSec=10
Restart=on-failure
RestartSec=5

[Install]
WantedBy=multi-user.target
```

**Comment by dzikoysk** [comment]
Thanks, I think we can add `Systemd` section in configuration with the example template.

**Comment by mijutu** [comment]
I tried `systemd-analyze security reposilite`, added some restrictions and got an IOException: Mount point not found

It seems that 

`ProtectSystem=strict` causes an sqlite problem, should use ProtectSystem=true instead

`SystemCallFilter=~@privileged` causes reposilite to be killed with a not so clear error message: systemd[1]: reposilite.service: Main process exited, code=killed, status=31/SYS

`ProcSubset=pid` causes the Mount point not found.

So I ended up using these security restrictions with systemd:
```
BindPaths=/opt/reposilite/work /etc/reposilite
CapabilityBoundingSet=
DevicePolicy=closed
LockPersonality=1
NoNewPrivileges=1
PrivateDevices=1
PrivateTmp=1
PrivateUsers=1
ProtectClock=1
ProtectControlGroups=1
ProtectHome=1
ProtectHostname=1
ProtectKernelLogs=1
ProtectKernelModules=1
ProtectKernelTunables=1
ProtectProc=invisible
ProtectSystem=1
ReadWritePaths=/opt/reposilite/work /etc/reposilite
RestrictAddressFamilies=AF_INET AF_INET6
RestrictNamespaces=1
RestrictRealtime=1
SystemCallArchitectures=native
SystemCallFilter=~@clock @cpu-emulation @debug @module @mount @obsolete @raw-io @reboot @resources @swap
UMask=0077
```

Perhaps something could be a bit more strict but that's a start anyway.
