### ISSUE TITLE
Support access tokens from environment-based sources

### ISSUE THREAD

**Issue by khmarbaise** [dzikoysk/reposilite#477]
Currently I'm setting up a docker instance (or running a docker instance of reposilite) but unfortunately I haven't found a way to generate a permission token or the `tokens.dat` file without starting reposilite in interactive mode once to generate the token (via `keygen ..`)...The makes it complicate to automatically setup a full environment in an automatic way..? Or provide credentials from an outside system like vault or alike? 

Did I miss something in the docs? Maybe you could give a little hint where to find it ?

**Comment by dzikoysk** [comment]
No, at this moment there is no possibility to generate a token without launching the instance. I think it's something what we can try to improve in Reposilite 3.0. Do you have any suggestions on how we can implement such a feature to simplify your workflow? :)

**Comment by khmarbaise** [comment]
First thanks for your reply and answer.

I can think of at least two separate options:

1. Create a separate command line client which could handle that.
2. Support to use an environment variable which could be defined from outside (for example from Vault or alike)

**Comment by volund** [comment]
I ran into the same problem and found this temporary workaround which uses the [socat](https://www.redhat.com/sysadmin/getting-started-socat) utility to run the keygen command on the running docker container. Assuming that the container name is `reposilite` It looks like this:

    echo "keygen / admin m" | socat EXEC:"docker attach reposilite",pty STDIO

For example this outputs:

    echo "keygen / admin m" | socat EXEC:"docker attach reposilite",pty STDIO
    keygen / admin m
    11:17:18.632 INFO | 
    11:17:18.723 INFO | Stored tokens: 1
    11:17:18.723 INFO | Generated new access token for admin (/) with 'm' permissions
    11:17:18.723 INFO | <generated-token>
    11:17:18.723 INFO | 
    
One can then use the generated token to log into the backend

NOTES:

(1) I started my docker image using docker-compose where it is defined like this:

    reposilite:
      image: dzikoysk/reposilite:2.9.23
      container_name: reposilite
      command: java -Xmx16M -jar reposilite.jar
      ports: ["8081:80"]
      stdin_open: true
      tty: true

(2)
This is also possible without using socat, although it's less scriptable. One can attach directly

    docker attach reposilite <ENTER>

Then although no output is shown we're connected to the cli. We then run our command:

    keygen / admin m<ENTER>

It should output our data. We then need to quit, but notice that running `CTRL+C` will close the entire reposilite server and kill the container. So we run `CTRL+P+Q` (hold control, press p, press q, release). But note that this last key combination will not work under some circumstances, e.g. see [this SO discussion](https://stackoverflow.com/questions/41097652/how-to-fix-ctrlc-inside-a-docker-container)

**Comment by dzikoysk** [comment]
Good job! I think I'll provide some kind of a dedicated client that will connect to the Reposilite instance through the local socket to simplify this process.

**Comment by dzikoysk** [comment]
I'm thinking about various possibilities on how can I solve this issue (and related like #526). At first, I was thinking about a dedicated client such as `reposilite-ctl` or something similar. The problem is that I pretty much have to open socket or I need to move to some kind of a file based communication. I don't quite like this approach, so I was looking for a better option. 

@khmarbaise What do you think about something like:

```bash
# Reposilite will generate temporary token alias:token
$ java -jar reposilite.jar --defaultAuth alias@secret

# Now, through the REST execute any command supported by CLI
let result = HttpClient.post("http://localhost:8080/cli/execute", "keygen xyz")

# [Extra] To remove default auth, you can just restart Reposilite and run it without auth flag
$ java -jar reposilite.jar
```

Does something like this in your opinion solve related issues? 🤔
