### ISSUE TITLE
maven-metadata.xml can generate incorrectly with 'incorrect' urls.

### ISSUE THREAD

**Issue by LexManos** [dzikoysk/reposilite#480]
Sometimes incorrect urls can enter the system, such as //com/google/foo/maven-metadata.xml
This will cause the generated pom to have '.com.google' as the actifact's group. Note the extra .
This seems to only happen if the first request is the one with the extra /'s due to the caching.
I fixed it by just replacing the if in norrmalize to a while https://github.com/MinecraftForge/reposilite/commit/a4d392db0c853dfd19d45bd83055847bf308da2a tho it'd probably be better to sanitize all of the incoming uri's to clean variants before passing it to any processing code.

**Comment by dzikoysk** [comment]
Thanks, something like that should fix similar issues.
