### ISSUE TITLE
Periodic prefetch of proxied snapshot artifacts

### ISSUE THREAD

**Issue by henrik42** [dzikoysk/reposilite#501]
Repolite could check periodicly if a newer version of a SNAPSHOT (that was downloaded from the hosted/main repo before) exists. If so, it just downloads the newer version and puts it into the local cache.

I'm asking for the feature because I'm working in home office and we have tons of different SNAPSHOT artefacts that are built by Jenkins all the time. So when I do a "mvn compile", I have to wait for minutes until all SNAPSHOTs are downloaded. 

With the prefetch I would just use repolite and wouldn't have to wait anymore.

**Comment by dzikoysk** [comment]
Interesting idea, we can consider this in Reposilite 3.x. The first problem I see is probably the need of providing a configuration for scheduler (paths/artifacts to scan), because we just cannot scan whole repository content - it will just blow up for large repositories.

**Comment by henrik42** [comment]
I was thinking of just pulling on artefacts that have been requested for by a client (like mvn). So you would not need to read whole repos. Only those few artefacts that have been consumed by my mvn. This should be feasible.

**Comment by dzikoysk** [comment]
Every proxied artifact was requested at least once, so it should be filtered by some minimum threshold. E.g. scheduler will request stats module every hour to list all of the artifacts that have been requested at least X times and contains `SNAPSHOT` identifier (time and threshold configurable ofc) 🤔

**Comment by henrik42** [comment]
Should work.

I'm not sure though that you really need a threshold. I think it should suffice to have the scheduler just loop/iterate over all proxied snapshots and see, if there is a newer version. If so, download. So the rate that artifacts are built determines how often they are downloaded. Of course you can throttle the loop as to not overload the hosting/main server (like a sleep between each loop and/or each element).

Using a threshold to keep certain artifacts from being downloaded could be counterproductive. It could save some space but in what kind of szenario does this happen? I'm using a snapshot *once* and then not again? In my case - if I ever use a snapshot it's very likely that I will use it forever from that moment on. So there is little sense in not prefetching it I believe.

**Comment by henrik42** [comment]
Just a few more thoughts: a running prefetch-download should not block the prefetch-loop. So the download(s) should run concurrently to eachother and the loop should continue. Since downloads could take long or even block, one would have to apply some kind of timeout mechanism. The loop could even hit the same artifact again if the download takes long. So that must be considered.
When a client (mvn) requests an artifakt it could be, that the prefetch download is running. So one would have to decide on to either wait for the download to complete or to deliver the older/cached version.

**Comment by dzikoysk** [comment]
In general, I think that the issue addresses an edge case and the best way to achieve such a functionality is just to write some kind of a script that constantly iterates through remote repositories and requests these artifacts in Reposilite intance. 

The problem with this kind of scheduler is that in case of huge repositories that may contain tens of thousands of artifacts or even more, it just won't really work well. Endless loop iterating over all of the proxied artifacts won't be efficient and the outcome of this process is kinda random. Specifying these artifacts to scan (through list & regex) might be an option, but I have no idea when we could implement this - there is a lot of issues with higher priority atm.

**Comment by henrik42** [comment]
Makes sense. We have been using this for a moment

while true ; do mvn dependency:go-offline; sleep 30; done

This uses the "correct" dependencies since it uses the pom.xml and just pulls the dep'ies that I really need. The only drawback is, that it writes to the local maven repo and thus overwrites the JARs in there. It has no separate cache that we could swap in when we need to pull. So we could just use Repolite for this cache: i.e. constantly pull into Repolite cache and then do a mvn compile against the Repolite instance which will contain the latest snapshot then.

That's what you suggested above if I understand correctly.

**Comment by dzikoysk** [comment]
As we said before, this issue is kinda out of scope of the main codebase, but it could be solved in the future by planned plugin system - #555.
