### ISSUE TITLE
Pinned Snapshots

### ISSUE THREAD

**Issue by henrik42** [dzikoysk/reposilite#502]
I'd like to be able to specify which artefacts should be "pinned", i.e. eventhough there are newer versions in the hosted/main repo or even in local cache, any "read" from "mvn compile" will receive the same content on any request. 

This feature can help us to keep certain dependencies "stable". These SNAPSHOT dependencies/artefacts come from other teams and may contain breaking changes and bugs. My team members will opt-in to consume these SNAPSHOTs from time to time when it is somehow known, that those artefact versions "are good". Then they will "pin" these dependencies and from then on only consume newer version of un-pined artefacts from their own team (i.e. not all artefacts get pined).

So there would have to be a way to specify (via regex maybe) **groups of artefacts** (which I would name somehow - like "billing" oder "orders") and then to pin these. These groups make handling of pined artefacts easier. These "pin configurtions" should be shareable somehow. Maybe just present some JSON text to the user that can be sent by mail and then imported by others. Or read it from a file that could be shared via source control (git).

**Comment by dzikoysk** [comment]
As we said before, this issue is kinda out of scope of the main codebase, but it could be solved in the future by #555.
