### ISSUE TITLE
Swagger UI not working on 2.9.22

### ISSUE THREAD

**Issue by alexparlett** [dzikoysk/reposilite#513]
When starting with swagger enabled we get the following:

`09:16:28.311 WARN | No Server set for WebjarHandler@368247b9{STARTING}`

And it 404's trying to load the swagger-ui configuration.

This is using the docker image with just turning swagger on

**Comment by dzikoysk** [comment]
It looks like Javalin 4.x changed a little webjar handling 🤔 I think `domain.com/swagger-docs` should still be available anyway.

**Comment by dzikoysk** [comment]
Resolved with #473 on 3.0 branch.

Sorry for not porting fix to 2.x branch, but unfortunately I don't have time to apply patches on both branches (3.0 is not compatible anymore with current code base).
