### ISSUE TITLE
Disk Quota incorrectly inited when configured in percentages

### ISSUE THREAD

**Issue by timboven** [dzikoysk/reposilite#514]
You can configure a percentage for disk quota and while this works in the beginning (with an empty disk) - this suddenly stops working when the disk is more full (and reposilite restarts).

https://github.com/dzikoysk/reposilite/blob/e4c385657b4308d7f2ba873542916d16ea3df0bf/reposilite-backend/src/main/java/org/panda_lang/reposilite/repository/DiskQuota.java#L48 inits the disk quota with a percentage of the usable (free) disk capacity - while it should be inited with the total capacity of that disk - otherwise when you get some more artifacts on the disk and restart reposilite your percentage suddenly results in another quota and reposilite starts to reject new artifacts.

**Comment by dzikoysk** [comment]
Thanks, I didn't really notice this. The fix will be available in a next release :)
