### ISSUE TITLE
ARM64 Builds

### ISSUE THREAD

**Issue by davidfrickert** [dzikoysk/reposilite#516]
Is it possible to build this project's docker image in ARM64?

Would be interesting for deploying in Raspberry PIs, for example.

**Comment by dzikoysk** [comment]
I don't know, but in theory it should be possible, because it runs on Java which is supported on this platform as far as I know. RPI has kinda limited resources, wouldn't it just be a better option to just launch Reposilite through a script or something?

**Comment by dzikoysk** [comment]
Unfortunately, I'm using official Docker Hub integration for GitHub project and there is no way to support multiple targets. I'm also not in a position to guarantee that ARM platform is really supported. I think that if you/someone could prepare a valid `Dockerfile`, we could provide it in documentation section and then people can just built it locally.

**Comment by davidfrickert** [comment]
This seems to be working. 
Had to change maven to openjdk-15 since the current 14 does not have an ARM64 build and change the runtime from alpine to ubuntu, couldn't find any alpine openjdk with ARM64 build. Used a rather lightweight ubuntu based 15 JRE (~90MB).

Build locally in my raspberry pi and it built + started with no problems.
Want to add this to the repository, with a different name? Like Dockerfile-ARM64.
Or do you prefer to put it somewhere else as you don't plan to support it? - totally understandable, too bad that github integration doesn't support multi-arch builds.

```
# Build stage
FROM maven:3.6.3-openjdk-15-slim AS build
COPY ./ /app/
RUN mvn -f /app/pom.xml clean package

# Build-time metadata stage
ARG BUILD_DATE
ARG VCS_REF
ARG VERSION
LABEL org.label-schema.build-date=$BUILD_DATE \
      org.label-schema.name="Reposilite" \
      org.label-schema.description="Lightweight repository management software dedicated for the Maven artifacts" \
      org.label-schema.url="https://reposilite.com/" \
      org.label-schema.vcs-ref=$VCS_REF \
      org.label-schema.vcs-url="https://github.com/dzikoysk/reposilite" \
      org.label-schema.vendor="dzikoysk" \
      org.label-schema.version=$VERSION \
      org.label-schema.schema-version="1.0"

# Run stage
FROM adoptopenjdk:15.0.2_7-jre-hotspot
WORKDIR /app
RUN rm -rf /var/lib/apt/lists/* && mkdir -p /app/data
VOLUME /app/data
COPY --from=build /app/reposilite-backend/target/reposilite*.jar reposilite.jar
ENTRYPOINT exec java $JAVA_OPTS -jar reposilite.jar -wd=/app/data $REPOSILITE_OPTS
```

**Comment by dzikoysk** [comment]
Thanks! I think that the best place to put it is just the Docker section on Reposilite site:

* https://reposilite.com/docs/docker

If you'd like to make a contribution, you can add it here:

* https://github.com/dzikoysk/reposilite/blob/3.0/reposilite-site/docs/docker.md

We're during the 3.0 development, so to simplify this process we don't really push any non-security/bugs related commits to master atm. If you don't have time to make a contribution, I'll just do it a little bit later :)

**Comment by davidfrickert** [comment]
Yeah I can do it, no worries.
