### ISSUE TITLE
Locally talking to the daemon process once it has been started

### ISSUE THREAD

**Issue by daudo** [dzikoysk/reposilite#526]
This actually is more like a question, or maybe a feature request, depending how the question is answered :)

I'm currently packaging reposilite for FreeBSD and in the process of writing the rc.d script I am a little bit confused on how to stop the reposilite/java process in the expected way.

If I understand the docs correctly, ie https://reposilite.com/docs/install#interactive-cli, then the only way to talk to the server process is either via a local or remote CLI. The local CLI is started within the server process. Before doing all kinds of nasty workarounds with screen or alike, I'd like to know if there's a better approach to talk to the server process, to shut it down for example or also to create new tokens and so on.

One other option would probably be to use the remote CLI for local access as well, but that feels a little bit strange.

**Comment by dzikoysk** [comment]
Hi there,

Well, at this moment Reposilite supports only standard cli input and remote execution through the authorized http request. If we're talking about only shutting down the JVM, Reposilite uses shutdown hook, so you can also send shutdown request to this process. 

I'm not really familiar with the topic on "how we can communicate with a process on local machine", so I'm kinda open to proposals and some suggestions in this area. There are and were some related issues like this:

* https://github.com/dzikoysk/reposilite/issues/477

But I'm still not sure how the implementation should look like. In theory I could just open a listen on a new socket and then probably provide some dedicated client to interact with app locally, but I don't know if it's the best solution.

**Comment by daudo** [comment]
ok, thanks. For a start, it would be nice if the server process could be shut down gracefully using standard signals (ie. SIGTERM) .

Right now, if I send SIGTERM to the process, I see this:

```
LOGGER ERROR: Failed to write log entry 'Shutting down 0.0.0.0::8084 ...' (java.io.IOException: Stream Closed)
13:41:39.042 INFO | Shutting down 0.0.0.0::8084 ...
LOGGER ERROR: Failed to write log entry 'Stored records: 5' (java.io.IOException: Stream Closed)
13:41:39.098 INFO | Stored records: 5
```

Maybe it already shutdown down nicely and it's just the logger that is already gone at that stage, I can't say, but the message doesn't look convincing in terms of data integrity :)

The issue you mentioned #477 raises another problem yes, because if the initial token cannot be generated upfront, it will be difficult to use the remote CLI for local administration.

**Comment by dzikoysk** [comment]
This error is just a bug that is already resolved on 3.0:

* https://github.com/dzikoysk/reposilite/issues/411

Unfortunately, I don't have time to apply this fix to the 2.x branch. You may lost the last part of the log, but in the end I think it should work pretty well for you for now.

**Comment by daudo** [comment]
alright, I've managed to craft an rc.d service script for FreeBSD, allowing to control the server process locally. 

Before I start the packaging itself, I will probably write a little helper script, allowing to interact with the server's CLI without having to leave the shell (ie in order to perform commands like keygen, revoke etc.), superficially comparable to what apachectl does for the Apache httpd.

I take it, no one has ever produced such a script?

**Comment by dzikoysk** [comment]
If so, probably only for personal usage as nobody shared such a script in any issue as far as I remember.

**Comment by dzikoysk** [comment]
Closing in favor of #477
