### ISSUE TITLE
Authentication for private repositories does not work

### ISSUE THREAD

**Issue by daudo** [dzikoysk/reposilite#533]
I've created a private sandbox repository to play with, but I am unable to create a token to access it:

The relevant part my config.cdn looks like this:

```
repositories [
  .udosandbox
  releases
  snapshots
]
```

then I created a token to access the private repository:

```
keygen /udosandbox whoever w
20:44:12.765 INFO | 
20:44:12.905 INFO | Stored tokens: 7
20:44:12.907 INFO | Generated new access token for whoever (/udosandbox) with 'w' permissions
20:44:12.909 INFO | okZMFC0Jqujx8yg1YjUx84pl4ZD2hOJMXj7cAeDdlMtrka+D8pYxkhLliwO+Er3d
20:44:12.909 INFO | 

```

Now when I try to access the reposilite server with http://reposilite.example.com:8084/udosandbox, the browser asks for credentials using the browser native user credentials popup and when I enter them, I am redirected to the "Index of /udosandbox/" page, displaying an empty repository plus a a red "Unauthorized access" overlay on top:

![unauth](https://user-images.githubusercontent.com/360141/123689503-947c6e80-d853-11eb-893b-280bd1f17ba3.png)

The log then shows this:

```
20:48:40.808 DEBUG | LOOKUP /udosandbox from 10.9.0.6
20:48:40.808 DEBUG | Header ---
20:48:40.808 DEBUG | Accept: text/html,application/xhtml+xml,application/xml;q=0.9,image/webp,*/*;q=0.8
20:48:40.808 DEBUG | Upgrade-Insecure-Requests: 1
20:48:40.808 DEBUG | User-Agent: Mozilla/5.0 (X11; Linux x86_64; rv:89.0) Gecko/20100101 Firefox/89.0
20:48:40.809 DEBUG | Connection: keep-alive
20:48:40.809 DEBUG | Sec-GPC: 1
20:48:40.809 DEBUG | Host: reposilite.example.com:8084
20:48:40.809 DEBUG | Accept-Language: de-DE,en-US;q=0.7,en;q=0.3
20:48:40.809 DEBUG | Accept-Encoding: gzip, deflate
20:48:40.809 DEBUG | DNT: 1
20:48:40.809 DEBUG | Authorization credentials are not specified
20:48:51.790 DEBUG | LOOKUP /udosandbox from 10.9.0.6
20:48:51.790 DEBUG | Header ---
20:48:51.791 DEBUG | Authorization: Basic d2hvZXZlcjpva1pNRkMwSnF1ang4eWcxWWpVeDg0cGw0WkQyaE9KTVhqN2NBZURkbE10cmthK0Q4cFl4a2hMbGl3TytFcjNk
20:48:51.791 DEBUG | Accept: text/html,application/xhtml+xml,application/xml;q=0.9,image/webp,*/*;q=0.8
20:48:51.791 DEBUG | Upgrade-Insecure-Requests: 1
20:48:51.791 DEBUG | User-Agent: Mozilla/5.0 (X11; Linux x86_64; rv:89.0) Gecko/20100101 Firefox/89.0
20:48:51.792 DEBUG | Connection: keep-alive
20:48:51.792 DEBUG | Sec-GPC: 1
20:48:51.792 DEBUG | Host: reposilite.example.com:8084
20:48:51.793 DEBUG | Accept-Language: de-DE,en-US;q=0.7,en;q=0.3
20:48:51.793 DEBUG | Accept-Encoding: gzip, deflate
20:48:51.798 DEBUG | DNT: 1
20:48:52.051 INFO | AUTH whoever accessed /udosandbox
20:48:52.449 INFO | API /api/udosandbox/ from 10.9.0.6
20:48:52.450 DEBUG | Header ---
20:48:52.450 DEBUG | Authorization: Basic Og==
20:48:52.451 DEBUG | Accept: application/json, text/plain, */*
20:48:52.451 DEBUG | User-Agent: Mozilla/5.0 (X11; Linux x86_64; rv:89.0) Gecko/20100101 Firefox/89.0
20:48:52.451 DEBUG | Connection: keep-alive
20:48:52.452 DEBUG | Referer: http://reposilite.example.com:8084/udosandbox
20:48:52.452 DEBUG | Sec-GPC: 1
20:48:52.452 DEBUG | Host: reposilite.example.com:8084
20:48:52.453 DEBUG | Accept-Language: de-DE,en-US;q=0.7,en;q=0.3
20:48:52.453 DEBUG | Accept-Encoding: gzip, deflate
20:48:52.453 DEBUG | DNT: 1
20:48:52.454 DEBUG | Invalid authorization credentials
```

Any ideas what might be the problem?

**Comment by dzikoysk** [comment]
Hi there :)

It's not really a problem with Reposilite to be honest, it's a problem with a browser that shows up a login popup for sites that return `401 Unauthotrized` status code no matter why. More about the topic:

* https://github.com/dzikoysk/reposilite/issues/240

To see its content, just login using the dashboard. In Reposilite 3.0 UI won't be served through the same controller, so I think user won't receive this popup, but I'm still working on it, so we'll see.

**Comment by daudo** [comment]
hmm, ok, so what your are saying is that this is a particular problem with browsers. If I use maven for example to access this private repository using http://reposilite.example.com:8084/udosandbox/, it would work?

Going through the dashboard may be some workaround, but on the other hand it isn't very intuitive. Imagine I have this nice little private repository that I want to use in my maven project. So what I would be doing was to open the repository in the browser, copy it's URL and put that in my pom.xml. Unfortunately, when going through the dashboard, I get a URL that is not useable for maven (and I really don't want maven use the dashboard URL at all, actually).

Or am I missing something?

**Comment by daudo** [comment]
and one other observation: after having authenticated using the browser's native credentials popup, it does not reappear again. So it seems, the browser is happy after having been fed with the credentials, what fails then afterwards is the /api/udosandbox call:

![api_401](https://user-images.githubusercontent.com/360141/123704352-d9a99c00-d865-11eb-9dcd-8aaf7a9fde01.png)

Regarding Reposilite V3: any approximate ETA?

**Comment by dzikoysk** [comment]
>If I use maven for example to access this private repository using http://reposilite.example.com:8084/udosandbox/, it would work?

Yes, Maven should access repository content as long as you provide valid credentials.

> Going through the dashboard may be some workaround, but on the other hand it isn't very intuitive. [...]

It's more like a problem with a fact that Reposilite serves Maven repository under the same route as its UI. It means that when Reposilite have to notify Maven about the unauthorized access to the path it also responds with UI as a content of this error message. In a standard repository you'd just get an raw blank error page with a message like `404 not found` and that's all so it's more like a side effect that you see the UI and I agree - it's not very intuitive, but it's caused by the current design. As a workaround I could return 404 (or any other status code) instead of 401 and the browser won't ask you with this old builtin login popup, but I prefer to return a valid status code rather than modify the specification to get rid of this one.

**Comment by dzikoysk** [comment]
> Regarding Reposilite V3: any approximate ETA?

It's hard to say to be honest. I'm still working on it and there is still much work to do. Everything about it is here:

* https://github.com/dzikoysk/reposilite/issues/458

I'm going on a 3 weeks break in ~10.07.2021, so we will see if I'd be able to deliver at least some kind of an alpha release until this date.

**Comment by daudo** [comment]
alright, so closing this issue in favor of #240
