### ISSUE TITLE
What permissions does 'm' provide, that 'w' does not provide?

### ISSUE THREAD

**Issue by MisterBirs** [dzikoysk/reposilite#534]
In the introduction on the website it is written:
w - allows to write (deploy) using this token
m - marks token as manager token (full access)

But it is not written what allows full access, does anyone know how to answer that?

**Comment by dzikoysk** [comment]
You're right, I think it could be clarified with a better description. The manager permission not only allows you to access all of paths no matter what path you will associate with a token, but also you can access remote CLI through the dashboard.
