### ISSUE TITLE
Is there a way to disable automatic update checks?

### ISSUE THREAD

**Issue by Alexander-at-Blue** [dzikoysk/reposilite#538]
Hi, I'm running reposilite on a machine that have internet access firewalled by default. I believe that for this reason starting the console is taking a huuuuge time...

Is there a way to disable this update checking?
 or perhaps the status metrics is the issue?
 
 ```
 13:58:06.373 INFO |
13:58:06.374 INFO | Collecting status metrics...
13:58:06.374 INFO |
help keygen
14:00:14.404 INFO | Reposilite 2.9.23 Status
14:00:14.405 INFO |   Active: true
14:00:14.405 INFO |   Uptime: 2.14min
14:00:14.405 INFO |   Memory usage of process: 8.05M
14:00:14.405 INFO |   Disk usage: 132.4 MiB
14:00:14.405 INFO |   Cached metadata: 0
14:00:14.406 INFO |   Exceptions: 0
14:00:14.406 INFO |   Latest version of reposilite: https://repo.panda-lang.org/org/panda-lang/reposilite/latest is unavailable: Connection timed out (Connection timed out)
14:00:14.406 INFO |
14:00:14.419 INFO |
14:00:14.451 INFO | Usage:  keygen <path> <alias> [<permissions>]
14:00:14.451 INFO | Generate a new access token for the given path
14:00:14.451 INFO |       <path>            assigned path
14:00:14.451 INFO |       <alias>           associated alias
14:00:14.452 INFO |       [<permissions>]   extra permissions: m - manager, w - write r - read
14:00:14.452 INFO |                           (optional)
14:00:14.452 INFO |
```
(Takes 2 minutes to actually show a console prompt... )
I'm using reposilite 2.9.23

**Comment by dzikoysk** [comment]
By `Memory usage of process: 8.05M` I assume you've just let your instance quite small amount of memory. Could you try to increase available RAM?

**Comment by Alexander-at-Blue** [comment]
Hm... it has quite a small memory because it has very little usage... But sure, I can increase it. So, the fact that it is trying to fetch updates from a firewalled address doesn't affect this delay?

**Comment by Alexander-at-Blue** [comment]
I've updated -Xmx2048m , and here is the most recent output:

```
15:04:19.363 INFO |
15:06:27.397 INFO | Reposilite 2.9.23 Status
15:06:27.398 INFO |   Active: true
15:06:27.401 INFO |   Uptime: 2.14min
15:06:27.401 INFO |   Memory usage of process: 9.19M
15:06:27.401 INFO |   Disk usage: 132.4 MiB
15:06:27.401 INFO |   Cached metadata: 0
15:06:27.402 INFO |   Exceptions: 0
15:06:27.402 INFO |   Latest version of reposilite: https://repo.panda-lang.org/org/panda-lang/reposilite/latest is unavailable: Connection timed out (Connection timed out)
15:06:27.402 INFO |
```

Again the two minutes. Probably because of that https://repo.panda-lang.org access that can't be done from my server? 
Although I don't know what statistics are being collected.

```
 00:00:04 /opt/is/default-java/jre/bin/java -Xmx2048M -DINTEGRATION_SERVICES_PROCESS_SIGNATURE=REPOSILITE -Dtinylog.configuration=/var/is/REPOSILITE/tinylog.properties -jar reposilite-2.9.23.jar
```

**Comment by dzikoysk** [comment]
It only checks the latest version and that's all. Looks like this request was sync on 2.x and it blocks startup as you said. As I'm currently unavailable due to #535 I'm not able to improve this. I'm also working on 3.x so I'll keep this issue open to make sure that it'll be fixed. 

As a workaround you can just fork this project and remove 'status' command call at startup and then build the application using 'mvn clean package' command.
