### ISSUE TITLE
Documentation - on how Reposilite is working

### ISSUE THREAD

**Issue by khmarbaise** [dzikoysk/reposilite#54]
* It would be great to have documentation on how repositories are created by default? 
* What can be configured in the `nanomaven.yml` ?

**Comment by dzikoysk** [comment]
* Permissions are granted by assigning an alias to the path ([README#Guide](https://github.com/dzikoysk/nanomaven#guide). For instance:
  * Typical admin account would be assigned to the `/` path
  * NanoMaven developer would be assigned to the `/releases/org/panda-lang/nanomaven` path
Users are allowed to do whatever they want as long as their actions are performed in the associated directory (path).

* Configuration was simplified in #35 and it is how it looks: https://github.com/dzikoysk/nanomaven/blob/master/src/main/resources/nanomaven.yml

**Comment by khmarbaise** [comment]
Don't get me wrong but you are closing the issues very fast without really answering things. From users point of view I would like to have a documentation which shows what/and how the configuration can be done and what the consequences are. I don't want to start reading the code and trying to understand how the code work to get an impression what I can configured.

Furthermore can I define repos with a given path? The path is relative based on the startup of the server? Can I put artifacts into the repositories according to GAV etc. ? How? Can I simply copy artifact into the repository? Do I need to restart the server if new artifacts have been added?

**Comment by dzikoysk** [comment]
The status of issue depends on the purpose, do not worry about it. The overall documentation might be a good idea, probably using the Wiki section on GitHub.

Yeah, the path is relative and nanomaven will use data from current working directory. You can manually put artifacts in the `repository` directory according to GAV. The only thing stored by NanoMaven at runtime is cache of generated `maven-metadata.xml` files, so if you will change sth, it might be a good idea to call `purge` command as long as you don't want to restart your application.

**Comment by dzikoysk** [comment]
#79
