### ISSUE TITLE
ICP license (Bei'An) information configuration

### ISSUE THREAD

**Issue by MiniDay** [dzikoysk/reposilite#541]
In China, all websites need to submit the website operation information to the government, and then get an ICP (Internet content provider) certificate issued by the government.

Each website must mark its own ICP ID at the bottom, otherwise the website may be forcibly shut down.

I set up my own reposilite in China. It's really good. I like it very much. But I was told that I had to declare my website to the government to keep it running.

Obviously, reposilite can neither kill nor sell drugs, so I soon got my ICP certificate.

Now I just need to do one thing, put the ICP ID at the bottom of my website page.

But this baffles me. I can't modify the HTML file of reposite myself.

So I would like to ask if the author can add an option to the configuration file so that Chinese users can configure their own ICP ID?

This should not be difficult, just add a line of optional information to the configuration:

```
beian: 国ICP备123000321号
```

Then, when it is recognized that the entry is set, a text will be added at the bottom of the website that will jump to the government ICP query page when clicked.

```html
<a href="https://beian.miit.gov.cn/#/Integrated/recordQuery" target="_blank">国ICP备123000321号</a>
```

My English is not good, but I try my best to convey my intention to you. If my words make you angry, please forgive me. thank you.

**Comment by MiniDay** [comment]
Here are some other website pages from China. Maybe we can refer to them.

[https://www.baidu.com/](https://www.baidu.com/) The most commonly used search engine in China is similar to Google.
![1.png](https://i.loli.net/2021/07/23/I6p1KyTsC9Et3km.png)
[https://gitee.com/](https://gitee.com/) In addition to GitHub, another code hosting website most commonly used in China
![2.png](https://i.loli.net/2021/07/23/ejQWfqIp386zlZv.png)
[https://www.57block.cn/](https://www.57block.cn/) My other website, it has obtained a legal certificate.
![3.png](https://i.loli.net/2021/07/23/AfBNe5vLPxurWwM.png)

**Comment by dzikoysk** [comment]
Hi @MiniDay 

It's quite strange that you have to add such a certificate to your website 🤔. At this moment I'm not as active due to #535. Also, Reposilite 2.x is not actively developed (I'm working on a 3.0 and I don't have enough time to develop both branches). I'll mark it as enhancement to make sure that such an option will be available in 3.x.

Because you need it now, I may suggest a workaround. Open the latest version of Reposilite as a zip archive and go to `reposilite-2.9.23.jar\static\index.html` and just modify this file.

![image](https://user-images.githubusercontent.com/4235722/126790721-39f9c883-08e1-4c44-b63a-5eef3bb50985.png)

I think this quick fix should work for you as long as Reposilite doesn't support this out of the box :)

**Comment by MiniDay** [comment]
> Hi @MiniDay
> 
> It's quite strange that you have to add such a certificate to your website 🤔. At this moment I'm not as active due to #535. Also, Reposilite 2.x is not actively developed (I'm working on a 3.0 and I don't have enough time to develop both branches). I'll mark it as enhancement to make sure that such an option will be available in 3.x.
> 
> Because you need it now, I may suggest a workaround. Open the latest version of Reposilite as a zip archive and go to `reposilite-2.9.23.jar\static\index.html` and just modify this file.
> 
> ![image](https://user-images.githubusercontent.com/4235722/126790721-39f9c883-08e1-4c44-b63a-5eef3bb50985.png)
> 
> I think this quick fix should work for you as long as Reposilite doesn't support this out of the box :)

ok，thanks!

**Comment by dzikoysk** [comment]
The official name of this mechanism is called ICP license:

* https://en.wikipedia.org/wiki/ICP_license

We should use this name rather than `Bei'An` as a configuration property name.

**Comment by MiniDay** [comment]
> The official name of this mechanism is called ICP license:
> 
> * https://en.wikipedia.org/wiki/ICP_license
> 
> We should use this name rather than `Bei'An` as a configuration property name.

Although ICP is the official name of this mechanism, few people use it in China. 
Although ICP is the official name of this mechanism, almost no one uses it in China. 
I have no objection to using this name, but it is best to write clearly the purpose of the ICP parameter in the comments. In addition, most people may not understand what ICP is.

like this
```
# the Internet Content Provider License
# Web services in Chinese mainland require ICP permission, otherwise the website will not be accessible.
# In order for the website to be accessed normally, you should apply for ICP license from your service provider and fill in this parameter.
# Or use servers in non mainland areas such as Hong Kong.
# For more information about this parameter, see https://baike.baidu.com/item/%E5%A4%87%E6%A1%88/5130430
ICPLicense: 国ICP备123000321号
```

It's worth mentioning that even if you don't like the link in the comment, don't replace it with Wikipedia.
Because China blocked the website, we can't access it.

**Comment by dzikoysk** [comment]
Oh, I didn't know it's blocked, thanks for details. I'll definitely provide an extended description with the original name.

**Comment by MiniDay** [comment]
> Oh, I didn't know it's blocked, thanks for details. I'll definitely provide an extended description with the original name.

OK, thank you.

But don't worry. Although GFW limits the network range of many Chinese people, most of the Chinese people you can see on the network have mastered the technology to bypass GFW, especially in GitHub.
