### ISSUE TITLE
Restrict artifact overwriting

### ISSUE THREAD

**Issue by alexparlett** [dzikoysk/reposilite#542]
In some areas that we are using reposilite we want to ensure users/customers cannot deploy an artifact which would overwrite an existing artifact.

Is this something we could look at adding on a general or repository level?

**Comment by dzikoysk** [comment]
Unfortunately, at this moment there is no such a possibility :/ It'll be available in Reposilite 3.0 (#395)

**Comment by dzikoysk** [comment]
If it's must have for you, I may suggest making a fork and just simply adding a check here somewhere here:

* https://github.com/dzikoysk/reposilite/blob/8e44bd801fba64b6c0ce6a4558508788842024e5/reposilite-backend/src/main/java/org/panda_lang/reposilite/repository/DeployService.java#L85

Checking if the file already exists (and it's not metadata file) should be probably fine.
