### ISSUE TITLE
Incomplete pom content sent on Gradle

### ISSUE THREAD

**Issue by MiniDay** [dzikoysk/reposilite#549]
I got an error when I tried to build my own project using gradle:
```
* What went wrong:
Execution failed for task ':api-bukkit:compileJava'.
> Could not resolve all files for configuration ':api-bukkit:compileClasspath'.
   > Could not resolve com.comphenix.protocol:ProtocolLib:4.7.0.
     Required by:
         project :api-bukkit
      > Could not resolve com.comphenix.protocol:ProtocolLib:4.7.0.
         > Could not parse POM https://maven.airgame.net/hamster-repo/com/comphenix/protocol/ProtocolLib/4.7.0/ProtocolLib-4.7.0.pom
            > XML 文档结构必须从头至尾包含在同一个实体内。

* Try:
Run with --info or --debug option to get more log output. Run with --scan to get full insights.
```

and i run with `--stacktrace`
```
Caused by: org.gradle.internal.resolve.ModuleVersionResolveException: Could not resolve com.comphenix.protocol:ProtocolLib:4.7.0.
Caused by: org.gradle.api.internal.artifacts.ivyservice.ivyresolve.parser.MetaDataParseException: Could not parse POM https://maven.airgame.net/hamster-repo/com/comphenix/protocol/ProtocolLib/4.7.0/ProtocolLib-4.7.0.pom
```

```
Caused by: org.xml.sax.SAXParseException; systemId: file:/C:/Users/MiniDay/.gradle/caches/modules-2/files-2.1/com.comphenix.protocol/ProtocolLib/4.7.0/895e366c727d74d720b981cdd3d2e66ca5fa0f6e/ProtocolLib-4.7.0.pom; lineNumber: 79; columnNumber: 4; XML 文档结构必须从头至尾包含在同一个实体内。
```
The error message told me: The structure of the XML document must be contained in the same entity from beginning to end.

So I opened my file browser and found that file to view it. It was found to be wrong: the entire file was intercepted directly after line 78.

Then I went back to my server to check this file, I found that the file on the server is complete, it has a size of 10kb, but I downloaded to the local through gradle only 3kb.

I thought there was something wrong with the server, so I deleted the file on the server and the local file, and then rebuilt the project so that it would download the file again.

However, even if I did this, the same problem still occurred.

So I tried to manually copy the file on the server directly and overwrite the local file. Rebuild the project again, the result was successful.

Okay, so I now infer that some accident happened when reposilite was transferring this file, which caused it to break the http link at the incorrect time? Or what kind of content does reposilite think it should only send?
In any case, I think this problem should be caused by the incomplete content that my gradle received from reposilite.

Finally, the version I used:
Gradle: 7.0.2
reposilite: 2.9.23

`reposilite mirrors of: `
```
  https://repo.dmulloy2.net/repository/releases
  https://repo.dmulloy2.net/repository/snapshots
```

`gradle dependencies:`
```
compileOnly 'com.comphenix.protocol:ProtocolLib:4.7.0'
```

**Comment by dzikoysk** [comment]
Could you send me the raw pom that caused this issue? I guess it might be some kind of a problem with encoding related to Chinese symbols, so also check the encoding of this file.

**Comment by dzikoysk** [comment]
Reposilite properly receives this file and serves it:

<details>

  ![image](https://user-images.githubusercontent.com/4235722/129174281-a30ec85c-8146-4e51-8fff-73b2e9de53e2.png)

</details>

I also played around various encodings and it's just fine. So on, I've tried to reproduce your proxying setup and yes, the proxied file is broken:

<details>

* https://repo.dmulloy2.net/repository/releases/com/comphenix/protocol/ProtocolLib/4.7.0/ProtocolLib-4.7.0.pom

![image](https://user-images.githubusercontent.com/4235722/129175786-564f029e-a03d-4890-b52b-dc0b9571ee8d.png)

</details>

I've found out that Jetty (or maybe a client) for some reason breaks the connection during the file transfer of proxied content. The proxied file on disk is correct, so if you'll reload the page and request it again you should receive proper response.

**Comment by dzikoysk** [comment]
Ok, in my opinion it's more like a Nexus bug rather than Reposilite. Nexus sends incorrect `Content-Length` header for an incomplete chunked responses which Reposilite redirects in standard responses and that causes problem, because client closes connection at fixed source length. I'm going to add a workaround and release Reposilite 2.9.24

**Comment by MiniDay** [comment]
I noticed a situation:

When I use
```
    maven {
        url = "https://maven.airgame.net/hamster-repo"
    }
```
 [https://maven.airgame.net/hamster-repo/com/comphenix/protocol/ProtocolLib/4.7.0/ProtocolLib-4.7.0.pom](https://maven.airgame.net/hamster-repo/com/comphenix/protocol/ProtocolLib/4.7.0/ProtocolLib-4.7.0.pom) The file is indeed corrupted.

But when I use

```
    maven {
        url = "https://maven.airgame.net/maven-public"
    }
```

 [https://maven.airgame.net/maven-public/com/comphenix/protocol/ProtocolLib/4.7.0/ProtocolLib-4.7.0.pom](https://maven.airgame.net/maven-public/com/comphenix/protocol/ProtocolLib/4.7.0/ProtocolLib-4.7.0.pom) The file can be transferred normally.

and this is my reposilite config:

```
# ~~~~~~~~~~~~~~~~~~~~~~ #
#       Reposilite       #
# ~~~~~~~~~~~~~~~~~~~~~~ #

# Hostname
hostname: 0.0.0.0
# Port to bind
port: 8081
# Custom base path
basePath: /
# Any kind of proxy services change real ip.
# The origin ip should be available in one of the headers.
# Nginx: X-Forwarded-For
# Cloudflare: CF-Connecting-IP
# Popular: X-Real-IP
forwardedIp: X-Forwarded-For
# Enable Swagger (/swagger-docs) and Swagger UI (/swagger)
swagger: true
# Debug
debugEnabled: false

# Support encrypted connections
sslEnabled: false
# SSL port to bind
sslPort: 443
# Key store file to use.
# You can specify absolute path to the given file or use ${WORKING_DIRECTORY} variable.
keyStorePath: ${WORKING_DIRECTORY}/keystore.jks
# Key store password to use
keyStorePassword: ""
# Redirect http traffic to https
enforceSsl: false

# Control the maximum amount of data assigned to Reposilite instance
# Supported formats: 90%, 500MB, 10GB
diskQuota: 85%
# List of supported Maven repositories.
# First directory on the list is the main (primary) repository.
# Tu mark repository as private, prefix its name with a dot, e.g. ".private"
repositories [
  maven-public
  hamster-repo
]
# Allow to omit name of the main repository in request
# e.g. /org/panda-lang/reposilite will be redirected to /releases/org/panda-lang/reposilite
rewritePathsEnabled: true
# Accept deployment connections
deployEnabled: true

# List of proxied repositories.
# Reposilite will search for an artifact in remote repositories listed below,
# if the requested artifact was not found.
proxied [
  https://repo1.maven.org/maven2
  https://repo.maven.apache.org/maven2
  https://hub.spigotmc.org/nexus/content/repositories/snapshots
  https://repo.mikeprimm.com
  https://repo.extendedclip.com/content/repositories/placeholderapi
  https://repo.dmulloy2.net/repository/releases
  https://repo.dmulloy2.net/repository/snapshots
  https://mvn.lumine.io/repository/maven-releases
  https://mvn.lumine.io/repository/maven-snapshots
  http://nexus.hc.to/content/repositories/pub_releases
  http://nexus.hc.to/content/repositories/pub_snapshots
  https://oss.sonatype.org/content/repositories/snapshots
  https://maven.fabricmc.net
  https://repo.spongepowered.org/maven
  https://libraries.minecraft.net
  https://repo.velocitypowered.com/snapshots
  https://jitpack.io
]
# Reposilite can store proxied artifacts locally to reduce response time and improve stability
storeProxied: true
# Proxying is disabled by default in private repositories because of the security policy.
# Enabling this feature may expose private data like i.e. artifact name used in your company.
proxyPrivate: false
# How long Reposilite can wait for establishing the connection with a remote host. (In seconds)
proxyConnectTimeout: 3
# How long Reposilite can read data from remote proxy. (In seconds)
# Increasing this value may be required in case of proxying slow remote repositories.
proxyReadTimeout: 15

# Title displayed by frontend
title: 叁只仓鼠的Maven仓库
# Description displayed by frontend
description: 叁只仓鼠的公共Maven仓库
# Accent color used by frontend
accentColor: #2fd4aa
```

That artifact only exists in `maven-public`, but I can get it in `hamster-repo`. I thought this was a feature of repository, so I used it all the time.

**Comment by dzikoysk** [comment]
Reposilite 2.9.24 should support these broken Nexus repositories:

* https://github.com/dzikoysk/reposilite/releases/tag/2.9.24

**Comment by MiniDay** [comment]
okay, thanks! It works

**Comment by dzikoysk** [comment]
Thanks for feedback! :)
