### ISSUE TITLE
Support for proxy repositories

### ISSUE THREAD

**Issue by khmarbaise** [dzikoysk/reposilite#55]
Do I correctly understand that the proxy repository currently is not working which means I can't use it a replacement for a Nexus/Artifactory ?

**Comment by dzikoysk** [comment]
Yeah, at this moment you cannot proxy other repository through the NanoMaven. You can use it only as a standalone repository manager. 

The proxy feature is requested (e.g. https://github.com/dzikoysk/nanomaven/issues/22#issuecomment-629179204) and should be available in a near future.

**Comment by khmarbaise** [comment]
Ok that means I have understood the information in the `README.md` correct. That's fine. It's really interesting project for me cause I'm searching for a lightweight solution to use a repository manager in [my testing framework](https://github.com/khmarbaise/maven-it-extension).
