### ISSUE TITLE
Make console prompt with $ sign

### ISSUE THREAD

**Issue by BD103** [dzikoysk/reposilite#638]
Right now, the console just has a blank line when it prompts you to enter commands

In your documentation, you insert a `$` in front of the commands. It would be nice if you just printed `$ ` before allowing input

**Comment by dzikoysk** [comment]
It might be a good idea, but I've experienced various bugs trying to combine logging libraries and standard output reading with prefix in the past, so I can't promise if it'll be finally implemented. I hope that with:

* https://github.com/reposilite-playground/journalist

It might work better than with a raw logging libs.

**Comment by dzikoysk** [comment]
As we're slowly moving away from CLI with just a better UI, I think this kind of change is not really needed, so I'm closing this for now
