### ISSUE TITLE
Port already in use

### ISSUE THREAD

**Issue by NellexBEST** [dzikoysk/reposilite#647]
Exception occurred during the task execution: java.lang.RuntimeException: Port already in use. Make sure no other process is using port 80 and try again.

**Comment by dzikoysk** [comment]
You have to select another port in configuration, because your `*:80` is already taken - probably because of some proxy service like Nginx. If you'd like to proxy Reposilite, take a look on:

* https://reposilite.com/docs/reverse-proxy
