### ISSUE TITLE
error docker

### ISSUE THREAD

**Issue by NellexBEST** [dzikoysk/reposilite#648]
root@nellex:/var/www/repo# docker pull dzikoysk/reposilite
Using default tag: latest
Error response from daemon: manifest for dzikoysk/reposilite:latest not found: manifest unknown: manifest unknown
root@nellex:/var/www/repo#

**Comment by dzikoysk** [comment]
Hi @NellexBEST,

Reposilite does not offer `latest` builds. Use fully qualified version identifier instead, you can find full list here:

* https://hub.docker.com/repository/docker/dzikoysk/reposilite/tags
