### ISSUE TITLE
Reimplement Card component

### ISSUE THREAD

**Issue by dzikoysk** [dzikoysk/reposilite#668]
**Component**

* https://github.com/dzikoysk/reposilite/blob/main/reposilite-frontend/src/components/browser/Card.vue

**Context**

In various situations `Card.vue` component behaves differently.

cc: @wvffle

**Comment by dzikoysk** [comment]
Invalid padding after page reload:

![image](https://user-images.githubusercontent.com/4235722/134422596-88264a83-0a5c-4cc7-a19e-4c7c22dc32de.png)

**Comment by dzikoysk** [comment]
Cannot select whole snippet:

![image](https://user-images.githubusercontent.com/4235722/134422711-4bd26f4e-3a41-44c1-84a2-afb4f6e8ff79.png)

**Comment by wvffle** [comment]
I can do it!

**Comment by wvffle** [comment]
> Invalid padding after page reload:
> 
> ![image](https://user-images.githubusercontent.com/4235722/134422596-88264a83-0a5c-4cc7-a19e-4c7c22dc32de.png)

This seems like a problem with the tabs component

**Comment by wvffle** [comment]
> Cannot select whole snippet:
> 
> ![image](https://user-images.githubusercontent.com/4235722/134422711-4bd26f4e-3a41-44c1-84a2-afb4f6e8ff79.png)

And this is definately an editor component error

**Comment by dzikoysk** [comment]
Both libraries kinda suck so feel free to use alternative solutions
