### ISSUE TITLE
Private Repository not shown as manager

### ISSUE THREAD

**Issue by SomeOverflow** [dzikoysk/reposilite#692]
### What happened?

I generated an manager token with token-generate -s test test m and route-add test /private r & w but it is still not showing:

![grafik](https://user-images.githubusercontent.com/66356230/134810259-66e2acb6-8a72-47b3-84ec-d22fa01a5bf3.png)

(I am logged in)
And if i go over link to private (https://repo.example.com/#/private) there comes this:

![grafik](https://user-images.githubusercontent.com/66356230/134810293-96ecd119-65cb-47e9-9165-ab8eae11b71c.png)

### Reposilite version

3.x

**Comment by dzikoysk** [comment]
Should be fixed in https://repo.panda-lang.org/snapshots/org/panda-lang/reposilite/3.0.0-alpha.1-SNAPSHOT/reposilite-3.0.0-alpha.1-20210926.164519-1-all.jar :)
