### ISSUE TITLE
Reposilite 3.0.0-alpha.1 in docker container not reachable from host

### ISSUE THREAD

**Issue by Saladoc** [dzikoysk/reposilite#713]
### What happened?

I set up a docker container with the dzikoysk/reposilite:3.0.0-alpha.1 image and exposed the port.

Expected outcome:
 - reposilite is reachable from the browser
 - curl localhost:8081/ will yield some html output (from host)
 - curl localhost:8081/ will yield some html output (from container)

Actual outcome:
 - browser connection dies
 - curl from host exits with code 52 "Empty reply from server"
 - curl from container succeeds with results as expected

Conclusion: Likely an issue with the docker image.

Version info: 
macOS Big Sur 11.6
Docker Engine 20.10.8
reposilite 3.0.0-alpha.1
curl 7.64.1
firefox 92.0.1

### Reposilite version

3.x

### Relevant log output

```shell
➜  ~ docker run --name=reposilite-test-v3 -p 8081:80 -d dzikoysk/reposilite:3.0.0-alpha.1
9c1534d8b993c8ffd43b347a4b6a9dd80473f38fb3311f6ee317b62dd7117e15
➜  ~ curl localhost:8081/
curl: (52) Empty reply from server
```

**Comment by Saladoc** [comment]
I have identified a cause / fix: in the config file, hostname is set to `127.0.0.1` by default. Setting it to `0.0.0.0` instead fixed the issue. 
Imho a docker image should work out of the box for a quick and dirty test though, so I'd recommend changing the default config or giving a different default config for the docker image.

**Comment by dzikoysk** [comment]
Yeah, I think we can use `0.0.0.0` as default hostname. Do you want to make a PR to `Configuration.kt`? :)

**Comment by Saladoc** [comment]
I can do that, yes.
