### ISSUE TITLE
Allow default options for proxied repositories

### ISSUE THREAD

**Issue by Saladoc** [dzikoysk/reposilite#721]
### Request details

Especially when using reposilite as a mirror, there might be multiple proxied repositories. From a configuration standpoint, it makes sense to define custom defaults for those repository options that override the system defaults, but are in turn overriden by flags on the configured repositories. Since picocli provides excellent support for negatable option flags, this can also easily be done with the `--store` flag.

The current configuration
```
proxied [
   https://slow.repo/we/want/to/cache --store --connectionTimeout=15 --readTimeout=30
   https://slow.repo/we/rarely/need --connectionTimeout=15 --readTimeout=30
   https://fast.repo/we/still/cache --store
]
```

would then be equivalent to
```
storeProxied: true
proxiedConnectionTimeout: 15
proxiedReadTimeout: 30

proxied [
   https://slow.repo/we/want/to/cache
   https://slow.repo/we/rarely/need --no-store
   https://fast.repo/we/still/cache --connectionTimeout=3 --readTimeout=15
]
```

**Comment by dzikoysk** [comment]
It was considered during the reimplementation of proxy configuration and we've finally agree it's not a good idea. The main problem is that further expansion will add a lot fields to every repository section that will make configuration really big and hard to read. The second argument was that it's not that clean either - providing custom values and then negating them just makes it more complicated rather than explicitly define these value for each repo 🤔

**Comment by Saladoc** [comment]
Truth be told, I only needed a way to apply `--store` by default and expanded the suggestion. I wanted a way to separate the concerns, that traits for all proxied repos can be given in advance and the `proxies` list then needs to contain nothing but the urls, since I figured this would save trouble when editing/managing the config through an external tool that can not be simply be instructed to append `--store` to all list elements. I'm with you that this might complicate the config file if you set different defaults and then negate them, but my focus was rather on configuring all proxied repos at once.

The negation I only brought up because it would ensure the new system would be equally powerful to the old one.

**Comment by dzikoysk** [comment]
As the shared configuration is slowly becoming a part of dashboard just like the standard setting page in every webapp, I'd say this issue addresses slightly deprecated approach to configure the instance. Thanks for
