### ISSUE TITLE
 Responsive UI

### ISSUE THREAD

**Issue by dzikoysk** [dzikoysk/reposilite#743]
### Request details

Well...

![Screenshot_2021-10-02-03-30-35-52](https://user-images.githubusercontent.com/4235722/135699683-7ffdd7bc-a2ac-4a55-9b8a-d62808cfb25c.jpg)

**Comment by sudhinm** [comment]
can I pick this?

**Comment by dzikoysk** [comment]
Feel free to contribute! :) This issue addresses a few problems, so remember that we prefer small changes in multiple standalone PRs rather than one big PR.

**Comment by dzikoysk** [comment]
Another issue:

![image](https://user-images.githubusercontent.com/4235722/135926917-8aa8cd05-0f9e-47eb-8664-a5148cbc065a.png)

**Comment by sudhinm** [comment]
Cool..got it..thanks

**Comment by dzikoysk** [comment]
I've found that we're missing a font in code snippets on your platform. 

![Screenshot_2021-10-08-09-21-14-28](https://user-images.githubusercontent.com/4235722/136514863-a3413f87-8f78-447b-ad0b-dc6fc1c931db.jpg)

It should be much more smooth like on the screen.
