### ISSUE TITLE
Channel filters does not match messages in production env

### ISSUE THREAD

**Issue by dzikoysk** [dzikoysk/reposilite#744]
### What happened?

All messages are counted as `Other`

![image](https://user-images.githubusercontent.com/4235722/135714370-81259150-7204-48fc-b25e-553f78e019e3.png)
![image](https://user-images.githubusercontent.com/4235722/135714400-582594b5-790e-4d67-8c48-8a4e0f00d568.png)

### Reposilite version

3.x

**Comment by jolheiser** [comment]
I'll try and take a look at this tonight. 👍
