### ISSUE TITLE
Project website

### ISSUE THREAD

**Issue by dzikoysk** [dzikoysk/reposilite#79]
https://reposilite.com

**Comment by dzikoysk** [comment]
Project website should be located in `reposilite-site` module

**Comment by dzikoysk** [comment]
Content:
* Index
* Download & Installation
* Docs

**Comment by eshepelyuk** [comment]
@dzikoysk currently https://reposilite.com it redrecting here 
is it ok ?

**Comment by dzikoysk** [comment]
Yeah, reposilite does not have a dedicated website at this moment and it is why this issue is still open. I'm a little busy in recent weeks, but it is a next goal for this project.
