### ISSUE TITLE
Support custom mount directory per each repository using FS storage

### ISSUE THREAD

**Issue by dzikoysk** [dzikoysk/reposilite#825]
### Request details

```storageProvider: fs --quota 100% --mount /mnt/proxied-repo```

**Comment by ChanthMiao** [comment]
Can I assign storageProvider to proxied repo? This would allow reposilite to store upstream caches in a different location rather than mixed with self hosted packages.

**Comment by dzikoysk** [comment]
@ChanthMiao Currently it's not possible, but it's an interesting idea for a new issue :)

**Comment by ChanthMiao** [comment]
> @ChanthMiao Currently it's not possible, but it's an interesting idea for a new issue :)

Thanks for reply. I just open a new issue #913
