### ISSUE TITLE
Option to download proxied dependencies to reposilite server

### ISSUE THREAD

**Issue by ruzkant** [dzikoysk/reposilite#85]
The idea is that when a request is made for a dependency that exists in a proxied repository, that it is downloaded and stored on the file system where reposilite is running. 

This is not just for download performance, it means that all internal developers are guaranteed to always get the same jar irrespective of what happens on the remote repository (eg. someone managing to replace a dependency with a rogue version). So it enhances traceability and security.

**Comment by dzikoysk** [comment]
This option probably requires some strict limitation rules like:

* Max size of artifact to store
* Limited disk space to use

Any extra thoughts on that? 🤔

**Comment by ruzkant** [comment]
Apologies for the late reply. 

Artifactory has an optional quota control, which by default at 85% full for the storage partition gives a warning, and 95% refuses to accept more. Both values configurable. It also has a clean up option for unused artifacts, which I am not sure how it works.

It rejects with "too large" responses if one tries to publish more artifacts. Not sure what it does in terms of cached downloads, probably just delivers without caching I would guess.

Seems like a reasonable approach.
