### ISSUE TITLE
Root (/) of Reposilite responds with 203 Non Authoritative Information

### ISSUE THREAD

**Issue by fsjovatsen** [dzikoysk/reposilite#897]
### What happened?

When accessing the Reposilite interface it responds with 203 and not 200. This creates problems in environments with strict security policies.

![image](https://user-images.githubusercontent.com/6375784/139923911-0f6bac29-dd51-45b7-826e-e132e4b57e60.png)

This happens if we go directly to Reposilite with no proxy in between. Is there a way to fix this?

Frode

### Reposilite version

2.x

**Comment by dzikoysk** [comment]
Reposilite 2.x sends this status code for invalid Maven requests:

https://github.com/dzikoysk/reposilite/blob/f47607e1113df0191867a6c66308bc28c6424b9b/reposilite-backend/src/main/java/org/panda_lang/reposilite/repository/LookupService.java#L84

https://github.com/dzikoysk/reposilite/blob/f47607e1113df0191867a6c66308bc28c6424b9b/reposilite-backend/src/main/java/org/panda_lang/reposilite/repository/LookupService.java#L120

And without modifying sources you can change it. I agree it's not the best code, but in the end it still should be a valid response.
