### ISSUE TITLE
Login notification shows 2 times each time login button is clicked

### ISSUE THREAD

**Issue by FrankHeijden** [dzikoysk/reposilite#899]
### What happened?

The login button can be spam clicked, and each time it is clicked, the login notification shows up twice the amount of times clicked. One click results in the following notifications:
<img width="362" alt="Screenshot 2021-11-06 at 21 39 25" src="https://user-images.githubusercontent.com/22407829/140623204-508d43b9-88fc-4e4f-ad3f-cb1857b7f2f1.png">

The same happens for invalid logins:
<img width="352" alt="Screenshot 2021-11-06 at 21 41 39" src="https://user-images.githubusercontent.com/22407829/140623224-2d4450be-8dd3-4815-9c76-59b1862a2ff0.png">

### Reposilite version

3.x

### Relevant log output

```shell
-
```

**Comment by WithoutAName25** [comment]
I fixed this already here: #823
However, it is not yet included in the latest version, but should be included in the next alpha

**Comment by dzikoysk** [comment]
Resolved by https://github.com/dzikoysk/reposilite/releases/tag/3.0.0-alpha.8
