### ISSUE TITLE
Browsing from Overview page

### ISSUE THREAD

**Issue by jwc65** [dzikoysk/reposilite#912]
### What happened?

When trying to browse my repository from the web interface I seem to get to the 4th layer before it infinitely repeats the same directory. Screenshot below.
Have tried in other repositories and see the same result.

Pulling from the repo works correctly so appears to just be a display issue.

Version 3.0.0-alpha.8 Docker image

https://i.imgur.com/NbMBgSH.png

Happy to provide any logs, just let me know what you need.

### Reposilite version

3.x

**Comment by dzikoysk** [comment]
Hi, I can't quite reproduce this:

![image](https://user-images.githubusercontent.com/4235722/141528091-591e0d96-3705-44c4-aaed-421dbd49ace6.png)

![image](https://user-images.githubusercontent.com/4235722/141528103-60bc328b-f5ae-4ed7-b977-770b55ac5b84.png)

Can you provide more details about your configuration? Do you use S3 or something 🤔
