### ISSUE TITLE
Allow reposilite to store upstream caches in a different location

### ISSUE THREAD

**Issue by ChanthMiao** [dzikoysk/reposilite#913]
### Request details

**Feature Request**: Assign some option like storageProvider to proxied repo, allowing reposilite to store upstream caches in a different location rather than mixed with self hosted packages.

I works withs a non-standard machine arch, which not supported by any known public jdk distribution. A internal private jdk is available, but I need modifying some java packages, which are architecture sensitive, to make maven build works fine. For a long time , installing modified packages to `~/.m2/repositories` is ok. 

I setup a reposilite server for internal use. It works pretty well, except mixing proxied caches with self host packages in the same location. It makes me hard to distinguish self host packages and proxied caches, even I can acess the reposilite storage directly.

**Comment by dzikoysk** [comment]
In theory it should be possible to proxy internal Reposilite repository. Did you try to do sth like:

```
/releases {
  proxied {
    your-repository.com/proxied
  }
}
/proxied {
  proxied {
    proxied-host.com/releases --store
  }
}

**Comment by ChanthMiao** [comment]
> In theory it should be possible to proxy internal Reposilite repository. Did you try to do sth like:
> 
> ```
> /releases {
>   proxied {
>     your-repository.com/proxied
>   }
> }
> /proxied {
>   proxied {
>     proxied-host.com/releases --store
>   }
> }
> ```
> 
> So proxied artifacts are stored in `proxied` repository and the `releases` repository just fetches them. I guess we could add a possibility to specify the name of internal repository instead of external url. Do you think it would be enough to handle such cases?

interesting!  I will have a try next monday in the company.

**Comment by dzikoysk** [comment]
Sure, let me know how it works for you :)

**Comment by ChanthMiao** [comment]
Unfortunately，I host the reposilite in a ppc64le server.
```
Caused by: java.lang.Exception: No native library found for os.name=Linux, os.arch=ppc64le, paths=[/usr/java/packages/lib:/usr/lib/powerpc64le-linux-gnu/jni:/lib/powerpc64le-linux-gnu:/usr/lib/powerpc64le-linux-gnu:/usr/lib/jni:/lib:/usr/lib]
        at org.sqlite.SQLiteJDBCLoader.loadSQLiteNativeLibrary(SQLiteJDBCLoader.java:389)
        at org.sqlite.SQLiteJDBCLoader.initialize(SQLiteJDBCLoader.java:68)
        at org.sqlite.core.NativeDB.load(NativeDB.java:63)
        at org.sqlite.SQLiteConnection.open(SQLiteConnection.java:240)
```

**Comment by ChanthMiao** [comment]
It works, thanks!

Now the only pronlem is that, the reposilite will make self network request to get proxied repo. It is a little unreasonable.

**Comment by dzikoysk** [comment]
That's what I thought, I think we can try to support direct proxied repositories to avoid a need to use external network. I'll mark it as enhancement for now.
