### ISSUE TITLE
Allow script to be run to potentially generate a missing version

### ISSUE THREAD

**Issue by Redempt** [dzikoysk/reposilite#941]
I'm looking for something that could replace jitpack for me, and my end goal is to have a repository that can automatically build missing versions from my GitHub repo. It doesn't seem possible currently, but if you were to allow a script to be configured (#555 could also be a solution here) that would be run for a missing version of an artifact and check again for the presence of the artifact after it was run, it would make this possible.

**Comment by dzikoysk** [comment]
Should be possible with `reposilite-3.0.0-alpha.14.jar` and plugin API :) `ResolveEvent` might be useful to detect requested artifacts.
