### ISSUE TITLE
Discord Webhook integration for new deployments

### ISSUE THREAD

**Issue by hypherionmc** [dzikoysk/reposilite#957]
### Request details

Would it be possible to add support for discord webhooks (preferably multiple per repository) so a message can be sent to discord when a new deployment is made?

You can use this library for handling the webhooks themselves: https://github.com/MinnDevelopment/discord-webhooks

**Comment by ChachyDev** [comment]
Would say this is kind of a duplicate of https://github.com/dzikoysk/reposilite/issues/844

**Comment by hypherionmc** [comment]
Oh, yeah I would say so too. Sorry didn't see that one. I'll add the "library" comment on there and close this
