### ISSUE TITLE
JavaDoc Hosting

### ISSUE THREAD

**Issue by TOTHT0MI** [dzikoysk/reposilite#993]
### Request details

(I've searched a lot but couldn't find any requests related to this topic, so here I am, but sorry if it's a duplicate)

My **idea/request** is simple:

Host JavaDoc pages from the maven repo -javadoc.jar file as a static page in an iframe.
The iframe would be embedded in the main site on a separate route. (For security the headers would only allow iframes from the same-origin)
This feature would also introduce a separate badge that would show the version of the latest JavaDoc available for a specified artifact or N/A if there are no available ones.

If it detects that the published artifact has a Javadoc generated along with it, with RegExp for example; the backend could extract the HTML content with the following:
The -javadoc.jar file is actually just like a "zip", it only contains the HTML pages. By running the command: `jar xf *-javadoc.jar`, it will extract the jar's content into the folder it's in. (* would be the artifact name).

(P.S: I'd create a pull request and implement it myself, but I don't have much experience with Kotlin, Javalin, and especially with your codebase. Once I learn it - will probably do - I most likely come back and implement it myself, if someone else hasn't implemented it by that time)

**Comment by dzikoysk** [comment]
Interesting! I think it could be great to somehow host these pages, but I don't think that the iframe concept is a good idea 🤔 Imo we should support this though standalone route repo.domain.com/javadocs/<artifact url>, it looks better and we can host it as a standard page (such as e.g. /swagger)

**Comment by dzikoysk** [comment]
As I see you've forked Reposilite, keep in mind that #981 is quite breaking as it refactors a lot of things. I'd suggest to wait a little bit, because I'm about to finish it soon :)

**Comment by TOTHT0MI** [comment]
Sure, thanks for notifying me!
I'm still going over how things are structured and interact with each other, and will only experiment at the moment, coming up with how to do it most efficiently. :)

So that breaking refactor will not be a problem, as I would implement it from scratch free of junk code after experimentation and after I've settled on a working solution.

**Comment by dzikoysk** [comment]
Sure, let me know about confusing parts, I'd like to prepare quick page for people that don't know Kotlin to simplify contribution process. I'm quite sure that with such a post people that know Java should be able to learn Kotlin in about 5mins, as it works pretty much the same, it's all about this extra syntax sugar :)

**Comment by dzikoysk** [comment]
>Will probably use the event system to listen for deploys and handle the JavaDoc extraction there.
Maybe move this entire thing into a plugin as an optional addon.

I think it would be easier if extraction could be performed for the 1st `/javadocs` request for the given artifact, so:
1. We can generate JavaDocs not only for deployed artifacts, but also all that are already in repo and for proxied ones
2. We'll reduce the resources usage as most people don't really need JavaDocs for each artifact

**Comment by TOTHT0MI** [comment]
> > Will probably use the event system to listen for deploys and handle the JavaDoc extraction there.
> > Maybe move this entire thing into a plugin as an optional addon.
> 
> I think it would be easier if extraction could be performed for the 1st `/javadocs` request for the given artifact, so:
> 
> 1. We can generate JavaDocs not only for deployed artifacts, but also all that are already in repo and for proxied ones
> 2. We'll reduce the resources usage as most people don't really need JavaDocs for each artifact

Oh yeah, makes sense, didn't think about that, this will also simplify the process as I won't need to touch the current code, and only get like the Repository and StorageProvider.

**Comment by dzikoysk** [comment]
Right :) Also, not sure if you know about it, but there's some content that could be helpful during interacting with the codebase:

* https://github.com/dzikoysk/reposilite/blob/main/.github/CONTRIBUTING.md

**Comment by Sundev79** [comment]
Maybe create a index of pages and a search-bar on the frontend for get documentation more easy.
The JavaDoc will be extracted into a separated hidden directory called **.docs/** who contains :

- A index file, contains all indexed docs-repo on the docs repo
- Extracted javadoc files with the name of the repo, with a subdirectory named with the right versionName of the package.
  For page versioning.
- a other index file for stores the index-pages, inside the right concerned docs-repo.

**Comment by dzikoysk** [comment]
Yeah, I think that some kind of a hidden directory for these pages might work for us to build some kind of persistent cache. The browser sounds interesting, but I don't think we really need this, especially during implement the base of this request. If you feel some kind of extra UI is really needed, I guess we can address it in another issue when this one will be done.

**Comment by TOTHT0MI** [comment]
Ok, decided to wait until the refactoring is done until then I will get familiar with the codebase and especially with the storage provider design so implementing it won't be difficult because in theory, it's a pretty simple thing to implement.

**Comment by dzikoysk** [comment]
Ok, so the plugin platform is done, let me know how it works, so we can find a way to improve it :)

**Comment by TOTHT0MI** [comment]
> Ok, so the plugin platform is done, let me know how it works, so we can find a way to improve it :)

I see you've made an example in Java, which is awesome I may write that plugin in Java then cause will be much easier for me and afaik you can convert any Java files to Kotlin at any time.

Will try it out once the holiday has passed and will let you know!
It seems fine at first glance, but I may recommend using a system like in Bukkit, where you have a Listener class that can listen to many events in it. This could also support plugins calling custom events as well.

Little example of the structure (with random names):
```java
class Something implements Listener {
    @EventHandler
    public void onInitialized(PluginInitializeEvent e) {
        [...]
        EventSystem.callEvent(new CustomEvent([...]))
    }
}
```

**Comment by ChachyDev** [comment]
> > Ok, so the plugin platform is done, let me know how it works, so we can find a way to improve it :)
> 
> I see you've made an example in Java, which is awesome I may write that plugin in Java then cause will be much easier for me and afaik you can convert any Java files to Kotlin at any time.
> 
> Will try it out once the holiday has passed and will let you know! It seems fine at first glance, but I may recommend using a system like in Bukkit, where you have a Listener class that can listen to many events in it. This could also support plugins calling custom events as well.
> 
> Little example of the structure (with random names):
> 
> ```java
> class Something implements Listener {
>     @EventHandler
>     public void onInitialized(PluginInitializeEvent e) {
>         [...]
>         EventSystem.callEvent(new CustomEvent([...]))
>     }
> }
> ```

Just chipping in, I believe the event system should be rather abstract meaning that many interpretations of it can be made instead of a forced one. For example your example could be implemented but also allowing for a DSL for Kotlin plugin users

**Comment by dzikoysk** [comment]
Everyone can implement custom Event through Event interface and listen to it with Listener interface (that is functional by default):

* https://github.com/dzikoysk/reposilite/blob/main/reposilite-backend/src/main/kotlin/com/reposilite/plugin/api/Event.kt

To call event, you just simply need `Extensions` instance (available in superclass in `ReposilitePlugin) and emit it:

```java
CustomEvent event = extensions.emitEvent(new CustomEvent(params));
```

I guess it should be enough 🤔

**Comment by TOTHT0MI** [comment]
@dzikoysk Is the API for the plugin system hosted on some kind of repo, or do I need to set up one locally, so I can work clean in my own git repo, compile the plugin and test it? And because I'm at it, should the JavaDoc be an installable plugin or a built-in feature that uses the plugin API?

**Comment by dzikoysk** [comment]
Reposilite is hosted on repo.panda-lang.org:

* https://repo.panda-lang.org/#/releases/org/panda-lang/reposilite
* https://github.com/dzikoysk/reposilite/tree/main/reposilite-plugins (examples)

There is no big difference between internal plugin and standalone plugin, so it's up to you for now I guess. We can decide how to distribute this when you'll finish, as I still don't have a clear policy about to manage the plugin ecosystem 😅

**Comment by TOTHT0MI** [comment]
> Reposilite is hosted on repo.panda-lang.org:
> 
> * https://repo.panda-lang.org/#/releases/org/panda-lang/reposilite
> * https://github.com/dzikoysk/reposilite/tree/main/reposilite-plugins (examples)
> 
> There is no big difference between internal plugin and standalone plugin, so it's up to you for now I guess. We can decide how to distribute this when you'll finish, as I still don't have a clear policy about management of the whole plugin ecosystem yet 😅

Could only find this related to version 3, however it does not contain the latest versions of v3, I guess I will use the forked repo and project() to get access to it.

**Comment by TOTHT0MI** [comment]
So I've set up the repo for the plugin development, however, when I run the backend the custom plugins in /test/workspace/plugins/ are not loaded (incl. the example ones); other than that the application starts fine.

BTW I ran the backend via Intellij, my stupid Gradle decided that the folder reposilite-plugins is also a module and doesn't proceed, because it cannot run it (will figure it out later, so I've built the plugin and I checked, it's indeed in the plugins folder).

Any idea?

**Comment by dzikoysk** [comment]
> Could only find this related to version 3, however it does not contain the latest versions of v3, I guess I will use the forked repo and project() to get access to it.

There is 3.0.0-alpha.15 and that's the latest version 🤔

**Comment by dzikoysk** [comment]
> So I've set up the repo for the plugin development, however, when I run the backend the custom plugins in /test/workspace/plugins/ are not loaded (incl. the example ones); other than that the application starts fine.
> 
> BTW I ran the backend via Intellij, my stupid Gradle decided that the folder reposilite-plugins is also a module and doesn't proceed, because it cannot run it (will figure it out later, so I've built the plugin and I checked, it's indeed in the plugins folder).
> 
> Any idea?

Could you share startup logs?

**Comment by TOTHT0MI** [comment]
> > So I've set up the repo for the plugin development, however, when I run the backend the custom plugins in /test/workspace/plugins/ are not loaded (incl. the example ones); other than that the application starts fine.
> > BTW I ran the backend via Intellij, my stupid Gradle decided that the folder reposilite-plugins is also a module and doesn't proceed, because it cannot run it (will figure it out later, so I've built the plugin and I checked, it's indeed in the plugins folder).
> > Any idea?
> 
> Could you share startup logs?

https://pastebin.com/zi9PfZFi

**Comment by TOTHT0MI** [comment]
> 

Not sure then, will try it again though

**Comment by dzikoysk** [comment]
> > > So I've set up the repo for the plugin development, however, when I run the backend the custom plugins in /test/workspace/plugins/ are not loaded (incl. the example ones); other than that the application starts fine.
> > > BTW I ran the backend via Intellij, my stupid Gradle decided that the folder reposilite-plugins is also a module and doesn't proceed, because it cannot run it (will figure it out later, so I've built the plugin and I checked, it's indeed in the plugins folder).
> > > Any idea?
> > 
> > 
> > Could you share startup logs?
> 
> https://pastebin.com/zi9PfZFi

```
14:35:54.571 INFO | Working directory: [REDECATED]\reposilite\reposilite-backend
```

Looks like you didn't launch it in `workspace` directory :)

**Comment by TOTHT0MI** [comment]
Ok, implementing the hosting now (may take some time, cause holidays). One idea for the plugin system:

Via extensions() I can access a Collection of Facades, now the problem is, that I need to loop over it, and check whether a Facade is the one I'm looking for.

I don't know how these are stored but I'd suggest a Map with their class as a key, so I could just do: extensions().getFacade(MavenFacade.class), which would of course return the MavenFacade already casted.

**Comment by dzikoysk** [comment]
With Kotlin, you can just simply use reified function:

```kotlin
val mavenFacade = extensions().facade<MavenFacade>() // gets facade by generic type
```

But yeah, it misses standard class based getter for Java API. I'll add in next release. Btw you're trying to write it in Java or Kotlin?

**Comment by TOTHT0MI** [comment]
> With Kotlin, you can just simply use reified function:
> 
> ```kotlin
> val mavenFacade = extensions().facade<MavenFacade>() // gets facade by generic type
> ```
> 
> But yeah, it misses standard class based getter for Java API. I'll add in next release. Btw you're trying to write it in Java or Kotlin?

Well first in Java, because I feel more comfortable with it, but I assume it can easily be converted into Kotlin down the line.

**Comment by dzikoysk** [comment]
I think it might be easier to start with Kotlin rather than trying to convert it later, as it'll be quite messy. I know it from experience, as I pretty much started to learn it at first from automatically converted codebases and that was just a bad decision imo 😅 If you'll find some troubles with Kotlin, you can ask on Discord about any programming-related stuff and I hope we'll find a way to help you.

**Comment by TOTHT0MI** [comment]
Hi, I was about to get the systems together after some experimentation, but suddenly when I start the application it exits with the following exception, it is weird because I didn't touch anything and last time it booted up perfectly.

```
14:49:39.398 INFO | 
14:49:39.400 INFO | Reposilite 3.0.0-alpha.15
14:49:39.400 INFO | 
14:49:39.401 INFO | --- Environment
14:49:39.401 INFO | Platform: 16.0.2 (Windows 10)
14:49:39.401 INFO | Working directory: [REDACATED]\reposilite\reposilite-backend\src\test\workspace
14:49:39.401 INFO | Threads: 32 WEB / 16 IO
Exception in thread "main" java.util.ServiceConfigurationError: com.reposilite.plugin.api.ReposilitePlugin: Provider com.reposilite.plugin.javadoc.JavadocPlugin not found
	at java.base/java.util.ServiceLoader.fail(ServiceLoader.java:589)
	at java.base/java.util.ServiceLoader$LazyClassPathLookupIterator.nextProviderClass(ServiceLoader.java:1211)
	at java.base/java.util.ServiceLoader$LazyClassPathLookupIterator.hasNextService(ServiceLoader.java:1220)
	at java.base/java.util.ServiceLoader$LazyClassPathLookupIterator.hasNext(ServiceLoader.java:1264)
	at java.base/java.util.ServiceLoader$2.hasNext(ServiceLoader.java:1299)
	at java.base/java.util.ServiceLoader$3.hasNext(ServiceLoader.java:1383)
	at com.reposilite.plugin.PluginLoaderKt.loadExternalPlugins(PluginLoader.kt:77)
	at com.reposilite.ReposiliteFactory.createReposilite(ReposiliteFactory.kt:56)
	at com.reposilite.ReposiliteFactory.createReposilite(ReposiliteFactory.kt:34)
	at com.reposilite.ReposiliteLauncherKt.createWithParameters(ReposiliteLauncher.kt:34)
	at com.reposilite.ReposiliteLauncherKt.main(ReposiliteLauncher.kt:38)
```

When I remove the file `com.reposilite.plugin.api.ReposilitePlugin` from `javadocplugin/[...]/resources/META-INF.services/` - as expected - it boots up. Now the weird thing about this, that my service file points to an existing class, so it should be findable.
![image](https://user-images.githubusercontent.com/36101494/147852045-57f88141-61b9-420c-a9d2-c6e5a42ed0cd.png)

build.gradle.kts:
```kts
import com.github.jengelman.gradle.plugins.shadow.tasks.ShadowJar

group = "com.reposilite.plugins"

application {
    mainClass.set("com.reposilite.plugin.javadoc.JavadocPlugin")
}

dependencies {
    // compileOnly("org.panda-lang:reposilite:version") for external plugins

    compileOnly(project(":reposilite-backend"))
}

tasks.withType<ShadowJar> {
    archiveFileName.set("javadoc-plugin.jar")
    destinationDirectory.set(file("$rootDir/reposilite-backend/src/test/workspace/plugins"))
    mergeServiceFiles()
}
```

I've deleted the file, I've run `gradle clean` on the whole project, on the plugin separately, but I cannot figure out the issue.
And so I've given up and written this issue to hopefully have it figured out.

(p.s: I'll probably use Discord for further conversation if you wish so, but I thought that this bug is so weird, that it's probably best to submit it on GitHub, so in the future, if someone encounters this issue again, can figure it out)

**Comment by dzikoysk** [comment]
Your main class should be  `mainClass.set("com.reposilite.plugin.javadoc.JavadocPluginKt")` probably, because Kotlin uses `Kt` suffix in class files :) Shadow plugin cannot properly build JAR when it doesn't have proper main class (should throw warning/exception during `gradle build` task)

**Comment by TOTHT0MI** [comment]
> com.reposilite.plugin.javadoc.JavadocPluginKt

Tried it, no luck, still got the same error.

**Comment by dzikoysk** [comment]
`Exception in thread "main" java.util.ServiceConfigurationError: com.reposilite.plugin.api.ReposilitePlugin: Provider com.reposilite.plugin.javadoc.JavadocPlugin not found` means there is no such class on classpath, could you open your `javadoc-plugin.jar` as zip and see if there is such class in the given package?

**Comment by TOTHT0MI** [comment]
> `Exception in thread "main" java.util.ServiceConfigurationError: com.reposilite.plugin.api.ReposilitePlugin: Provider com.reposilite.plugin.javadoc.JavadocPlugin not found` means there is no such class on classpath, could you open your `javadoc-plugin.jar` as zip and see if there is such class in the given package?

Oh my...
Gradle only includes the META-INF and ignores the entire source...

**Comment by dzikoysk** [comment]
Rename `java` directory to `kotlin` :)

**Comment by TOTHT0MI** [comment]
> Rename `java` directory to `kotlin` in your sources :)

Oh well... Yeah now it has a source so I assume it's gonna boot up. The more you know, yeah forgot to do that when converting from java to Kotlin. Thanks.
